/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#ifndef R_CMTW_CFG_H_
#define R_CMTW_CFG_H_
#define CMTW_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define CMTW_CFG_MULTIPLEX_INTERRUPT_SUPPORTED (0)
#if CMTW_CFG_MULTIPLEX_INTERRUPT_SUPPORTED
 #define CMTW_CFG_MULTIPLEX_INTERRUPT_ENABLE         BSP_INTERRUPT_ENABLE
 #define CMTW_CFG_MULTIPLEX_INTERRUPT_DISABLE        BSP_INTERRUPT_DISABLE
#else
#define CMTW_CFG_MULTIPLEX_INTERRUPT_ENABLE
#define CMTW_CFG_MULTIPLEX_INTERRUPT_DISABLE
#endif
#endif /* R_CMTW_CFG_H_ */
