/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#ifndef R_SPI_CFG_H_
#define R_SPI_CFG_H_
#define SPI_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define SPI_DMAC_SUPPORT_ENABLE CONFIG_SPI_RENESAS_RZ_DMA
#define SPI_TRANSMIT_FROM_RXI_ISR (0)
#define SPI_CFG_MULTIPLEX_INTERRUPT_SUPPORTED (0)
#if SPI_CFG_MULTIPLEX_INTERRUPT_SUPPORTED
 #define SPI_CFG_MULTIPLEX_INTERRUPT_ENABLE         BSP_INTERRUPT_ENABLE
 #define SPI_CFG_MULTIPLEX_INTERRUPT_DISABLE        BSP_INTERRUPT_DISABLE
#else
#define SPI_CFG_MULTIPLEX_INTERRUPT_ENABLE
#define SPI_CFG_MULTIPLEX_INTERRUPT_DISABLE
#endif
#endif /* R_SPI_CFG_H_ */
