/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

/**********************************************************************************************************************
 * File Name    : adc_e_iobitmask.h
 * Version      : 1.00
 * Description  : IO bit mask file for adc_e.
 *********************************************************************************************************************/

#ifndef ADC_E_IOBITMASK_H
#define ADC_E_IOBITMASK_H

#define R_ADC_E_ADCSR_DBLANS_Msk          (0x001FUL)
#define R_ADC_E_ADCSR_DBLANS_Pos          (0UL)
#define R_ADC_E_ADCSR_GBADIE_Msk          (0x0040UL)
#define R_ADC_E_ADCSR_GBADIE_Pos          (6UL)
#define R_ADC_E_ADCSR_DBLE_Msk            (0x0080UL)
#define R_ADC_E_ADCSR_DBLE_Pos            (7UL)
#define R_ADC_E_ADCSR_EXTRG_Msk           (0x0100UL)
#define R_ADC_E_ADCSR_EXTRG_Pos           (8UL)
#define R_ADC_E_ADCSR_TRGE_Msk            (0x0200UL)
#define R_ADC_E_ADCSR_TRGE_Pos            (9UL)
#define R_ADC_E_ADCSR_ADIE_Msk            (0x1000UL)
#define R_ADC_E_ADCSR_ADIE_Pos            (12UL)
#define R_ADC_E_ADCSR_ADCS_Msk            (0x6000UL)
#define R_ADC_E_ADCSR_ADCS_Pos            (13UL)
#define R_ADC_E_ADCSR_ADST_Msk            (0x8000UL)
#define R_ADC_E_ADCSR_ADST_Pos            (15UL)
#define R_ADC_E_ADREF_ADF_Msk             (0x01UL)
#define R_ADC_E_ADREF_ADF_Pos             (0UL)
#define R_ADC_E_ADREF_ADSCACT_Msk         (0x80UL)
#define R_ADC_E_ADREF_ADSCACT_Pos         (7UL)
#define R_ADC_E_ADANSA0_ANSA0_Msk         (0x00FFUL)
#define R_ADC_E_ADANSA0_ANSA0_Pos         (0UL)
#define R_ADC_E_ADADS0_ADS0_Msk           (0x00FFUL)
#define R_ADC_E_ADADS0_ADS0_Pos           (0UL)
#define R_ADC_E_ADADC_ADC_Msk             (0x07UL)
#define R_ADC_E_ADADC_ADC_Pos             (0UL)
#define R_ADC_E_ADADC_AVEE_Msk            (0x80UL)
#define R_ADC_E_ADADC_AVEE_Pos            (7UL)
#define R_ADC_E_ADCER_ADPRC_Msk           (0x0006UL)
#define R_ADC_E_ADCER_ADPRC_Pos           (1UL)
#define R_ADC_E_ADCER_ACE_Msk             (0x0020UL)
#define R_ADC_E_ADCER_ACE_Pos             (5UL)
#define R_ADC_E_ADCER_ADRFMT_Msk          (0x8000UL)
#define R_ADC_E_ADCER_ADRFMT_Pos          (15UL)
#define R_ADC_E_ADSTRGR_TRSB_Msk          (0x003FUL)
#define R_ADC_E_ADSTRGR_TRSB_Pos          (0UL)
#define R_ADC_E_ADSTRGR_TRSA_Msk          (0x3F00UL)
#define R_ADC_E_ADSTRGR_TRSA_Pos          (8UL)
#define R_ADC_E_ADANSB0_ANSB0_Msk         (0x00FFUL)
#define R_ADC_E_ADANSB0_ANSB0_Pos         (0UL)
#define R_ADC_E_ADDBLDR_DBLDR_Msk         (0xFFFFUL)
#define R_ADC_E_ADDBLDR_DBLDR_Pos         (0UL)
#define R_ADC_E_ADDR0_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR0_DR_Pos              (0UL)
#define R_ADC_E_ADDR1_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR1_DR_Pos              (0UL)
#define R_ADC_E_ADDR2_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR2_DR_Pos              (0UL)
#define R_ADC_E_ADDR3_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR3_DR_Pos              (0UL)
#define R_ADC_E_ADDR4_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR4_DR_Pos              (0UL)
#define R_ADC_E_ADDR5_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR5_DR_Pos              (0UL)
#define R_ADC_E_ADDR6_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR6_DR_Pos              (0UL)
#define R_ADC_E_ADDR7_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR7_DR_Pos              (0UL)
#define R_ADC_E_ADELCCR_ELCC_Msk          (0x03UL)
#define R_ADC_E_ADELCCR_ELCC_Pos          (0UL)
#define R_ADC_E_ADELCCR_GCELC_Msk         (0x04UL)
#define R_ADC_E_ADELCCR_GCELC_Pos         (2UL)
#define R_ADC_E_ADGSPCR_PGS_Msk           (0x0001UL)
#define R_ADC_E_ADGSPCR_PGS_Pos           (0UL)
#define R_ADC_E_ADGSPCR_GBRSCN_Msk        (0x0002UL)
#define R_ADC_E_ADGSPCR_GBRSCN_Pos        (1UL)
#define R_ADC_E_ADGSPCR_LGRRS_Msk         (0x4000UL)
#define R_ADC_E_ADGSPCR_LGRRS_Pos         (14UL)
#define R_ADC_E_ADGSPCR_GBRP_Msk          (0x8000UL)
#define R_ADC_E_ADGSPCR_GBRP_Pos          (15UL)
#define R_ADC_E_ADDBLDRA_DBLDRA_Msk       (0xFFFFUL)
#define R_ADC_E_ADDBLDRA_DBLDRA_Pos       (0UL)
#define R_ADC_E_ADDBLDRB_DBLDRB_Msk       (0xFFFFUL)
#define R_ADC_E_ADDBLDRB_DBLDRB_Pos       (0UL)
#define R_ADC_E_ADWINMON_MONCOMB_Msk      (0x01UL)
#define R_ADC_E_ADWINMON_MONCOMB_Pos      (0UL)
#define R_ADC_E_ADWINMON_MONCMPA_Msk      (0x10UL)
#define R_ADC_E_ADWINMON_MONCMPA_Pos      (4UL)
#define R_ADC_E_ADWINMON_MONCMPB_Msk      (0x20UL)
#define R_ADC_E_ADWINMON_MONCMPB_Pos      (5UL)
#define R_ADC_E_ADCMPCR_CMPAB_Msk         (0x0003UL)
#define R_ADC_E_ADCMPCR_CMPAB_Pos         (0UL)
#define R_ADC_E_ADCMPCR_CMPBE_Msk         (0x0200UL)
#define R_ADC_E_ADCMPCR_CMPBE_Pos         (9UL)
#define R_ADC_E_ADCMPCR_CMPAE_Msk         (0x0800UL)
#define R_ADC_E_ADCMPCR_CMPAE_Pos         (11UL)
#define R_ADC_E_ADCMPCR_CMPBIE_Msk        (0x2000UL)
#define R_ADC_E_ADCMPCR_CMPBIE_Pos        (13UL)
#define R_ADC_E_ADCMPCR_WCMPE_Msk         (0x4000UL)
#define R_ADC_E_ADCMPCR_WCMPE_Pos         (14UL)
#define R_ADC_E_ADCMPCR_CMPAIE_Msk        (0x8000UL)
#define R_ADC_E_ADCMPCR_CMPAIE_Pos        (15UL)
#define R_ADC_E_ADCMPANSR0_CMPCHA0_Msk    (0x00FFUL)
#define R_ADC_E_ADCMPANSR0_CMPCHA0_Pos    (0UL)
#define R_ADC_E_ADCMPLR0_CMPLCHA0_Msk     (0x00FFUL)
#define R_ADC_E_ADCMPLR0_CMPLCHA0_Pos     (0UL)
#define R_ADC_E_ADCMPDR0_CMPLLA_Msk       (0xFFFFUL)
#define R_ADC_E_ADCMPDR0_CMPLLA_Pos       (0UL)
#define R_ADC_E_ADCMPDR1_CMPULA_Msk       (0xFFFFUL)
#define R_ADC_E_ADCMPDR1_CMPULA_Pos       (0UL)
#define R_ADC_E_ADCMPSR0_CMPSTCHA0_Msk    (0x00FFUL)
#define R_ADC_E_ADCMPSR0_CMPSTCHA0_Pos    (0UL)
#define R_ADC_E_ADCMPBNSR_CMPCHB_Msk      (0x3FUL)
#define R_ADC_E_ADCMPBNSR_CMPCHB_Pos      (0UL)
#define R_ADC_E_ADCMPBNSR_CMPLB_Msk       (0x80UL)
#define R_ADC_E_ADCMPBNSR_CMPLB_Pos       (7UL)
#define R_ADC_E_ADWINLLB_CMPLLB_Msk       (0xFFFFUL)
#define R_ADC_E_ADWINLLB_CMPLLB_Pos       (0UL)
#define R_ADC_E_ADWINULB_CMPULB_Msk       (0xFFFFUL)
#define R_ADC_E_ADWINULB_CMPULB_Pos       (0UL)
#define R_ADC_E_ADCMPBSR_CMPSTB_Msk       (0x01UL)
#define R_ADC_E_ADCMPBSR_CMPSTB_Pos       (0UL)
#define R_ADC_E_ADANSC0_ANSC0_Msk         (0x00FFUL)
#define R_ADC_E_ADANSC0_ANSC0_Pos         (0UL)
#define R_ADC_E_ADGCTRGR_TRSC_Msk         (0x3FUL)
#define R_ADC_E_ADGCTRGR_TRSC_Pos         (0UL)
#define R_ADC_E_ADGCTRGR_GCADIE_Msk       (0x40UL)
#define R_ADC_E_ADGCTRGR_GCADIE_Pos       (6UL)
#define R_ADC_E_ADGCTRGR_GRCE_Msk         (0x80UL)
#define R_ADC_E_ADGCTRGR_GRCE_Pos         (7UL)
#define R_ADC_E_ADERCR_OWEIE_Msk          (0x04UL)
#define R_ADC_E_ADERCR_OWEIE_Pos          (2UL)
#define R_ADC_E_ADERCLR_OWEC_Msk          (0x04UL)
#define R_ADC_E_ADERCLR_OWEC_Pos          (2UL)
#define R_ADC_E_ADOWER_OWE_Msk            (0x00FFUL)
#define R_ADC_E_ADOWER_OWE_Pos            (0UL)
#define R_ADC_E_ADOWEER_DBOWE_Msk         (0x0001UL)
#define R_ADC_E_ADOWEER_DBOWE_Pos         (0UL)
#define R_ADC_E_ADOWEER_DAOWE_Msk         (0x0002UL)
#define R_ADC_E_ADOWEER_DAOWE_Pos         (1UL)
#define R_ADC_E_ADOWEER_DOWE_Msk          (0x0004UL)
#define R_ADC_E_ADOWEER_DOWE_Pos          (2UL)

#endif
