/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

/**********************************************************************************************************************
 * File Name    : rtc_iobitmask.h
 * Version      : 1.00
 * Description  : IO bit mask file for rtc.
 *********************************************************************************************************************/

#ifndef RTC_IOBITMASK_H
#define RTC_IOBITMASK_H

#define R_RTC_R64CNT_F64HZ_Msk      (0x01UL)
#define R_RTC_R64CNT_F64HZ_Pos      (0UL)
#define R_RTC_R64CNT_F32HZ_Msk      (0x02UL)
#define R_RTC_R64CNT_F32HZ_Pos      (1UL)
#define R_RTC_R64CNT_F16HZ_Msk      (0x04UL)
#define R_RTC_R64CNT_F16HZ_Pos      (2UL)
#define R_RTC_R64CNT_F8HZ_Msk       (0x08UL)
#define R_RTC_R64CNT_F8HZ_Pos       (3UL)
#define R_RTC_R64CNT_F4HZ_Msk       (0x10UL)
#define R_RTC_R64CNT_F4HZ_Pos       (4UL)
#define R_RTC_R64CNT_F2HZ_Msk       (0x20UL)
#define R_RTC_R64CNT_F2HZ_Pos       (5UL)
#define R_RTC_R64CNT_F1HZ_Msk       (0x40UL)
#define R_RTC_R64CNT_F1HZ_Pos       (6UL)
#define R_RTC_RSECCNT_SEC1_Msk      (0x0FUL)
#define R_RTC_RSECCNT_SEC1_Pos      (0UL)
#define R_RTC_RSECCNT_SEC10_Msk     (0x70UL)
#define R_RTC_RSECCNT_SEC10_Pos     (4UL)
#define R_RTC_BCNT0_BCNT_Msk        (0xFFUL)
#define R_RTC_BCNT0_BCNT_Pos        (0UL)
#define R_RTC_RMINCNT_MIN1_Msk      (0x0FUL)
#define R_RTC_RMINCNT_MIN1_Pos      (0UL)
#define R_RTC_RMINCNT_MIN10_Msk     (0x70UL)
#define R_RTC_RMINCNT_MIN10_Pos     (4UL)
#define R_RTC_BCNT1_BCNT_Msk        (0xFFUL)
#define R_RTC_BCNT1_BCNT_Pos        (0UL)
#define R_RTC_RHRCNT_HR1_Msk        (0x0FUL)
#define R_RTC_RHRCNT_HR1_Pos        (0UL)
#define R_RTC_RHRCNT_HR10_Msk       (0x30UL)
#define R_RTC_RHRCNT_HR10_Pos       (4UL)
#define R_RTC_RHRCNT_PM_Msk         (0x40UL)
#define R_RTC_RHRCNT_PM_Pos         (6UL)
#define R_RTC_BCNT2_BCNT_Msk        (0xFFUL)
#define R_RTC_BCNT2_BCNT_Pos        (0UL)
#define R_RTC_RWKCNT_DAYW_Msk       (0x07UL)
#define R_RTC_RWKCNT_DAYW_Pos       (0UL)
#define R_RTC_BCNT3_BCNT_Msk        (0xFFUL)
#define R_RTC_BCNT3_BCNT_Pos        (0UL)
#define R_RTC_RDAYCNT_DATE1_Msk     (0x0FUL)
#define R_RTC_RDAYCNT_DATE1_Pos     (0UL)
#define R_RTC_RDAYCNT_DATE10_Msk    (0x30UL)
#define R_RTC_RDAYCNT_DATE10_Pos    (4UL)
#define R_RTC_RMONCNT_MON1_Msk      (0x0FUL)
#define R_RTC_RMONCNT_MON1_Pos      (0UL)
#define R_RTC_RMONCNT_MON10_Msk     (0x10UL)
#define R_RTC_RMONCNT_MON10_Pos     (4UL)
#define R_RTC_RYRCNT_YR1_Msk        (0x000FUL)
#define R_RTC_RYRCNT_YR1_Pos        (0UL)
#define R_RTC_RYRCNT_YR10_Msk       (0x00F0UL)
#define R_RTC_RYRCNT_YR10_Pos       (4UL)
#define R_RTC_RSECAR_SEC1_Msk       (0x0FUL)
#define R_RTC_RSECAR_SEC1_Pos       (0UL)
#define R_RTC_RSECAR_SEC10_Msk      (0x70UL)
#define R_RTC_RSECAR_SEC10_Pos      (4UL)
#define R_RTC_RSECAR_ENB_Msk        (0x80UL)
#define R_RTC_RSECAR_ENB_Pos        (7UL)
#define R_RTC_BCNT0AR_BCNTAR_Msk    (0xFFUL)
#define R_RTC_BCNT0AR_BCNTAR_Pos    (0UL)
#define R_RTC_RMINAR_MIN1_Msk       (0x0FUL)
#define R_RTC_RMINAR_MIN1_Pos       (0UL)
#define R_RTC_RMINAR_MIN10_Msk      (0x70UL)
#define R_RTC_RMINAR_MIN10_Pos      (4UL)
#define R_RTC_RMINAR_ENB_Msk        (0x80UL)
#define R_RTC_RMINAR_ENB_Pos        (7UL)
#define R_RTC_BCNT1AR_BCNTAR_Msk    (0xFFUL)
#define R_RTC_BCNT1AR_BCNTAR_Pos    (0UL)
#define R_RTC_RHRAR_HR1_Msk         (0x0FUL)
#define R_RTC_RHRAR_HR1_Pos         (0UL)
#define R_RTC_RHRAR_HR10_Msk        (0x30UL)
#define R_RTC_RHRAR_HR10_Pos        (4UL)
#define R_RTC_RHRAR_PM_Msk          (0x40UL)
#define R_RTC_RHRAR_PM_Pos          (6UL)
#define R_RTC_RHRAR_ENB_Msk         (0x80UL)
#define R_RTC_RHRAR_ENB_Pos         (7UL)
#define R_RTC_BCNT2AR_BCNTAR_Msk    (0xFFUL)
#define R_RTC_BCNT2AR_BCNTAR_Pos    (0UL)
#define R_RTC_RWKAR_DAYW_Msk        (0x07UL)
#define R_RTC_RWKAR_DAYW_Pos        (0UL)
#define R_RTC_RWKAR_ENB_Msk         (0x80UL)
#define R_RTC_RWKAR_ENB_Pos         (7UL)
#define R_RTC_BCNT3AR_BCNTAR_Msk    (0xFFUL)
#define R_RTC_BCNT3AR_BCNTAR_Pos    (0UL)
#define R_RTC_RDAYAR_DATE1_Msk      (0x0FUL)
#define R_RTC_RDAYAR_DATE1_Pos      (0UL)
#define R_RTC_RDAYAR_DATE10_Msk     (0x30UL)
#define R_RTC_RDAYAR_DATE10_Pos     (4UL)
#define R_RTC_RDAYAR_ENB_Msk        (0x80UL)
#define R_RTC_RDAYAR_ENB_Pos        (7UL)
#define R_RTC_BCNT0AER_ENB_Msk      (0xFFUL)
#define R_RTC_BCNT0AER_ENB_Pos      (0UL)
#define R_RTC_RMONAR_MON1_Msk       (0x0FUL)
#define R_RTC_RMONAR_MON1_Pos       (0UL)
#define R_RTC_RMONAR_MON10_Msk      (0x10UL)
#define R_RTC_RMONAR_MON10_Pos      (4UL)
#define R_RTC_RMONAR_ENB_Msk        (0x80UL)
#define R_RTC_RMONAR_ENB_Pos        (7UL)
#define R_RTC_BCNT1AER_ENB_Msk      (0xFFUL)
#define R_RTC_BCNT1AER_ENB_Pos      (0UL)
#define R_RTC_RYRAR_YR1_Msk         (0x000FUL)
#define R_RTC_RYRAR_YR1_Pos         (0UL)
#define R_RTC_RYRAR_YR10_Msk        (0x00F0UL)
#define R_RTC_RYRAR_YR10_Pos        (4UL)
#define R_RTC_BCNT2AER_ENB_Msk      (0x00FFUL)
#define R_RTC_BCNT2AER_ENB_Pos      (0UL)
#define R_RTC_RYRAREN_ENB_Msk       (0x80UL)
#define R_RTC_RYRAREN_ENB_Pos       (7UL)
#define R_RTC_BCNT3AER_ENB_Msk      (0xFFUL)
#define R_RTC_BCNT3AER_ENB_Pos      (0UL)
#define R_RTC_RSR_AF_Msk            (0x01UL)
#define R_RTC_RSR_AF_Pos            (0UL)
#define R_RTC_RSR_CF_Msk            (0x02UL)
#define R_RTC_RSR_CF_Pos            (1UL)
#define R_RTC_RSR_PF_Msk            (0x04UL)
#define R_RTC_RSR_PF_Pos            (2UL)
#define R_RTC_RCR1_AIE_Msk          (0x01UL)
#define R_RTC_RCR1_AIE_Pos          (0UL)
#define R_RTC_RCR1_CIE_Msk          (0x02UL)
#define R_RTC_RCR1_CIE_Pos          (1UL)
#define R_RTC_RCR1_PIE_Msk          (0x04UL)
#define R_RTC_RCR1_PIE_Pos          (2UL)
#define R_RTC_RCR1_PES_Msk          (0xF0UL)
#define R_RTC_RCR1_PES_Pos          (4UL)
#define R_RTC_RCR2_START_Msk        (0x01UL)
#define R_RTC_RCR2_START_Pos        (0UL)
#define R_RTC_RCR2_RESET_Msk        (0x02UL)
#define R_RTC_RCR2_RESET_Pos        (1UL)
#define R_RTC_RCR2_ADJ30_Msk        (0x04UL)
#define R_RTC_RCR2_ADJ30_Pos        (2UL)
#define R_RTC_RCR2_AADJE_Msk        (0x10UL)
#define R_RTC_RCR2_AADJE_Pos        (4UL)
#define R_RTC_RCR2_AADJP_Msk        (0x20UL)
#define R_RTC_RCR2_AADJP_Pos        (5UL)
#define R_RTC_RCR2_HR24_Msk         (0x40UL)
#define R_RTC_RCR2_HR24_Pos         (6UL)
#define R_RTC_RCR2_CNTMD_Msk        (0x80UL)
#define R_RTC_RCR2_CNTMD_Pos        (7UL)
#define R_RTC_RADJ_ADJ_Msk          (0x3FUL)
#define R_RTC_RADJ_ADJ_Pos          (0UL)
#define R_RTC_RADJ_PMADJ_Msk        (0xC0UL)
#define R_RTC_RADJ_PMADJ_Pos        (6UL)

#endif
