/*
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

/*******************************************************************************************************************//**
 * @addtogroup BSP_MCU
 * @{
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Includes   <System Includes> , "Project Includes"
 **********************************************************************************************************************/
#include <string.h>
#include "bsp_api.h"

/***********************************************************************************************************************
 * Macro definitions
 **********************************************************************************************************************/
#if BSP_CFG_DCACHE_ENABLED || BSP_CFG_ICACHE_ENABLED
 #define BSP_PRV_MPU_PAGE_SIZE    (0x20) // MPU page size
 #define BSP_PRV_RSPAGE_DCA       (0x3)  // Enable D-Cache, write-back method
 #define BSP_PRV_RSPAGE_ICA       (0x4)  // Enable I-Cache
 #define BSP_PRV_REPAGE_V         (0x1)  // Enable area
 #define BSP_PRV_REPAGE_UAC       (0xE)  // r, w, x permitted

/* The RX74M/RX74N MPU has RPAGE[8]. */
 #define BSP_PRV_MPU_MAX_SLOTS    (8U)
#endif

/***********************************************************************************************************************
 * Typedef definitions
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Exported global variables (to be accessed by other files)
 **********************************************************************************************************************/

/** System Clock Frequency (Core Clock) */
uint32_t SystemCoreClock BSP_SECTION_EARLY_INIT;

/* Generated by linker. */
#if defined(__GNUC__) || defined(__CCRX__)
extern uint32_t __etext;
extern uint32_t __data_start__;
extern uint32_t __data_end__;
extern uint32_t __bss_start__;
extern uint32_t __bss_end__;
extern uint32_t __StackLimit;
extern uint32_t __StackTop;
#elif defined(__ICCRX__)
 #pragma section=".data16.bss"
 #pragma section=".data24.bss"
 #pragma section=".data32.bss"
 #pragma section=".data16.data"
 #pragma section=".data24.data"
 #pragma section=".data32.data"
 #pragma section=".data16.data_init"
 #pragma section=".data24.data_init"
 #pragma section=".data32.data_init"
 #pragma section=".stack"
#endif

/* Initialize static constructors */
#if defined(__GNUC__)

extern void (* __init_array_start[])(void);

extern void (* __init_array_end[])(void);
#elif defined(__ICCRX__)
extern void __call_ctors(void const *, void const *);

 #pragma section = "SHT$$PREINIT_ARRAY" const
 #pragma section = "SHT$$INIT_ARRAY" const
#endif

#if BSP_PZ_SECURE_BUILD
extern void R_BSP_SecurityInit(void);

#endif

/***********************************************************************************************************************
 * Private global variables and functions
 **********************************************************************************************************************/

BSP_WEAK_REFERENCE void R_BSP_WarmStart(bsp_warm_start_event_t event) __attribute__((noinline));

#if BSP_CFG_EARLY_INIT
static void bsp_init_uninitialized_vars(void);

#endif

#if BSP_CFG_DCACHE_ENABLED || BSP_CFG_ICACHE_ENABLED
static void bsp_init_mpu(void);

#endif

#if BSP_CFG_C_RUNTIME_INIT
static void SystemRuntimeInit(const uint32_t external);

#endif

#if BSP_CFG_C_RUNTIME_INIT
static void SystemRuntimeInit (const uint32_t external)
{
    /* Initialize C runtime environment. */
    for (uint32_t i = 0; i < g_init_info.zero_count; i++)
    {
        if (external == g_init_info.p_zero_list[i].type.external)
        {
            memset(g_init_info.p_zero_list[i].p_base, 0U,
                   ((uint32_t) g_init_info.p_zero_list[i].p_limit - (uint32_t) g_init_info.p_zero_list[i].p_base));
        }
    }

    for (uint32_t i = 0; i < g_init_info.copy_count; i++)
    {
        if (external == g_init_info.p_copy_list[i].type.external)
        {
            memcpy(g_init_info.p_copy_list[i].p_base, g_init_info.p_copy_list[i].p_load,
                   ((uint32_t) g_init_info.p_copy_list[i].p_limit - (uint32_t) g_init_info.p_copy_list[i].p_base));
        }
    }

    for (uint32_t i = 0; i < g_init_info.code_copy_count; i++)
    {
        if (external == g_init_info.p_code_copy_list[i].type.external)
        {
 #if defined(__BIG) && defined(__ICCRX__)
            uint8_t * p_base_addr = (uint8_t *) g_init_info.p_code_copy_list[i].p_base;
            uint8_t * p_load_addr = (uint8_t *) g_init_info.p_code_copy_list[i].p_load;
            for (uint32_t copied_size = 0;
                 copied_size <
                 ((uint32_t) g_init_info.p_code_copy_list[i].p_limit -
                  (uint32_t) g_init_info.p_code_copy_list[i].p_base);
                 copied_size += 4)
            {
                p_base_addr[copied_size]     = p_load_addr[copied_size + 3];
                p_base_addr[copied_size + 1] = p_load_addr[copied_size + 2];
                p_base_addr[copied_size + 2] = p_load_addr[copied_size + 1];
                p_base_addr[copied_size + 3] = p_load_addr[copied_size];
            }

 #else
            memcpy(g_init_info.p_code_copy_list[i].p_base,
                   g_init_info.p_code_copy_list[i].p_load,
                   ((uint32_t) g_init_info.p_code_copy_list[i].p_limit -
                    (uint32_t) g_init_info.p_code_copy_list[i].p_base));
 #endif
        }
    }
}

#endif

/*******************************************************************************************************************//**
 * Initialize the MCU and the runtime environment.
 **********************************************************************************************************************/
void SystemInit (void)
{
#if BSP_CFG_EARLY_INIT

    /* Initialize uninitialized BSP variables early for use in R_BSP_WarmStart. */
    bsp_init_uninitialized_vars();
#endif

    /* Call pre clock initialization hook. */
    R_BSP_WarmStart(BSP_WARM_START_RESET);

    /* Configure system clocks. */
    bsp_clock_init();

    /* Call post clock initialization hook. */
    R_BSP_WarmStart(BSP_WARM_START_POST_CLOCK);

#if BSP_CFG_C_RUNTIME_INIT

    /* Initialize data placed in internal memories. */
    SystemRuntimeInit(0);
#endif

    /* Initialize SystemCoreClock variable. */
    SystemCoreClockUpdate();

#if BSP_FEATURE_RTC_IS_AVAILABLE || BSP_FEATURE_RTC_HAS_TCEN || BSP_FEATURE_SYSC_HAS_TAMPICR1

    /* Perform RTC reset sequence to avoid unintended operation. */
    R_BSP_Init_RTC();
#endif

#if !BSP_CFG_PFS_PROTECT && defined(R_PMISC)
    R_PMISC->PWPRS = 0;                              ///< Clear BOWI bit - writing to PFSWE bit enabled
    R_PMISC->PWPRS = 1U << BSP_IO_PWPR_PFSWE_OFFSET; ///< Set PFSWE bit - writing to PFS register enabled
#endif

#if BSP_PZ_SECURE_BUILD

    /* Initialize security features. */
    R_BSP_SecurityInit();
#else
 #if  FSP_PRIV_PZ_USE_SECURE_REGS

    /* Initialize peripherals to secure mode for flat projects */
    R_BSP_RegisterProtectDisable(BSP_REG_PROTECT_SAR);
    R_PSCU->PSARB = 0U;
    FSP_HARDWARE_REGISTER_WAIT(R_PSCU->PSARB, 0U);
    R_PSCU->PSARC = 0U;
    FSP_HARDWARE_REGISTER_WAIT(R_PSCU->PSARC, 0U);
    R_PSCU->PSARD = 0U;
    FSP_HARDWARE_REGISTER_WAIT(R_PSCU->PSARD, 0U);
    R_PSCU->PSARE = 0U;
    FSP_HARDWARE_REGISTER_WAIT(R_PSCU->PSARE, 0U);
    R_PSCU->PSARF = 0U;
    FSP_HARDWARE_REGISTER_WAIT(R_PSCU->PSARF, 0U);
    R_PSCU->MSSAR = 0U;
    FSP_HARDWARE_REGISTER_WAIT(R_PSCU->MSSAR, 0U);
    R_BSP_RegisterProtectEnable(BSP_REG_PROTECT_SAR);
 #endif
#endif

#if BSP_CFG_DCACHE_ENABLED || BSP_CFG_ICACHE_ENABLED

    /* Initialize MPU. The RX MPU declares the cacheable ranges. */
    bsp_init_mpu();
#endif

#if BSP_CFG_ICACHE_ENABLED

    /* Invalidate I-Cache */
    R_CACHE->IFCACTL = (uint32_t) ((R_CACHE->IFCACTL & ~R_CACHE_IFCACTL_FL_Msk) | (1U << R_CACHE_IFCACTL_FL_Pos));

    /* Wait for the cache to flush. */
    FSP_HARDWARE_REGISTER_WAIT(R_CACHE->IFCAFCT_b.FL, 0U);

    /* Enable I-Cache. */
    R_CACHE->IFCACTL = (uint32_t) ((R_CACHE->IFCACTL & ~R_CACHE_IFCACTL_EN_Msk) | (1U << R_CACHE_IFCACTL_EN_Pos));
#endif

#if BSP_CFG_DCACHE_ENABLED

    /* Invalidate D-Cache */
    R_BSP_CacheInvalidate();

    /* Enable D-Cache. */
    R_BSP_CacheEnable();
#endif

#if BSP_FEATURE_BSP_HAS_ESWM_DOMAIN
    FSP_HARDWARE_REGISTER_WAIT(R_SYSTEM->PDCTRESWM_b.PDCSF, 0);

    if (1 == R_SYSTEM->PDCTRESWM_b.PDPGSF)
    {
        /* Turn on ESWM power domain.
         * This requires MOCO to be enabled, but MOCO is always enabled after bsp_clock_init(). */
        R_BSP_RegisterProtectDisable(BSP_REG_PROTECT_OM_LPC_BATT_SWR);
        FSP_HARDWARE_REGISTER_WAIT(
            (R_SYSTEM->PDCTRESWM & (R_SYSTEM_PDCTRESWM_PDCSF_Msk | R_SYSTEM_PDCTRESWM_PDPGSF_Msk)),
            R_SYSTEM_PDCTRESWM_PDPGSF_Msk);
        R_SYSTEM->PDCTRESWM = 0;
        FSP_HARDWARE_REGISTER_WAIT(
            (R_SYSTEM->PDCTRESWM & (R_SYSTEM_PDCTRESWM_PDCSF_Msk | R_SYSTEM_PDCTRESWM_PDPGSF_Msk)),
            0);
        R_BSP_RegisterProtectEnable(BSP_REG_PROTECT_OM_LPC_BATT_SWR);
    }
#endif

    /* Call Post C runtime initialization hook. */
    R_BSP_WarmStart(BSP_WARM_START_POST_C);

#if BSP_CFG_C_RUNTIME_INIT

    /* Initialize data placed in external memories. */
    SystemRuntimeInit(1);
#endif

    /* Initialize static constructors */
#if defined(__GNUC__)
    int32_t count = __init_array_end - __init_array_start;
    for (int32_t i = 0; i < count; i++)
    {
        if ((NULL != __init_array_start[i]) &&
            (((void (*)(void))UINTPTR_MAX) != __init_array_start[i])) // NOLINT(readability-magic-numbers)
        {
            __init_array_start[i]();
        }
    }

#elif defined(__ICCRX__)
    void const * pibase = __section_begin("SHT$$PREINIT_ARRAY");
    void const * ilimit = __section_end("SHT$$INIT_ARRAY");
    __call_ctors(pibase, ilimit);
#endif

    /* Initialize ICU events that will be used to trigger ICU interrupts. */
    bsp_irq_cfg();

    /* Call any BSP specific code. No arguments are needed so NULL is sent. */
    bsp_init(NULL);
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.
 * This function is declared as a weak symbol higher up in this file because it is meant to be overridden by a user
 * implemented version. One of the main uses for this function is to call functional safety code during the startup
 * process. To use this function just copy this function into your own code and modify it to meet your needs.
 *
 * @param[in]  event    Where the code currently is in the start up process
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* C runtime environment has not been setup so you cannot use globals. System clocks are not setup. */
    }

    if (BSP_WARM_START_POST_CLOCK == event)
    {
        /* C runtime environment has not been setup so you cannot use globals. Clocks have been initialized. */
    }
    else if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment, system clocks, and pins are all setup. */
    }
    else
    {
        /* Do nothing */
    }
}

#if BSP_CFG_EARLY_INIT

/*******************************************************************************************************************//**
 * Initialize BSP variables not handled by C runtime startup.
 **********************************************************************************************************************/
static void bsp_init_uninitialized_vars (void)
{
    g_protect_pfswe_counter = 0;

    extern volatile uint16_t g_protect_counters[];
    for (uint32_t i = 0; i < BSP_FEATURE_PRC_MAX_PROTECT_BITS; i++)
    {
        g_protect_counters[i] = 0;
    }

    extern bsp_grp_irq_nmi_cb_t g_bsp_group_irq_sources[];
    for (uint32_t i = 0; i < (BSP_FEATURE_ICU_NMIER_MAX_INDEX + 1); i++)
    {
        g_bsp_group_irq_sources[i] = 0;
    }

 #if BSP_CFG_EARLY_INIT

    /* Set SystemCoreClock to MOCO */
    SystemCoreClock = BSP_MOCO_HZ;
 #endif
}

#endif

#if BSP_CFG_DCACHE_ENABLED || BSP_CFG_ICACHE_ENABLED

/*******************************************************************************************************************//**
 * Initialize MPU.
 *
 * Programs the RX MPU RPAGE table with the cacheable regions enumerated in g_init_info.p_cacheable_list[]. The
 * linker emits the __<region>_cacheable$$ symbols from section usage. Zero-size ranges are skipped automatically.
 * Nocache carve-outs are placed at the end of each region by the linker so the cacheable range is a single
 * contiguous prefix.
 **********************************************************************************************************************/
static void bsp_init_mpu (void)
{
    uint8_t slot = 0U;

    for (uint32_t i = 0; i < g_init_info.cacheable_count; i++)
    {
        uintptr_t base  = (uintptr_t) g_init_info.p_cacheable_list[i].p_base;
        uintptr_t limit = (uintptr_t) g_init_info.p_cacheable_list[i].p_limit;

        /* Skip zero-size entries (e.g. a region whose nocache carve-out ended up covering the whole area). */
        if ((base >= limit) || (slot >= BSP_PRV_MPU_MAX_SLOTS))
        {
            continue;
        }

 #if BSP_CFG_DCACHE_ENABLED && BSP_CFG_ICACHE_ENABLED
        R_MPU->RPAGE[slot].ST = BSP_PRV_RSPAGE_ICA | BSP_PRV_RSPAGE_DCA | (base & R_MPU_RPAGE_ST_RSPN_Msk);
 #elif BSP_CFG_DCACHE_ENABLED
        R_MPU->RPAGE[slot].ST = BSP_PRV_RSPAGE_DCA | (base & R_MPU_RPAGE_ST_RSPN_Msk);
 #else
        R_MPU->RPAGE[slot].ST = BSP_PRV_RSPAGE_ICA | (base & R_MPU_RPAGE_ST_RSPN_Msk);
 #endif
        R_MPU->RPAGE[slot].EN = BSP_PRV_REPAGE_V | BSP_PRV_REPAGE_UAC |
                                ((limit - BSP_PRV_MPU_PAGE_SIZE) & R_MPU_RPAGE_EN_REPN_Msk);
        slot++;
    }

    /* Enable memory protection. */
    R_MPU->MPEN = 1;
}

#endif

/** @} (end addtogroup BSP_MCU) */
