/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#ifndef BSP_CLOCK_CFG_H_
#define BSP_CLOCK_CFG_H_
#define BSP_CFG_CLOCKS_SECURE (0)
#define BSP_CFG_CLOCKS_OVERRIDE (0)
#define BSP_CFG_MAIN_CLOCK_HZ (25000000) /* Main Clock: 25MHz */
#define BSP_CFG_PLL0 (BSP_CLOCKS_PLL0_STANDBY) /* PLL0 is standby state */
#define BSP_CFG_CLMA0_ENABLE (BSP_CLOCKS_CLMA0_ENABLE) /* CLMA0 Enabled */
#define BSP_CFG_CLMA0MASK (BSP_CLOCKS_CLMA0_ERROR_NOT_MASK) /* CLMA0 error not mask */
#define BSP_CFG_PLL0SSCEN (BSP_CLOCKS_PLL0SSCEN_DISABLE) /* PLL0 SSC Disabled */
#define BSP_CFG_PLL0MFR (7) /* MMF: 111.7kHz */
#define BSP_CFG_PLL0MRR (1) /* MRR: 1 */
#define BSP_CFG_CA55CORE0 (BSP_CLOCKS_CA55CORE0_600_MHZ) /* CA55C0CLK 600MHz */
#define BSP_CFG_CA55CORE1 (BSP_CLOCKS_CA55CORE1_600_MHZ) /* CA55C1CLK 600MHz */
#define BSP_CFG_CA55CORE2 (BSP_CLOCKS_CA55CORE2_600_MHZ) /* CA55C2CLK 600MHz */
#define BSP_CFG_CA55CORE3 (BSP_CLOCKS_CA55CORE3_600_MHZ) /* CA55C3CLK 600MHz */
#define BSP_CFG_CLMA1_ENABLE (BSP_CLOCKS_CLMA1_ENABLE) /* CLMA1 Enabled */
#define BSP_CFG_CLMA1MASK (BSP_CLOCKS_CLMA1_ERROR_NOT_MASK) /* CLMA1 error not mask */
#define BSP_CFG_CA55SCLK (BSP_CLOCKS_CA55SCLK_500_MHZ) /* CA55SCLK 500MHz */
#define BSP_CFG_CR52C0CLK (BSP_CLOCKS_CR52CPU0_500_MHZ) /* CR52C0CLK 500MHz */
#define BSP_CFG_CR52C1CLK (BSP_CLOCKS_CR52CPU1_500_MHZ) /* CR52C1CLK 500MHz */
#define BSP_CFG_CKIO (BSP_CLOCKS_CKIO_62_5_MHZ) /* CKIO Div /4 */
#define BSP_CFG_RMII_REFCLK (50000000) /* RMII_REFCLK 50000000Hz */
#define BSP_CFG_PHYSEL (BSP_CLOCKS_PHYSEL_PLL1_DIV) /* Ethernet Clock src: PLL1 divider clock */
#define BSP_CFG_ETH_REFCLK (25000000) /* ETHn_REFCLK 25000000Hz */
#define BSP_CFG_CLMA4_ENABLE (BSP_CLOCKS_CLMA4_ENABLE) /* CLMA4 Enabled */
#define BSP_CFG_CLMA4MASK (BSP_CLOCKS_CLMA4_ERROR_NOT_MASK) /* CLMA4 error not mask */
#define BSP_CFG_FSELCANFD (BSP_CLOCKS_CANFD_CLOCK_80_MHZ) /* CANFDCLK Src: PCLKCAN 80MHz */
#define BSP_CFG_ENCOUTCLK (BSP_CLOCKS_ENCO_CLOCK_80_MHZ) /* PCLKENCO: 80MHz */
#define BSP_CFG_FSELXSPI0_DIVSELXSPI0 (BSP_CLOCKS_XSPI0_CLOCK_DIV0_12_5_MHZ) /* XSPI_CLK0 12.5MHz */
#define BSP_CFG_FSELXSPI1_DIVSELXSPI1 (BSP_CLOCKS_XSPI1_CLOCK_DIV0_12_5_MHZ) /* XSPI_CLK1 12.5MHz */
#define BSP_CFG_SCI0ASYNCCLK (BSP_CLOCKS_SCI0_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCI0ASYNCCLK: 100MHz */
#define BSP_CFG_SCI1ASYNCCLK (BSP_CLOCKS_SCI1_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCI1ASYNCCLK: 100MHz */
#define BSP_CFG_SCI2ASYNCCLK (BSP_CLOCKS_SCI2_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCI2ASYNCCLK: 100MHz */
#define BSP_CFG_SCI3ASYNCCLK (BSP_CLOCKS_SCI3_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCI3ASYNCCLK: 100MHz */
#define BSP_CFG_SCI4ASYNCCLK (BSP_CLOCKS_SCI4_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCI4ASYNCCLK: 100MHz */
#define BSP_CFG_SCI5ASYNCCLK (BSP_CLOCKS_SCI5_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCI5ASYNCCLK: 100MHz */
#define BSP_CFG_SPI0ASYNCCLK (BSP_CLOCKS_SPI0_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SPI0ASYNCCLK: 100MHz */
#define BSP_CFG_SPI1ASYNCCLK (BSP_CLOCKS_SPI1_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SPI1ASYNCCLK: 100MHz */
#define BSP_CFG_SPI2ASYNCCLK (BSP_CLOCKS_SPI2_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SPI2ASYNCCLK: 100MHz */
#define BSP_CFG_SPI3ASYNCCLK (BSP_CLOCKS_SPI3_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SPI3ASYNCCLK: 100MHz */
#define BSP_CFG_SCIE0ASYNCCLK (BSP_CLOCKS_SCIE0_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCIE0ASYNCCLK: 100MHz */
#define BSP_CFG_SCIE1ASYNCCLK (BSP_CLOCKS_SCIE1_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCIE1ASYNCCLK: 100MHz */
#define BSP_CFG_SCIE2ASYNCCLK (BSP_CLOCKS_SCIE2_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCIE2ASYNCCLK: 100MHz */
#define BSP_CFG_SCIE3ASYNCCLK (BSP_CLOCKS_SCIE3_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCIE3ASYNCCLK: 100MHz */
#define BSP_CFG_SCIE4ASYNCCLK (BSP_CLOCKS_SCIE4_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCIE4ASYNCCLK: 100MHz */
#define BSP_CFG_SCIE5ASYNCCLK (BSP_CLOCKS_SCIE5_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCIE5ASYNCCLK: 100MHz */
#define BSP_CFG_SCIE6ASYNCCLK (BSP_CLOCKS_SCIE6_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCIE6ASYNCCLK: 100MHz */
#define BSP_CFG_SCIE7ASYNCCLK (BSP_CLOCKS_SCIE7_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCIE7ASYNCCLK: 100MHz */
#define BSP_CFG_SCIE8ASYNCCLK (BSP_CLOCKS_SCIE8_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCIE8ASYNCCLK: 100MHz */
#define BSP_CFG_SCIE9ASYNCCLK (BSP_CLOCKS_SCIE9_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCIE9ASYNCCLK: 100MHz */
#define BSP_CFG_SCIE10ASYNCCLK (BSP_CLOCKS_SCIE10_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCIE10ASYNCCLK: 100MHz */
#define BSP_CFG_SCIE11ASYNCCLK (BSP_CLOCKS_SCIE11_ASYNCHRONOUS_SERIAL_CLOCK_100_MHZ) /* SCIE11ASYNCCLK: 100MHz */
#define BSP_CFG_PLL3P (2) /* P-divider=2 */
#define BSP_CFG_PLL3M (100) /* M-divider=100 */
#define BSP_CFG_PLL3K (0) /* Delta-Sigma=0 */
#define BSP_CFG_PLL3S (3) /* S-divider=3 */
#define BSP_CFG_PLL3 (BSP_CLOCKS_PLL3_STANDBY) /* PLL3 is standby state */
#define BSP_CFG_CLMA3_ENABLE (BSP_CLOCKS_CLMA3_ENABLE) /* CLMA3 Enabled */
#define BSP_CFG_CLMA3MASK (BSP_CLOCKS_CLMA3_ERROR_NOT_MASK) /* CLMA3 error not mask */
#define BSP_CFG_LCDCDIVSEL (BSP_CLOCKS_LCDCDIVSEL_DIV_4) /* LCDC Div /4 */
#define BSP_CFG_PLL2 (BSP_CLOCKS_PLL2_STANDBY) /* PLL2 is standby state */
#define BSP_CFG_CLMA2_ENABLE (BSP_CLOCKS_CLMA2_ENABLE) /* CLMA2 Enabled */
#define BSP_CFG_CLMA2MASK (BSP_CLOCKS_CLMA2_ERROR_NOT_MASK) /* CLMA2 error not mask */
#define BSP_CFG_PLL2SSCEN (BSP_CLOCKS_PLL2SSCEN_DISABLE) /* PLL2 SSC Disabled */
#define BSP_CFG_PLL2MFR (7) /* MMF: 111.7kHz */
#define BSP_CFG_PLL2MRR (1) /* MRR: 1 */
#define BSP_CFG_CLMA6_ENABLE (BSP_CLOCKS_CLMA6_ENABLE) /* CLMA6 Enabled */
#define BSP_CFG_CLMA6MASK (BSP_CLOCKS_CLMA6_ERROR_NOT_MASK) /* CLMA6 error not mask */
#define BSP_CFG_CLMASEL (BSP_CLOCKS_CLMASEL_LOCO) /* CLMA6 Alternative CLK: LOCO */
#define BSP_CFG_LOCO_ENABLE (BSP_CLOCKS_LOCO_ENABLE) /* LOCO Enabled */
#define BSP_CFG_CLMA5_ENABLE (BSP_CLOCKS_CLMA5_ENABLE) /* CLMA5 Enabled */
#define BSP_CFG_CLMA0_CMPL (1) /* CLMA0 CMPL 1 */
#define BSP_CFG_CLMA1_CMPL (1) /* CLMA1 CMPL 1 */
#define BSP_CFG_CLMA2_CMPL (1) /* CLMA2 CMPL 1 */
#define BSP_CFG_CLMA3_CMPL (1) /* CLMA3 CMPL 1 */
#define BSP_CFG_CLMA4_CMPL (1) /* CLMA4 CMPL 1 */
#define BSP_CFG_CLMA5_CMPL (1) /* CLMA5 CMPL 1 */
#define BSP_CFG_CLMA6_CMPL (1) /* CLMA6 CMPL 1 */
#define BSP_CFG_CLMA0_CMPH (1023) /* CLMA0 CMPH 1023 */
#define BSP_CFG_CLMA1_CMPH (1023) /* CLMA1 CMPH 1023 */
#define BSP_CFG_CLMA2_CMPH (1023) /* CLMA2 CMPH 1023 */
#define BSP_CFG_CLMA3_CMPH (1023) /* CLMA3 CMPH 1023 */
#define BSP_CFG_CLMA4_CMPH (1023) /* CLMA4 CMPH 1023 */
#define BSP_CFG_CLMA5_CMPH (1023) /* CLMA5 CMPH 1023 */
#define BSP_CFG_CLMA6_CMPH (1023) /* CLMA6 CMPH 1023 */
#endif /* BSP_CLOCK_CFG_H_ */
