/*
 * Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef BSP_MCU_DEVICE_PN_CFG_H_
#define BSP_MCU_DEVICE_PN_CFG_H_

#define BSP_MCU_FEATURE_SET (CONFIG_RENESAS_PN_FEATURE_SET)
#define BSP_ROM_SIZE_BYTES (CONFIG_RENESAS_PN_ROM_SIZE)
#define BSP_RAM_SIZE_BYTES (1916928)
#define BSP_DATA_FLASH_SIZE_BYTES (0)
#define BSP_NUMBER_OF_CORES (CONFIG_RENESAS_PN_NUMBER_OF_CORES)

#if (CONFIG_RENESAS_PN_PACKAGE_TYPE == 1)
#define BSP_PACKAGE_LFBGA
#define BSP_PACKAGE_PINS (224)
#elif (CONFIG_RENESAS_PN_PACKAGE_TYPE == 2)
#define BSP_PACKAGE_LFBGA
#define BSP_PACKAGE_PINS (289)
#elif (CONFIG_RENESAS_PN_PACKAGE_TYPE == 3)
#define BSP_PACKAGE_LFBGA
#define BSP_PACKAGE_PINS (303)
#endif

#endif /* BSP_MCU_DEVICE_PN_CFG_H_ */
