/*
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#ifndef R_CPSCU_POSMSK_H
#define R_CPSCU_POSMSK_H

/* =========================================================================================================================== */
/* ================                                          R_CPSCU                                          ================ */
/* =========================================================================================================================== */

/* ========================================================  SRAMSAR  ======================================================== */
#define R_CPSCU_SRAMSAR_SRAMWTSA_Pos        (8UL)          /*!< SRAMWTSA (Bit 8)                                      */
#define R_CPSCU_SRAMSAR_SRAMWTSA_Msk        (0x100UL)      /*!< SRAMWTSA (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_SRAMSAR_SRAMSA1_Pos         (1UL)          /*!< SRAMSA1 (Bit 1)                                       */
#define R_CPSCU_SRAMSAR_SRAMSA1_Msk         (0x2UL)        /*!< SRAMSA1 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_SRAMSAR_SRAMSA0_Pos         (0UL)          /*!< SRAMSA0 (Bit 0)                                       */
#define R_CPSCU_SRAMSAR_SRAMSA0_Msk         (0x1UL)        /*!< SRAMSA0 (Bitfield-Mask: 0x01)                         */
/* ========================================================  DTCSAR  ========================================================= */
#define R_CPSCU_DTCSAR_SADTC0_Pos           (0UL)          /*!< SADTC0 (Bit 0)                                        */
#define R_CPSCU_DTCSAR_SADTC0_Msk           (0x1UL)        /*!< SADTC0 (Bitfield-Mask: 0x01)                          */
/* ========================================================  DMACSAR  ======================================================== */
#define R_CPSCU_DMACSAR_DMASTSA0_Pos        (0UL)          /*!< DMASTSA0 (Bit 0)                                      */
#define R_CPSCU_DMACSAR_DMASTSA0_Msk        (0x1UL)        /*!< DMASTSA0 (Bitfield-Mask: 0x01)                        */
/* =======================================================  EXDMACSAR  ======================================================= */
#define R_CPSCU_EXDMACSAR_DMAXSTSA0_Pos     (0UL)          /*!< DMAXSTSA0 (Bit 0)                                     */
#define R_CPSCU_EXDMACSAR_DMAXSTSA0_Msk     (0x1UL)        /*!< DMAXSTSA0 (Bitfield-Mask: 0x01)                       */
/* ========================================================  ICUSARA  ======================================================== */
#define R_CPSCU_ICUSARA_SAIRQCR31_Pos       (31UL)         /*!< SAIRQCR31 (Bit 31)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR31_Msk       (0x80000000UL) /*!< SAIRQCR31 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR30_Pos       (30UL)         /*!< SAIRQCR30 (Bit 30)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR30_Msk       (0x40000000UL) /*!< SAIRQCR30 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR29_Pos       (29UL)         /*!< SAIRQCR29 (Bit 29)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR29_Msk       (0x20000000UL) /*!< SAIRQCR29 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR28_Pos       (28UL)         /*!< SAIRQCR28 (Bit 28)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR28_Msk       (0x10000000UL) /*!< SAIRQCR28 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR27_Pos       (27UL)         /*!< SAIRQCR27 (Bit 27)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR27_Msk       (0x8000000UL)  /*!< SAIRQCR27 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR26_Pos       (26UL)         /*!< SAIRQCR26 (Bit 26)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR26_Msk       (0x4000000UL)  /*!< SAIRQCR26 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR25_Pos       (25UL)         /*!< SAIRQCR25 (Bit 25)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR25_Msk       (0x2000000UL)  /*!< SAIRQCR25 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR24_Pos       (24UL)         /*!< SAIRQCR24 (Bit 24)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR24_Msk       (0x1000000UL)  /*!< SAIRQCR24 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR23_Pos       (23UL)         /*!< SAIRQCR23 (Bit 23)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR23_Msk       (0x800000UL)   /*!< SAIRQCR23 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR22_Pos       (22UL)         /*!< SAIRQCR22 (Bit 22)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR22_Msk       (0x400000UL)   /*!< SAIRQCR22 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR21_Pos       (21UL)         /*!< SAIRQCR21 (Bit 21)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR21_Msk       (0x200000UL)   /*!< SAIRQCR21 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR20_Pos       (20UL)         /*!< SAIRQCR20 (Bit 20)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR20_Msk       (0x100000UL)   /*!< SAIRQCR20 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR19_Pos       (19UL)         /*!< SAIRQCR19 (Bit 19)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR19_Msk       (0x80000UL)    /*!< SAIRQCR19 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR18_Pos       (18UL)         /*!< SAIRQCR18 (Bit 18)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR18_Msk       (0x40000UL)    /*!< SAIRQCR18 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR17_Pos       (17UL)         /*!< SAIRQCR17 (Bit 17)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR17_Msk       (0x20000UL)    /*!< SAIRQCR17 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR16_Pos       (16UL)         /*!< SAIRQCR16 (Bit 16)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR16_Msk       (0x10000UL)    /*!< SAIRQCR16 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR15_Pos       (15UL)         /*!< SAIRQCR15 (Bit 15)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR15_Msk       (0x8000UL)     /*!< SAIRQCR15 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR14_Pos       (14UL)         /*!< SAIRQCR14 (Bit 14)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR14_Msk       (0x4000UL)     /*!< SAIRQCR14 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR13_Pos       (13UL)         /*!< SAIRQCR13 (Bit 13)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR13_Msk       (0x2000UL)     /*!< SAIRQCR13 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR12_Pos       (12UL)         /*!< SAIRQCR12 (Bit 12)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR12_Msk       (0x1000UL)     /*!< SAIRQCR12 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR11_Pos       (11UL)         /*!< SAIRQCR11 (Bit 11)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR11_Msk       (0x800UL)      /*!< SAIRQCR11 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR10_Pos       (10UL)         /*!< SAIRQCR10 (Bit 10)                                    */
#define R_CPSCU_ICUSARA_SAIRQCR10_Msk       (0x400UL)      /*!< SAIRQCR10 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_ICUSARA_SAIRQCR9_Pos        (9UL)          /*!< SAIRQCR9 (Bit 9)                                      */
#define R_CPSCU_ICUSARA_SAIRQCR9_Msk        (0x200UL)      /*!< SAIRQCR9 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_ICUSARA_SAIRQCR8_Pos        (8UL)          /*!< SAIRQCR8 (Bit 8)                                      */
#define R_CPSCU_ICUSARA_SAIRQCR8_Msk        (0x100UL)      /*!< SAIRQCR8 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_ICUSARA_SAIRQCR7_Pos        (7UL)          /*!< SAIRQCR7 (Bit 7)                                      */
#define R_CPSCU_ICUSARA_SAIRQCR7_Msk        (0x80UL)       /*!< SAIRQCR7 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_ICUSARA_SAIRQCR6_Pos        (6UL)          /*!< SAIRQCR6 (Bit 6)                                      */
#define R_CPSCU_ICUSARA_SAIRQCR6_Msk        (0x40UL)       /*!< SAIRQCR6 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_ICUSARA_SAIRQCR5_Pos        (5UL)          /*!< SAIRQCR5 (Bit 5)                                      */
#define R_CPSCU_ICUSARA_SAIRQCR5_Msk        (0x20UL)       /*!< SAIRQCR5 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_ICUSARA_SAIRQCR4_Pos        (4UL)          /*!< SAIRQCR4 (Bit 4)                                      */
#define R_CPSCU_ICUSARA_SAIRQCR4_Msk        (0x10UL)       /*!< SAIRQCR4 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_ICUSARA_SAIRQCR3_Pos        (3UL)          /*!< SAIRQCR3 (Bit 3)                                      */
#define R_CPSCU_ICUSARA_SAIRQCR3_Msk        (0x8UL)        /*!< SAIRQCR3 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_ICUSARA_SAIRQCR2_Pos        (2UL)          /*!< SAIRQCR2 (Bit 2)                                      */
#define R_CPSCU_ICUSARA_SAIRQCR2_Msk        (0x4UL)        /*!< SAIRQCR2 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_ICUSARA_SAIRQCR1_Pos        (1UL)          /*!< SAIRQCR1 (Bit 1)                                      */
#define R_CPSCU_ICUSARA_SAIRQCR1_Msk        (0x2UL)        /*!< SAIRQCR1 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_ICUSARA_SAIRQCR0_Pos        (0UL)          /*!< SAIRQCR0 (Bit 0)                                      */
#define R_CPSCU_ICUSARA_SAIRQCR0_Msk        (0x1UL)        /*!< SAIRQCR0 (Bitfield-Mask: 0x01)                        */
/* ========================================================  ICUSARB  ======================================================== */
#define R_CPSCU_ICUSARB_SANMI0_Pos          (1UL)          /*!< SANMI0 (Bit 1)                                        */
#define R_CPSCU_ICUSARB_SANMI0_Msk          (0x2UL)        /*!< SANMI0 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICUSARB_SANMICR_Pos         (0UL)          /*!< SANMICR (Bit 0)                                       */
#define R_CPSCU_ICUSARB_SANMICR_Msk         (0x1UL)        /*!< SANMICR (Bitfield-Mask: 0x01)                         */
/* ========================================================  ICUSARC  ======================================================== */
#define R_CPSCU_ICUSARC_SACLPCR0_Pos        (1UL)          /*!< SACLPCR0 (Bit 1)                                      */
#define R_CPSCU_ICUSARC_SACLPCR0_Msk        (0x2UL)        /*!< SACLPCR0 (Bitfield-Mask: 0x01)                        */
/* ========================================================  ICUSARD  ======================================================== */
#define R_CPSCU_ICUSARD_SAMEWE_Pos          (12UL)         /*!< SAMEWE (Bit 12)                                       */
#define R_CPSCU_ICUSARD_SAMEWE_Msk          (0x1000UL)     /*!< SAMEWE (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICUSARD_SAMDWE_Pos          (11UL)         /*!< SAMDWE (Bit 11)                                       */
#define R_CPSCU_ICUSARD_SAMDWE_Msk          (0x800UL)      /*!< SAMDWE (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICUSARD_SAMCWE_Pos          (10UL)         /*!< SAMCWE (Bit 10)                                       */
#define R_CPSCU_ICUSARD_SAMCWE_Msk          (0x400UL)      /*!< SAMCWE (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICUSARD_SAMEEE_Pos          (9UL)          /*!< SAMEEE (Bit 9)                                        */
#define R_CPSCU_ICUSARD_SAMEEE_Msk          (0x200UL)      /*!< SAMEEE (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICUSARD_SAMCEE_Pos          (8UL)          /*!< SAMCEE (Bit 8)                                        */
#define R_CPSCU_ICUSARD_SAMCEE_Msk          (0x100UL)      /*!< SAMCEE (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICUSARD_SAHLDTO_Pos         (3UL)          /*!< SAHLDTO (Bit 3)                                       */
#define R_CPSCU_ICUSARD_SAHLDTO_Msk         (0x8UL)        /*!< SAHLDTO (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICUSARD_SACM_Pos            (2UL)          /*!< SACM (Bit 2)                                          */
#define R_CPSCU_ICUSARD_SACM_Msk            (0x4UL)        /*!< SACM (Bitfield-Mask: 0x01)                            */
#define R_CPSCU_ICUSARD_SALM_Pos            (1UL)          /*!< SALM (Bit 1)                                          */
#define R_CPSCU_ICUSARD_SALM_Msk            (0x2UL)        /*!< SALM (Bitfield-Mask: 0x01)                            */
#define R_CPSCU_ICUSARD_SADPFPU_Pos         (0UL)          /*!< SADPFPU (Bit 0)                                       */
#define R_CPSCU_ICUSARD_SADPFPU_Msk         (0x1UL)        /*!< SADPFPU (Bitfield-Mask: 0x01)                         */
/* =======================================================  ICU0SAR0  ======================================================== */
#define R_CPSCU_ICU0SAR0_SAIR31_Pos         (31UL)         /*!< SAIR31 (Bit 31)                                       */
#define R_CPSCU_ICU0SAR0_SAIR31_Msk         (0x80000000UL) /*!< SAIR31 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR30_Pos         (30UL)         /*!< SAIR30 (Bit 30)                                       */
#define R_CPSCU_ICU0SAR0_SAIR30_Msk         (0x40000000UL) /*!< SAIR30 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR29_Pos         (29UL)         /*!< SAIR29 (Bit 29)                                       */
#define R_CPSCU_ICU0SAR0_SAIR29_Msk         (0x20000000UL) /*!< SAIR29 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR28_Pos         (28UL)         /*!< SAIR28 (Bit 28)                                       */
#define R_CPSCU_ICU0SAR0_SAIR28_Msk         (0x10000000UL) /*!< SAIR28 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR27_Pos         (27UL)         /*!< SAIR27 (Bit 27)                                       */
#define R_CPSCU_ICU0SAR0_SAIR27_Msk         (0x8000000UL)  /*!< SAIR27 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR26_Pos         (26UL)         /*!< SAIR26 (Bit 26)                                       */
#define R_CPSCU_ICU0SAR0_SAIR26_Msk         (0x4000000UL)  /*!< SAIR26 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR25_Pos         (25UL)         /*!< SAIR25 (Bit 25)                                       */
#define R_CPSCU_ICU0SAR0_SAIR25_Msk         (0x2000000UL)  /*!< SAIR25 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR24_Pos         (24UL)         /*!< SAIR24 (Bit 24)                                       */
#define R_CPSCU_ICU0SAR0_SAIR24_Msk         (0x1000000UL)  /*!< SAIR24 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR23_Pos         (23UL)         /*!< SAIR23 (Bit 23)                                       */
#define R_CPSCU_ICU0SAR0_SAIR23_Msk         (0x800000UL)   /*!< SAIR23 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR22_Pos         (22UL)         /*!< SAIR22 (Bit 22)                                       */
#define R_CPSCU_ICU0SAR0_SAIR22_Msk         (0x400000UL)   /*!< SAIR22 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR21_Pos         (21UL)         /*!< SAIR21 (Bit 21)                                       */
#define R_CPSCU_ICU0SAR0_SAIR21_Msk         (0x200000UL)   /*!< SAIR21 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR20_Pos         (20UL)         /*!< SAIR20 (Bit 20)                                       */
#define R_CPSCU_ICU0SAR0_SAIR20_Msk         (0x100000UL)   /*!< SAIR20 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR19_Pos         (19UL)         /*!< SAIR19 (Bit 19)                                       */
#define R_CPSCU_ICU0SAR0_SAIR19_Msk         (0x80000UL)    /*!< SAIR19 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR18_Pos         (18UL)         /*!< SAIR18 (Bit 18)                                       */
#define R_CPSCU_ICU0SAR0_SAIR18_Msk         (0x40000UL)    /*!< SAIR18 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR17_Pos         (17UL)         /*!< SAIR17 (Bit 17)                                       */
#define R_CPSCU_ICU0SAR0_SAIR17_Msk         (0x20000UL)    /*!< SAIR17 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR16_Pos         (16UL)         /*!< SAIR16 (Bit 16)                                       */
#define R_CPSCU_ICU0SAR0_SAIR16_Msk         (0x10000UL)    /*!< SAIR16 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR15_Pos         (15UL)         /*!< SAIR15 (Bit 15)                                       */
#define R_CPSCU_ICU0SAR0_SAIR15_Msk         (0x8000UL)     /*!< SAIR15 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR14_Pos         (14UL)         /*!< SAIR14 (Bit 14)                                       */
#define R_CPSCU_ICU0SAR0_SAIR14_Msk         (0x4000UL)     /*!< SAIR14 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR13_Pos         (13UL)         /*!< SAIR13 (Bit 13)                                       */
#define R_CPSCU_ICU0SAR0_SAIR13_Msk         (0x2000UL)     /*!< SAIR13 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR12_Pos         (12UL)         /*!< SAIR12 (Bit 12)                                       */
#define R_CPSCU_ICU0SAR0_SAIR12_Msk         (0x1000UL)     /*!< SAIR12 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR11_Pos         (11UL)         /*!< SAIR11 (Bit 11)                                       */
#define R_CPSCU_ICU0SAR0_SAIR11_Msk         (0x800UL)      /*!< SAIR11 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR10_Pos         (10UL)         /*!< SAIR10 (Bit 10)                                       */
#define R_CPSCU_ICU0SAR0_SAIR10_Msk         (0x400UL)      /*!< SAIR10 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR0_SAIR9_Pos          (9UL)          /*!< SAIR9 (Bit 9)                                         */
#define R_CPSCU_ICU0SAR0_SAIR9_Msk          (0x200UL)      /*!< SAIR9 (Bitfield-Mask: 0x01)                           */
#define R_CPSCU_ICU0SAR0_SAIR8_Pos          (8UL)          /*!< SAIR8 (Bit 8)                                         */
#define R_CPSCU_ICU0SAR0_SAIR8_Msk          (0x100UL)      /*!< SAIR8 (Bitfield-Mask: 0x01)                           */
#define R_CPSCU_ICU0SAR0_SAIR7_Pos          (7UL)          /*!< SAIR7 (Bit 7)                                         */
#define R_CPSCU_ICU0SAR0_SAIR7_Msk          (0x80UL)       /*!< SAIR7 (Bitfield-Mask: 0x01)                           */
#define R_CPSCU_ICU0SAR0_SAIR6_Pos          (6UL)          /*!< SAIR6 (Bit 6)                                         */
#define R_CPSCU_ICU0SAR0_SAIR6_Msk          (0x40UL)       /*!< SAIR6 (Bitfield-Mask: 0x01)                           */
#define R_CPSCU_ICU0SAR0_SAIR5_Pos          (5UL)          /*!< SAIR5 (Bit 5)                                         */
#define R_CPSCU_ICU0SAR0_SAIR5_Msk          (0x20UL)       /*!< SAIR5 (Bitfield-Mask: 0x01)                           */
#define R_CPSCU_ICU0SAR0_SAIR4_Pos          (4UL)          /*!< SAIR4 (Bit 4)                                         */
#define R_CPSCU_ICU0SAR0_SAIR4_Msk          (0x10UL)       /*!< SAIR4 (Bitfield-Mask: 0x01)                           */
#define R_CPSCU_ICU0SAR0_SAIR3_Pos          (3UL)          /*!< SAIR3 (Bit 3)                                         */
#define R_CPSCU_ICU0SAR0_SAIR3_Msk          (0x8UL)        /*!< SAIR3 (Bitfield-Mask: 0x01)                           */
#define R_CPSCU_ICU0SAR0_SAIR2_Pos          (2UL)          /*!< SAIR2 (Bit 2)                                         */
#define R_CPSCU_ICU0SAR0_SAIR2_Msk          (0x4UL)        /*!< SAIR2 (Bitfield-Mask: 0x01)                           */
#define R_CPSCU_ICU0SAR0_SAIR1_Pos          (1UL)          /*!< SAIR1 (Bit 1)                                         */
#define R_CPSCU_ICU0SAR0_SAIR1_Msk          (0x2UL)        /*!< SAIR1 (Bitfield-Mask: 0x01)                           */
#define R_CPSCU_ICU0SAR0_SAIR0_Pos          (0UL)          /*!< SAIR0 (Bit 0)                                         */
#define R_CPSCU_ICU0SAR0_SAIR0_Msk          (0x1UL)        /*!< SAIR0 (Bitfield-Mask: 0x01)                           */
/* =======================================================  ICU0SAR1  ======================================================== */
#define R_CPSCU_ICU0SAR1_SAIR63_Pos         (31UL)         /*!< SAIR63 (Bit 31)                                       */
#define R_CPSCU_ICU0SAR1_SAIR63_Msk         (0x80000000UL) /*!< SAIR63 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR62_Pos         (30UL)         /*!< SAIR62 (Bit 30)                                       */
#define R_CPSCU_ICU0SAR1_SAIR62_Msk         (0x40000000UL) /*!< SAIR62 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR61_Pos         (29UL)         /*!< SAIR61 (Bit 29)                                       */
#define R_CPSCU_ICU0SAR1_SAIR61_Msk         (0x20000000UL) /*!< SAIR61 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR60_Pos         (28UL)         /*!< SAIR60 (Bit 28)                                       */
#define R_CPSCU_ICU0SAR1_SAIR60_Msk         (0x10000000UL) /*!< SAIR60 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR59_Pos         (27UL)         /*!< SAIR59 (Bit 27)                                       */
#define R_CPSCU_ICU0SAR1_SAIR59_Msk         (0x8000000UL)  /*!< SAIR59 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR58_Pos         (26UL)         /*!< SAIR58 (Bit 26)                                       */
#define R_CPSCU_ICU0SAR1_SAIR58_Msk         (0x4000000UL)  /*!< SAIR58 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR57_Pos         (25UL)         /*!< SAIR57 (Bit 25)                                       */
#define R_CPSCU_ICU0SAR1_SAIR57_Msk         (0x2000000UL)  /*!< SAIR57 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR56_Pos         (24UL)         /*!< SAIR56 (Bit 24)                                       */
#define R_CPSCU_ICU0SAR1_SAIR56_Msk         (0x1000000UL)  /*!< SAIR56 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR55_Pos         (23UL)         /*!< SAIR55 (Bit 23)                                       */
#define R_CPSCU_ICU0SAR1_SAIR55_Msk         (0x800000UL)   /*!< SAIR55 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR54_Pos         (22UL)         /*!< SAIR54 (Bit 22)                                       */
#define R_CPSCU_ICU0SAR1_SAIR54_Msk         (0x400000UL)   /*!< SAIR54 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR53_Pos         (21UL)         /*!< SAIR53 (Bit 21)                                       */
#define R_CPSCU_ICU0SAR1_SAIR53_Msk         (0x200000UL)   /*!< SAIR53 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR52_Pos         (20UL)         /*!< SAIR52 (Bit 20)                                       */
#define R_CPSCU_ICU0SAR1_SAIR52_Msk         (0x100000UL)   /*!< SAIR52 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR51_Pos         (19UL)         /*!< SAIR51 (Bit 19)                                       */
#define R_CPSCU_ICU0SAR1_SAIR51_Msk         (0x80000UL)    /*!< SAIR51 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR50_Pos         (18UL)         /*!< SAIR50 (Bit 18)                                       */
#define R_CPSCU_ICU0SAR1_SAIR50_Msk         (0x40000UL)    /*!< SAIR50 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR49_Pos         (17UL)         /*!< SAIR49 (Bit 17)                                       */
#define R_CPSCU_ICU0SAR1_SAIR49_Msk         (0x20000UL)    /*!< SAIR49 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR48_Pos         (16UL)         /*!< SAIR48 (Bit 16)                                       */
#define R_CPSCU_ICU0SAR1_SAIR48_Msk         (0x10000UL)    /*!< SAIR48 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR47_Pos         (15UL)         /*!< SAIR47 (Bit 15)                                       */
#define R_CPSCU_ICU0SAR1_SAIR47_Msk         (0x8000UL)     /*!< SAIR47 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR46_Pos         (14UL)         /*!< SAIR46 (Bit 14)                                       */
#define R_CPSCU_ICU0SAR1_SAIR46_Msk         (0x4000UL)     /*!< SAIR46 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR45_Pos         (13UL)         /*!< SAIR45 (Bit 13)                                       */
#define R_CPSCU_ICU0SAR1_SAIR45_Msk         (0x2000UL)     /*!< SAIR45 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR44_Pos         (12UL)         /*!< SAIR44 (Bit 12)                                       */
#define R_CPSCU_ICU0SAR1_SAIR44_Msk         (0x1000UL)     /*!< SAIR44 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR43_Pos         (11UL)         /*!< SAIR43 (Bit 11)                                       */
#define R_CPSCU_ICU0SAR1_SAIR43_Msk         (0x800UL)      /*!< SAIR43 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR42_Pos         (10UL)         /*!< SAIR42 (Bit 10)                                       */
#define R_CPSCU_ICU0SAR1_SAIR42_Msk         (0x400UL)      /*!< SAIR42 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR41_Pos         (9UL)          /*!< SAIR41 (Bit 9)                                        */
#define R_CPSCU_ICU0SAR1_SAIR41_Msk         (0x200UL)      /*!< SAIR41 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR40_Pos         (8UL)          /*!< SAIR40 (Bit 8)                                        */
#define R_CPSCU_ICU0SAR1_SAIR40_Msk         (0x100UL)      /*!< SAIR40 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR39_Pos         (7UL)          /*!< SAIR39 (Bit 7)                                        */
#define R_CPSCU_ICU0SAR1_SAIR39_Msk         (0x80UL)       /*!< SAIR39 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR38_Pos         (6UL)          /*!< SAIR38 (Bit 6)                                        */
#define R_CPSCU_ICU0SAR1_SAIR38_Msk         (0x40UL)       /*!< SAIR38 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR37_Pos         (5UL)          /*!< SAIR37 (Bit 5)                                        */
#define R_CPSCU_ICU0SAR1_SAIR37_Msk         (0x20UL)       /*!< SAIR37 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR36_Pos         (4UL)          /*!< SAIR36 (Bit 4)                                        */
#define R_CPSCU_ICU0SAR1_SAIR36_Msk         (0x10UL)       /*!< SAIR36 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR35_Pos         (3UL)          /*!< SAIR35 (Bit 3)                                        */
#define R_CPSCU_ICU0SAR1_SAIR35_Msk         (0x8UL)        /*!< SAIR35 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR34_Pos         (2UL)          /*!< SAIR34 (Bit 2)                                        */
#define R_CPSCU_ICU0SAR1_SAIR34_Msk         (0x4UL)        /*!< SAIR34 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR33_Pos         (1UL)          /*!< SAIR33 (Bit 1)                                        */
#define R_CPSCU_ICU0SAR1_SAIR33_Msk         (0x2UL)        /*!< SAIR33 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR1_SAIR32_Pos         (0UL)          /*!< SAIR32 (Bit 0)                                        */
#define R_CPSCU_ICU0SAR1_SAIR32_Msk         (0x1UL)        /*!< SAIR32 (Bitfield-Mask: 0x01)                          */
/* =======================================================  ICU0SAR2  ======================================================== */
#define R_CPSCU_ICU0SAR2_SAIR95_Pos         (31UL)         /*!< SAIR95 (Bit 31)                                       */
#define R_CPSCU_ICU0SAR2_SAIR95_Msk         (0x80000000UL) /*!< SAIR95 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR94_Pos         (30UL)         /*!< SAIR94 (Bit 30)                                       */
#define R_CPSCU_ICU0SAR2_SAIR94_Msk         (0x40000000UL) /*!< SAIR94 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR93_Pos         (29UL)         /*!< SAIR93 (Bit 29)                                       */
#define R_CPSCU_ICU0SAR2_SAIR93_Msk         (0x20000000UL) /*!< SAIR93 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR92_Pos         (28UL)         /*!< SAIR92 (Bit 28)                                       */
#define R_CPSCU_ICU0SAR2_SAIR92_Msk         (0x10000000UL) /*!< SAIR92 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR91_Pos         (27UL)         /*!< SAIR91 (Bit 27)                                       */
#define R_CPSCU_ICU0SAR2_SAIR91_Msk         (0x8000000UL)  /*!< SAIR91 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR90_Pos         (26UL)         /*!< SAIR90 (Bit 26)                                       */
#define R_CPSCU_ICU0SAR2_SAIR90_Msk         (0x4000000UL)  /*!< SAIR90 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR89_Pos         (25UL)         /*!< SAIR89 (Bit 25)                                       */
#define R_CPSCU_ICU0SAR2_SAIR89_Msk         (0x2000000UL)  /*!< SAIR89 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR88_Pos         (24UL)         /*!< SAIR88 (Bit 24)                                       */
#define R_CPSCU_ICU0SAR2_SAIR88_Msk         (0x1000000UL)  /*!< SAIR88 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR87_Pos         (23UL)         /*!< SAIR87 (Bit 23)                                       */
#define R_CPSCU_ICU0SAR2_SAIR87_Msk         (0x800000UL)   /*!< SAIR87 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR86_Pos         (22UL)         /*!< SAIR86 (Bit 22)                                       */
#define R_CPSCU_ICU0SAR2_SAIR86_Msk         (0x400000UL)   /*!< SAIR86 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR85_Pos         (21UL)         /*!< SAIR85 (Bit 21)                                       */
#define R_CPSCU_ICU0SAR2_SAIR85_Msk         (0x200000UL)   /*!< SAIR85 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR84_Pos         (20UL)         /*!< SAIR84 (Bit 20)                                       */
#define R_CPSCU_ICU0SAR2_SAIR84_Msk         (0x100000UL)   /*!< SAIR84 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR83_Pos         (19UL)         /*!< SAIR83 (Bit 19)                                       */
#define R_CPSCU_ICU0SAR2_SAIR83_Msk         (0x80000UL)    /*!< SAIR83 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR82_Pos         (18UL)         /*!< SAIR82 (Bit 18)                                       */
#define R_CPSCU_ICU0SAR2_SAIR82_Msk         (0x40000UL)    /*!< SAIR82 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR81_Pos         (17UL)         /*!< SAIR81 (Bit 17)                                       */
#define R_CPSCU_ICU0SAR2_SAIR81_Msk         (0x20000UL)    /*!< SAIR81 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR80_Pos         (16UL)         /*!< SAIR80 (Bit 16)                                       */
#define R_CPSCU_ICU0SAR2_SAIR80_Msk         (0x10000UL)    /*!< SAIR80 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR79_Pos         (15UL)         /*!< SAIR79 (Bit 15)                                       */
#define R_CPSCU_ICU0SAR2_SAIR79_Msk         (0x8000UL)     /*!< SAIR79 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR78_Pos         (14UL)         /*!< SAIR78 (Bit 14)                                       */
#define R_CPSCU_ICU0SAR2_SAIR78_Msk         (0x4000UL)     /*!< SAIR78 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR77_Pos         (13UL)         /*!< SAIR77 (Bit 13)                                       */
#define R_CPSCU_ICU0SAR2_SAIR77_Msk         (0x2000UL)     /*!< SAIR77 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR76_Pos         (12UL)         /*!< SAIR76 (Bit 12)                                       */
#define R_CPSCU_ICU0SAR2_SAIR76_Msk         (0x1000UL)     /*!< SAIR76 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR75_Pos         (11UL)         /*!< SAIR75 (Bit 11)                                       */
#define R_CPSCU_ICU0SAR2_SAIR75_Msk         (0x800UL)      /*!< SAIR75 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR74_Pos         (10UL)         /*!< SAIR74 (Bit 10)                                       */
#define R_CPSCU_ICU0SAR2_SAIR74_Msk         (0x400UL)      /*!< SAIR74 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR73_Pos         (9UL)          /*!< SAIR73 (Bit 9)                                        */
#define R_CPSCU_ICU0SAR2_SAIR73_Msk         (0x200UL)      /*!< SAIR73 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR72_Pos         (8UL)          /*!< SAIR72 (Bit 8)                                        */
#define R_CPSCU_ICU0SAR2_SAIR72_Msk         (0x100UL)      /*!< SAIR72 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR71_Pos         (7UL)          /*!< SAIR71 (Bit 7)                                        */
#define R_CPSCU_ICU0SAR2_SAIR71_Msk         (0x80UL)       /*!< SAIR71 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR70_Pos         (6UL)          /*!< SAIR70 (Bit 6)                                        */
#define R_CPSCU_ICU0SAR2_SAIR70_Msk         (0x40UL)       /*!< SAIR70 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR69_Pos         (5UL)          /*!< SAIR69 (Bit 5)                                        */
#define R_CPSCU_ICU0SAR2_SAIR69_Msk         (0x20UL)       /*!< SAIR69 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR68_Pos         (4UL)          /*!< SAIR68 (Bit 4)                                        */
#define R_CPSCU_ICU0SAR2_SAIR68_Msk         (0x10UL)       /*!< SAIR68 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR67_Pos         (3UL)          /*!< SAIR67 (Bit 3)                                        */
#define R_CPSCU_ICU0SAR2_SAIR67_Msk         (0x8UL)        /*!< SAIR67 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR66_Pos         (2UL)          /*!< SAIR66 (Bit 2)                                        */
#define R_CPSCU_ICU0SAR2_SAIR66_Msk         (0x4UL)        /*!< SAIR66 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR65_Pos         (1UL)          /*!< SAIR65 (Bit 1)                                        */
#define R_CPSCU_ICU0SAR2_SAIR65_Msk         (0x2UL)        /*!< SAIR65 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR2_SAIR64_Pos         (0UL)          /*!< SAIR64 (Bit 0)                                        */
#define R_CPSCU_ICU0SAR2_SAIR64_Msk         (0x1UL)        /*!< SAIR64 (Bitfield-Mask: 0x01)                          */
/* =======================================================  ICU0SAR3  ======================================================== */
#define R_CPSCU_ICU0SAR3_SAIR127_Pos        (31UL)         /*!< SAIR127 (Bit 31)                                      */
#define R_CPSCU_ICU0SAR3_SAIR127_Msk        (0x80000000UL) /*!< SAIR127 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR126_Pos        (30UL)         /*!< SAIR126 (Bit 30)                                      */
#define R_CPSCU_ICU0SAR3_SAIR126_Msk        (0x40000000UL) /*!< SAIR126 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR125_Pos        (29UL)         /*!< SAIR125 (Bit 29)                                      */
#define R_CPSCU_ICU0SAR3_SAIR125_Msk        (0x20000000UL) /*!< SAIR125 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR124_Pos        (28UL)         /*!< SAIR124 (Bit 28)                                      */
#define R_CPSCU_ICU0SAR3_SAIR124_Msk        (0x10000000UL) /*!< SAIR124 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR123_Pos        (27UL)         /*!< SAIR123 (Bit 27)                                      */
#define R_CPSCU_ICU0SAR3_SAIR123_Msk        (0x8000000UL)  /*!< SAIR123 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR122_Pos        (26UL)         /*!< SAIR122 (Bit 26)                                      */
#define R_CPSCU_ICU0SAR3_SAIR122_Msk        (0x4000000UL)  /*!< SAIR122 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR121_Pos        (25UL)         /*!< SAIR121 (Bit 25)                                      */
#define R_CPSCU_ICU0SAR3_SAIR121_Msk        (0x2000000UL)  /*!< SAIR121 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR120_Pos        (24UL)         /*!< SAIR120 (Bit 24)                                      */
#define R_CPSCU_ICU0SAR3_SAIR120_Msk        (0x1000000UL)  /*!< SAIR120 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR119_Pos        (23UL)         /*!< SAIR119 (Bit 23)                                      */
#define R_CPSCU_ICU0SAR3_SAIR119_Msk        (0x800000UL)   /*!< SAIR119 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR118_Pos        (22UL)         /*!< SAIR118 (Bit 22)                                      */
#define R_CPSCU_ICU0SAR3_SAIR118_Msk        (0x400000UL)   /*!< SAIR118 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR117_Pos        (21UL)         /*!< SAIR117 (Bit 21)                                      */
#define R_CPSCU_ICU0SAR3_SAIR117_Msk        (0x200000UL)   /*!< SAIR117 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR116_Pos        (20UL)         /*!< SAIR116 (Bit 20)                                      */
#define R_CPSCU_ICU0SAR3_SAIR116_Msk        (0x100000UL)   /*!< SAIR116 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR115_Pos        (19UL)         /*!< SAIR115 (Bit 19)                                      */
#define R_CPSCU_ICU0SAR3_SAIR115_Msk        (0x80000UL)    /*!< SAIR115 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR114_Pos        (18UL)         /*!< SAIR114 (Bit 18)                                      */
#define R_CPSCU_ICU0SAR3_SAIR114_Msk        (0x40000UL)    /*!< SAIR114 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR113_Pos        (17UL)         /*!< SAIR113 (Bit 17)                                      */
#define R_CPSCU_ICU0SAR3_SAIR113_Msk        (0x20000UL)    /*!< SAIR113 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR112_Pos        (16UL)         /*!< SAIR112 (Bit 16)                                      */
#define R_CPSCU_ICU0SAR3_SAIR112_Msk        (0x10000UL)    /*!< SAIR112 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR111_Pos        (15UL)         /*!< SAIR111 (Bit 15)                                      */
#define R_CPSCU_ICU0SAR3_SAIR111_Msk        (0x8000UL)     /*!< SAIR111 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR110_Pos        (14UL)         /*!< SAIR110 (Bit 14)                                      */
#define R_CPSCU_ICU0SAR3_SAIR110_Msk        (0x4000UL)     /*!< SAIR110 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR109_Pos        (13UL)         /*!< SAIR109 (Bit 13)                                      */
#define R_CPSCU_ICU0SAR3_SAIR109_Msk        (0x2000UL)     /*!< SAIR109 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR108_Pos        (12UL)         /*!< SAIR108 (Bit 12)                                      */
#define R_CPSCU_ICU0SAR3_SAIR108_Msk        (0x1000UL)     /*!< SAIR108 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR107_Pos        (11UL)         /*!< SAIR107 (Bit 11)                                      */
#define R_CPSCU_ICU0SAR3_SAIR107_Msk        (0x800UL)      /*!< SAIR107 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR106_Pos        (10UL)         /*!< SAIR106 (Bit 10)                                      */
#define R_CPSCU_ICU0SAR3_SAIR106_Msk        (0x400UL)      /*!< SAIR106 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR105_Pos        (9UL)          /*!< SAIR105 (Bit 9)                                       */
#define R_CPSCU_ICU0SAR3_SAIR105_Msk        (0x200UL)      /*!< SAIR105 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR104_Pos        (8UL)          /*!< SAIR104 (Bit 8)                                       */
#define R_CPSCU_ICU0SAR3_SAIR104_Msk        (0x100UL)      /*!< SAIR104 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR103_Pos        (7UL)          /*!< SAIR103 (Bit 7)                                       */
#define R_CPSCU_ICU0SAR3_SAIR103_Msk        (0x80UL)       /*!< SAIR103 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR102_Pos        (6UL)          /*!< SAIR102 (Bit 6)                                       */
#define R_CPSCU_ICU0SAR3_SAIR102_Msk        (0x40UL)       /*!< SAIR102 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR101_Pos        (5UL)          /*!< SAIR101 (Bit 5)                                       */
#define R_CPSCU_ICU0SAR3_SAIR101_Msk        (0x20UL)       /*!< SAIR101 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR100_Pos        (4UL)          /*!< SAIR100 (Bit 4)                                       */
#define R_CPSCU_ICU0SAR3_SAIR100_Msk        (0x10UL)       /*!< SAIR100 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR3_SAIR99_Pos         (3UL)          /*!< SAIR99 (Bit 3)                                        */
#define R_CPSCU_ICU0SAR3_SAIR99_Msk         (0x8UL)        /*!< SAIR99 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR3_SAIR98_Pos         (2UL)          /*!< SAIR98 (Bit 2)                                        */
#define R_CPSCU_ICU0SAR3_SAIR98_Msk         (0x4UL)        /*!< SAIR98 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR3_SAIR97_Pos         (1UL)          /*!< SAIR97 (Bit 1)                                        */
#define R_CPSCU_ICU0SAR3_SAIR97_Msk         (0x2UL)        /*!< SAIR97 (Bitfield-Mask: 0x01)                          */
#define R_CPSCU_ICU0SAR3_SAIR96_Pos         (0UL)          /*!< SAIR96 (Bit 0)                                        */
#define R_CPSCU_ICU0SAR3_SAIR96_Msk         (0x1UL)        /*!< SAIR96 (Bitfield-Mask: 0x01)                          */
/* =======================================================  ICU0SAR4  ======================================================== */
#define R_CPSCU_ICU0SAR4_SAIR159_Pos        (31UL)         /*!< SAIR159 (Bit 31)                                      */
#define R_CPSCU_ICU0SAR4_SAIR159_Msk        (0x80000000UL) /*!< SAIR159 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR158_Pos        (30UL)         /*!< SAIR158 (Bit 30)                                      */
#define R_CPSCU_ICU0SAR4_SAIR158_Msk        (0x40000000UL) /*!< SAIR158 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR157_Pos        (29UL)         /*!< SAIR157 (Bit 29)                                      */
#define R_CPSCU_ICU0SAR4_SAIR157_Msk        (0x20000000UL) /*!< SAIR157 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR156_Pos        (28UL)         /*!< SAIR156 (Bit 28)                                      */
#define R_CPSCU_ICU0SAR4_SAIR156_Msk        (0x10000000UL) /*!< SAIR156 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR155_Pos        (27UL)         /*!< SAIR155 (Bit 27)                                      */
#define R_CPSCU_ICU0SAR4_SAIR155_Msk        (0x8000000UL)  /*!< SAIR155 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR154_Pos        (26UL)         /*!< SAIR154 (Bit 26)                                      */
#define R_CPSCU_ICU0SAR4_SAIR154_Msk        (0x4000000UL)  /*!< SAIR154 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR153_Pos        (25UL)         /*!< SAIR153 (Bit 25)                                      */
#define R_CPSCU_ICU0SAR4_SAIR153_Msk        (0x2000000UL)  /*!< SAIR153 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR152_Pos        (24UL)         /*!< SAIR152 (Bit 24)                                      */
#define R_CPSCU_ICU0SAR4_SAIR152_Msk        (0x1000000UL)  /*!< SAIR152 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR151_Pos        (23UL)         /*!< SAIR151 (Bit 23)                                      */
#define R_CPSCU_ICU0SAR4_SAIR151_Msk        (0x800000UL)   /*!< SAIR151 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR150_Pos        (22UL)         /*!< SAIR150 (Bit 22)                                      */
#define R_CPSCU_ICU0SAR4_SAIR150_Msk        (0x400000UL)   /*!< SAIR150 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR149_Pos        (21UL)         /*!< SAIR149 (Bit 21)                                      */
#define R_CPSCU_ICU0SAR4_SAIR149_Msk        (0x200000UL)   /*!< SAIR149 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR148_Pos        (20UL)         /*!< SAIR148 (Bit 20)                                      */
#define R_CPSCU_ICU0SAR4_SAIR148_Msk        (0x100000UL)   /*!< SAIR148 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR147_Pos        (19UL)         /*!< SAIR147 (Bit 19)                                      */
#define R_CPSCU_ICU0SAR4_SAIR147_Msk        (0x80000UL)    /*!< SAIR147 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR146_Pos        (18UL)         /*!< SAIR146 (Bit 18)                                      */
#define R_CPSCU_ICU0SAR4_SAIR146_Msk        (0x40000UL)    /*!< SAIR146 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR145_Pos        (17UL)         /*!< SAIR145 (Bit 17)                                      */
#define R_CPSCU_ICU0SAR4_SAIR145_Msk        (0x20000UL)    /*!< SAIR145 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR144_Pos        (16UL)         /*!< SAIR144 (Bit 16)                                      */
#define R_CPSCU_ICU0SAR4_SAIR144_Msk        (0x10000UL)    /*!< SAIR144 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR143_Pos        (15UL)         /*!< SAIR143 (Bit 15)                                      */
#define R_CPSCU_ICU0SAR4_SAIR143_Msk        (0x8000UL)     /*!< SAIR143 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR142_Pos        (14UL)         /*!< SAIR142 (Bit 14)                                      */
#define R_CPSCU_ICU0SAR4_SAIR142_Msk        (0x4000UL)     /*!< SAIR142 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR141_Pos        (13UL)         /*!< SAIR141 (Bit 13)                                      */
#define R_CPSCU_ICU0SAR4_SAIR141_Msk        (0x2000UL)     /*!< SAIR141 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR140_Pos        (12UL)         /*!< SAIR140 (Bit 12)                                      */
#define R_CPSCU_ICU0SAR4_SAIR140_Msk        (0x1000UL)     /*!< SAIR140 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR139_Pos        (11UL)         /*!< SAIR139 (Bit 11)                                      */
#define R_CPSCU_ICU0SAR4_SAIR139_Msk        (0x800UL)      /*!< SAIR139 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR138_Pos        (10UL)         /*!< SAIR138 (Bit 10)                                      */
#define R_CPSCU_ICU0SAR4_SAIR138_Msk        (0x400UL)      /*!< SAIR138 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR137_Pos        (9UL)          /*!< SAIR137 (Bit 9)                                       */
#define R_CPSCU_ICU0SAR4_SAIR137_Msk        (0x200UL)      /*!< SAIR137 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR136_Pos        (8UL)          /*!< SAIR136 (Bit 8)                                       */
#define R_CPSCU_ICU0SAR4_SAIR136_Msk        (0x100UL)      /*!< SAIR136 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR135_Pos        (7UL)          /*!< SAIR135 (Bit 7)                                       */
#define R_CPSCU_ICU0SAR4_SAIR135_Msk        (0x80UL)       /*!< SAIR135 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR134_Pos        (6UL)          /*!< SAIR134 (Bit 6)                                       */
#define R_CPSCU_ICU0SAR4_SAIR134_Msk        (0x40UL)       /*!< SAIR134 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR133_Pos        (5UL)          /*!< SAIR133 (Bit 5)                                       */
#define R_CPSCU_ICU0SAR4_SAIR133_Msk        (0x20UL)       /*!< SAIR133 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR132_Pos        (4UL)          /*!< SAIR132 (Bit 4)                                       */
#define R_CPSCU_ICU0SAR4_SAIR132_Msk        (0x10UL)       /*!< SAIR132 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR131_Pos        (3UL)          /*!< SAIR131 (Bit 3)                                       */
#define R_CPSCU_ICU0SAR4_SAIR131_Msk        (0x8UL)        /*!< SAIR131 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR130_Pos        (2UL)          /*!< SAIR130 (Bit 2)                                       */
#define R_CPSCU_ICU0SAR4_SAIR130_Msk        (0x4UL)        /*!< SAIR130 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR129_Pos        (1UL)          /*!< SAIR129 (Bit 1)                                       */
#define R_CPSCU_ICU0SAR4_SAIR129_Msk        (0x2UL)        /*!< SAIR129 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR4_SAIR128_Pos        (0UL)          /*!< SAIR128 (Bit 0)                                       */
#define R_CPSCU_ICU0SAR4_SAIR128_Msk        (0x1UL)        /*!< SAIR128 (Bitfield-Mask: 0x01)                         */
/* =======================================================  ICU0SAR5  ======================================================== */
#define R_CPSCU_ICU0SAR5_SAIR191_Pos        (31UL)         /*!< SAIR191 (Bit 31)                                      */
#define R_CPSCU_ICU0SAR5_SAIR191_Msk        (0x80000000UL) /*!< SAIR191 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR190_Pos        (30UL)         /*!< SAIR190 (Bit 30)                                      */
#define R_CPSCU_ICU0SAR5_SAIR190_Msk        (0x40000000UL) /*!< SAIR190 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR189_Pos        (29UL)         /*!< SAIR189 (Bit 29)                                      */
#define R_CPSCU_ICU0SAR5_SAIR189_Msk        (0x20000000UL) /*!< SAIR189 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR188_Pos        (28UL)         /*!< SAIR188 (Bit 28)                                      */
#define R_CPSCU_ICU0SAR5_SAIR188_Msk        (0x10000000UL) /*!< SAIR188 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR187_Pos        (27UL)         /*!< SAIR187 (Bit 27)                                      */
#define R_CPSCU_ICU0SAR5_SAIR187_Msk        (0x8000000UL)  /*!< SAIR187 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR186_Pos        (26UL)         /*!< SAIR186 (Bit 26)                                      */
#define R_CPSCU_ICU0SAR5_SAIR186_Msk        (0x4000000UL)  /*!< SAIR186 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR185_Pos        (25UL)         /*!< SAIR185 (Bit 25)                                      */
#define R_CPSCU_ICU0SAR5_SAIR185_Msk        (0x2000000UL)  /*!< SAIR185 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR184_Pos        (24UL)         /*!< SAIR184 (Bit 24)                                      */
#define R_CPSCU_ICU0SAR5_SAIR184_Msk        (0x1000000UL)  /*!< SAIR184 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR183_Pos        (23UL)         /*!< SAIR183 (Bit 23)                                      */
#define R_CPSCU_ICU0SAR5_SAIR183_Msk        (0x800000UL)   /*!< SAIR183 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR182_Pos        (22UL)         /*!< SAIR182 (Bit 22)                                      */
#define R_CPSCU_ICU0SAR5_SAIR182_Msk        (0x400000UL)   /*!< SAIR182 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR181_Pos        (21UL)         /*!< SAIR181 (Bit 21)                                      */
#define R_CPSCU_ICU0SAR5_SAIR181_Msk        (0x200000UL)   /*!< SAIR181 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR180_Pos        (20UL)         /*!< SAIR180 (Bit 20)                                      */
#define R_CPSCU_ICU0SAR5_SAIR180_Msk        (0x100000UL)   /*!< SAIR180 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR179_Pos        (19UL)         /*!< SAIR179 (Bit 19)                                      */
#define R_CPSCU_ICU0SAR5_SAIR179_Msk        (0x80000UL)    /*!< SAIR179 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR178_Pos        (18UL)         /*!< SAIR178 (Bit 18)                                      */
#define R_CPSCU_ICU0SAR5_SAIR178_Msk        (0x40000UL)    /*!< SAIR178 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR177_Pos        (17UL)         /*!< SAIR177 (Bit 17)                                      */
#define R_CPSCU_ICU0SAR5_SAIR177_Msk        (0x20000UL)    /*!< SAIR177 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR176_Pos        (16UL)         /*!< SAIR176 (Bit 16)                                      */
#define R_CPSCU_ICU0SAR5_SAIR176_Msk        (0x10000UL)    /*!< SAIR176 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR175_Pos        (15UL)         /*!< SAIR175 (Bit 15)                                      */
#define R_CPSCU_ICU0SAR5_SAIR175_Msk        (0x8000UL)     /*!< SAIR175 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR174_Pos        (14UL)         /*!< SAIR174 (Bit 14)                                      */
#define R_CPSCU_ICU0SAR5_SAIR174_Msk        (0x4000UL)     /*!< SAIR174 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR173_Pos        (13UL)         /*!< SAIR173 (Bit 13)                                      */
#define R_CPSCU_ICU0SAR5_SAIR173_Msk        (0x2000UL)     /*!< SAIR173 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR172_Pos        (12UL)         /*!< SAIR172 (Bit 12)                                      */
#define R_CPSCU_ICU0SAR5_SAIR172_Msk        (0x1000UL)     /*!< SAIR172 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR171_Pos        (11UL)         /*!< SAIR171 (Bit 11)                                      */
#define R_CPSCU_ICU0SAR5_SAIR171_Msk        (0x800UL)      /*!< SAIR171 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR170_Pos        (10UL)         /*!< SAIR170 (Bit 10)                                      */
#define R_CPSCU_ICU0SAR5_SAIR170_Msk        (0x400UL)      /*!< SAIR170 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR169_Pos        (9UL)          /*!< SAIR169 (Bit 9)                                       */
#define R_CPSCU_ICU0SAR5_SAIR169_Msk        (0x200UL)      /*!< SAIR169 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR168_Pos        (8UL)          /*!< SAIR168 (Bit 8)                                       */
#define R_CPSCU_ICU0SAR5_SAIR168_Msk        (0x100UL)      /*!< SAIR168 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR167_Pos        (7UL)          /*!< SAIR167 (Bit 7)                                       */
#define R_CPSCU_ICU0SAR5_SAIR167_Msk        (0x80UL)       /*!< SAIR167 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR166_Pos        (6UL)          /*!< SAIR166 (Bit 6)                                       */
#define R_CPSCU_ICU0SAR5_SAIR166_Msk        (0x40UL)       /*!< SAIR166 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR165_Pos        (5UL)          /*!< SAIR165 (Bit 5)                                       */
#define R_CPSCU_ICU0SAR5_SAIR165_Msk        (0x20UL)       /*!< SAIR165 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR164_Pos        (4UL)          /*!< SAIR164 (Bit 4)                                       */
#define R_CPSCU_ICU0SAR5_SAIR164_Msk        (0x10UL)       /*!< SAIR164 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR163_Pos        (3UL)          /*!< SAIR163 (Bit 3)                                       */
#define R_CPSCU_ICU0SAR5_SAIR163_Msk        (0x8UL)        /*!< SAIR163 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR162_Pos        (2UL)          /*!< SAIR162 (Bit 2)                                       */
#define R_CPSCU_ICU0SAR5_SAIR162_Msk        (0x4UL)        /*!< SAIR162 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR161_Pos        (1UL)          /*!< SAIR161 (Bit 1)                                       */
#define R_CPSCU_ICU0SAR5_SAIR161_Msk        (0x2UL)        /*!< SAIR161 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR5_SAIR160_Pos        (0UL)          /*!< SAIR160 (Bit 0)                                       */
#define R_CPSCU_ICU0SAR5_SAIR160_Msk        (0x1UL)        /*!< SAIR160 (Bitfield-Mask: 0x01)                         */
/* =======================================================  ICU0SAR6  ======================================================== */
#define R_CPSCU_ICU0SAR6_SAIR223_Pos        (31UL)         /*!< SAIR223 (Bit 31)                                      */
#define R_CPSCU_ICU0SAR6_SAIR223_Msk        (0x80000000UL) /*!< SAIR223 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR222_Pos        (30UL)         /*!< SAIR222 (Bit 30)                                      */
#define R_CPSCU_ICU0SAR6_SAIR222_Msk        (0x40000000UL) /*!< SAIR222 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR221_Pos        (29UL)         /*!< SAIR221 (Bit 29)                                      */
#define R_CPSCU_ICU0SAR6_SAIR221_Msk        (0x20000000UL) /*!< SAIR221 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR220_Pos        (28UL)         /*!< SAIR220 (Bit 28)                                      */
#define R_CPSCU_ICU0SAR6_SAIR220_Msk        (0x10000000UL) /*!< SAIR220 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR219_Pos        (27UL)         /*!< SAIR219 (Bit 27)                                      */
#define R_CPSCU_ICU0SAR6_SAIR219_Msk        (0x8000000UL)  /*!< SAIR219 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR218_Pos        (26UL)         /*!< SAIR218 (Bit 26)                                      */
#define R_CPSCU_ICU0SAR6_SAIR218_Msk        (0x4000000UL)  /*!< SAIR218 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR217_Pos        (25UL)         /*!< SAIR217 (Bit 25)                                      */
#define R_CPSCU_ICU0SAR6_SAIR217_Msk        (0x2000000UL)  /*!< SAIR217 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR216_Pos        (24UL)         /*!< SAIR216 (Bit 24)                                      */
#define R_CPSCU_ICU0SAR6_SAIR216_Msk        (0x1000000UL)  /*!< SAIR216 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR215_Pos        (23UL)         /*!< SAIR215 (Bit 23)                                      */
#define R_CPSCU_ICU0SAR6_SAIR215_Msk        (0x800000UL)   /*!< SAIR215 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR214_Pos        (22UL)         /*!< SAIR214 (Bit 22)                                      */
#define R_CPSCU_ICU0SAR6_SAIR214_Msk        (0x400000UL)   /*!< SAIR214 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR213_Pos        (21UL)         /*!< SAIR213 (Bit 21)                                      */
#define R_CPSCU_ICU0SAR6_SAIR213_Msk        (0x200000UL)   /*!< SAIR213 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR212_Pos        (20UL)         /*!< SAIR212 (Bit 20)                                      */
#define R_CPSCU_ICU0SAR6_SAIR212_Msk        (0x100000UL)   /*!< SAIR212 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR211_Pos        (19UL)         /*!< SAIR211 (Bit 19)                                      */
#define R_CPSCU_ICU0SAR6_SAIR211_Msk        (0x80000UL)    /*!< SAIR211 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR210_Pos        (18UL)         /*!< SAIR210 (Bit 18)                                      */
#define R_CPSCU_ICU0SAR6_SAIR210_Msk        (0x40000UL)    /*!< SAIR210 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR209_Pos        (17UL)         /*!< SAIR209 (Bit 17)                                      */
#define R_CPSCU_ICU0SAR6_SAIR209_Msk        (0x20000UL)    /*!< SAIR209 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR208_Pos        (16UL)         /*!< SAIR208 (Bit 16)                                      */
#define R_CPSCU_ICU0SAR6_SAIR208_Msk        (0x10000UL)    /*!< SAIR208 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR207_Pos        (15UL)         /*!< SAIR207 (Bit 15)                                      */
#define R_CPSCU_ICU0SAR6_SAIR207_Msk        (0x8000UL)     /*!< SAIR207 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR206_Pos        (14UL)         /*!< SAIR206 (Bit 14)                                      */
#define R_CPSCU_ICU0SAR6_SAIR206_Msk        (0x4000UL)     /*!< SAIR206 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR205_Pos        (13UL)         /*!< SAIR205 (Bit 13)                                      */
#define R_CPSCU_ICU0SAR6_SAIR205_Msk        (0x2000UL)     /*!< SAIR205 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR204_Pos        (12UL)         /*!< SAIR204 (Bit 12)                                      */
#define R_CPSCU_ICU0SAR6_SAIR204_Msk        (0x1000UL)     /*!< SAIR204 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR203_Pos        (11UL)         /*!< SAIR203 (Bit 11)                                      */
#define R_CPSCU_ICU0SAR6_SAIR203_Msk        (0x800UL)      /*!< SAIR203 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR202_Pos        (10UL)         /*!< SAIR202 (Bit 10)                                      */
#define R_CPSCU_ICU0SAR6_SAIR202_Msk        (0x400UL)      /*!< SAIR202 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR201_Pos        (9UL)          /*!< SAIR201 (Bit 9)                                       */
#define R_CPSCU_ICU0SAR6_SAIR201_Msk        (0x200UL)      /*!< SAIR201 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR200_Pos        (8UL)          /*!< SAIR200 (Bit 8)                                       */
#define R_CPSCU_ICU0SAR6_SAIR200_Msk        (0x100UL)      /*!< SAIR200 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR199_Pos        (7UL)          /*!< SAIR199 (Bit 7)                                       */
#define R_CPSCU_ICU0SAR6_SAIR199_Msk        (0x80UL)       /*!< SAIR199 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR198_Pos        (6UL)          /*!< SAIR198 (Bit 6)                                       */
#define R_CPSCU_ICU0SAR6_SAIR198_Msk        (0x40UL)       /*!< SAIR198 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR197_Pos        (5UL)          /*!< SAIR197 (Bit 5)                                       */
#define R_CPSCU_ICU0SAR6_SAIR197_Msk        (0x20UL)       /*!< SAIR197 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR196_Pos        (4UL)          /*!< SAIR196 (Bit 4)                                       */
#define R_CPSCU_ICU0SAR6_SAIR196_Msk        (0x10UL)       /*!< SAIR196 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR195_Pos        (3UL)          /*!< SAIR195 (Bit 3)                                       */
#define R_CPSCU_ICU0SAR6_SAIR195_Msk        (0x8UL)        /*!< SAIR195 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR194_Pos        (2UL)          /*!< SAIR194 (Bit 2)                                       */
#define R_CPSCU_ICU0SAR6_SAIR194_Msk        (0x4UL)        /*!< SAIR194 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR193_Pos        (1UL)          /*!< SAIR193 (Bit 1)                                       */
#define R_CPSCU_ICU0SAR6_SAIR193_Msk        (0x2UL)        /*!< SAIR193 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR6_SAIR192_Pos        (0UL)          /*!< SAIR192 (Bit 0)                                       */
#define R_CPSCU_ICU0SAR6_SAIR192_Msk        (0x1UL)        /*!< SAIR192 (Bitfield-Mask: 0x01)                         */
/* =======================================================  ICU0SAR7  ======================================================== */
#define R_CPSCU_ICU0SAR7_SAIR255_Pos        (31UL)         /*!< SAIR255 (Bit 31)                                      */
#define R_CPSCU_ICU0SAR7_SAIR255_Msk        (0x80000000UL) /*!< SAIR255 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR254_Pos        (30UL)         /*!< SAIR254 (Bit 30)                                      */
#define R_CPSCU_ICU0SAR7_SAIR254_Msk        (0x40000000UL) /*!< SAIR254 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR253_Pos        (29UL)         /*!< SAIR253 (Bit 29)                                      */
#define R_CPSCU_ICU0SAR7_SAIR253_Msk        (0x20000000UL) /*!< SAIR253 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR252_Pos        (28UL)         /*!< SAIR252 (Bit 28)                                      */
#define R_CPSCU_ICU0SAR7_SAIR252_Msk        (0x10000000UL) /*!< SAIR252 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR251_Pos        (27UL)         /*!< SAIR251 (Bit 27)                                      */
#define R_CPSCU_ICU0SAR7_SAIR251_Msk        (0x8000000UL)  /*!< SAIR251 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR250_Pos        (26UL)         /*!< SAIR250 (Bit 26)                                      */
#define R_CPSCU_ICU0SAR7_SAIR250_Msk        (0x4000000UL)  /*!< SAIR250 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR249_Pos        (25UL)         /*!< SAIR249 (Bit 25)                                      */
#define R_CPSCU_ICU0SAR7_SAIR249_Msk        (0x2000000UL)  /*!< SAIR249 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR248_Pos        (24UL)         /*!< SAIR248 (Bit 24)                                      */
#define R_CPSCU_ICU0SAR7_SAIR248_Msk        (0x1000000UL)  /*!< SAIR248 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR247_Pos        (23UL)         /*!< SAIR247 (Bit 23)                                      */
#define R_CPSCU_ICU0SAR7_SAIR247_Msk        (0x800000UL)   /*!< SAIR247 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR246_Pos        (22UL)         /*!< SAIR246 (Bit 22)                                      */
#define R_CPSCU_ICU0SAR7_SAIR246_Msk        (0x400000UL)   /*!< SAIR246 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR245_Pos        (21UL)         /*!< SAIR245 (Bit 21)                                      */
#define R_CPSCU_ICU0SAR7_SAIR245_Msk        (0x200000UL)   /*!< SAIR245 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR244_Pos        (20UL)         /*!< SAIR244 (Bit 20)                                      */
#define R_CPSCU_ICU0SAR7_SAIR244_Msk        (0x100000UL)   /*!< SAIR244 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR243_Pos        (19UL)         /*!< SAIR243 (Bit 19)                                      */
#define R_CPSCU_ICU0SAR7_SAIR243_Msk        (0x80000UL)    /*!< SAIR243 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR242_Pos        (18UL)         /*!< SAIR242 (Bit 18)                                      */
#define R_CPSCU_ICU0SAR7_SAIR242_Msk        (0x40000UL)    /*!< SAIR242 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR241_Pos        (17UL)         /*!< SAIR241 (Bit 17)                                      */
#define R_CPSCU_ICU0SAR7_SAIR241_Msk        (0x20000UL)    /*!< SAIR241 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR240_Pos        (16UL)         /*!< SAIR240 (Bit 16)                                      */
#define R_CPSCU_ICU0SAR7_SAIR240_Msk        (0x10000UL)    /*!< SAIR240 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR239_Pos        (15UL)         /*!< SAIR239 (Bit 15)                                      */
#define R_CPSCU_ICU0SAR7_SAIR239_Msk        (0x8000UL)     /*!< SAIR239 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR238_Pos        (14UL)         /*!< SAIR238 (Bit 14)                                      */
#define R_CPSCU_ICU0SAR7_SAIR238_Msk        (0x4000UL)     /*!< SAIR238 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR237_Pos        (13UL)         /*!< SAIR237 (Bit 13)                                      */
#define R_CPSCU_ICU0SAR7_SAIR237_Msk        (0x2000UL)     /*!< SAIR237 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR236_Pos        (12UL)         /*!< SAIR236 (Bit 12)                                      */
#define R_CPSCU_ICU0SAR7_SAIR236_Msk        (0x1000UL)     /*!< SAIR236 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR235_Pos        (11UL)         /*!< SAIR235 (Bit 11)                                      */
#define R_CPSCU_ICU0SAR7_SAIR235_Msk        (0x800UL)      /*!< SAIR235 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR234_Pos        (10UL)         /*!< SAIR234 (Bit 10)                                      */
#define R_CPSCU_ICU0SAR7_SAIR234_Msk        (0x400UL)      /*!< SAIR234 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR233_Pos        (9UL)          /*!< SAIR233 (Bit 9)                                       */
#define R_CPSCU_ICU0SAR7_SAIR233_Msk        (0x200UL)      /*!< SAIR233 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR232_Pos        (8UL)          /*!< SAIR232 (Bit 8)                                       */
#define R_CPSCU_ICU0SAR7_SAIR232_Msk        (0x100UL)      /*!< SAIR232 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR231_Pos        (7UL)          /*!< SAIR231 (Bit 7)                                       */
#define R_CPSCU_ICU0SAR7_SAIR231_Msk        (0x80UL)       /*!< SAIR231 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR230_Pos        (6UL)          /*!< SAIR230 (Bit 6)                                       */
#define R_CPSCU_ICU0SAR7_SAIR230_Msk        (0x40UL)       /*!< SAIR230 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR229_Pos        (5UL)          /*!< SAIR229 (Bit 5)                                       */
#define R_CPSCU_ICU0SAR7_SAIR229_Msk        (0x20UL)       /*!< SAIR229 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR228_Pos        (4UL)          /*!< SAIR228 (Bit 4)                                       */
#define R_CPSCU_ICU0SAR7_SAIR228_Msk        (0x10UL)       /*!< SAIR228 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR227_Pos        (3UL)          /*!< SAIR227 (Bit 3)                                       */
#define R_CPSCU_ICU0SAR7_SAIR227_Msk        (0x8UL)        /*!< SAIR227 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR226_Pos        (2UL)          /*!< SAIR226 (Bit 2)                                       */
#define R_CPSCU_ICU0SAR7_SAIR226_Msk        (0x4UL)        /*!< SAIR226 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR225_Pos        (1UL)          /*!< SAIR225 (Bit 1)                                       */
#define R_CPSCU_ICU0SAR7_SAIR225_Msk        (0x2UL)        /*!< SAIR225 (Bitfield-Mask: 0x01)                         */
#define R_CPSCU_ICU0SAR7_SAIR224_Pos        (0UL)          /*!< SAIR224 (Bit 0)                                       */
#define R_CPSCU_ICU0SAR7_SAIR224_Msk        (0x1UL)        /*!< SAIR224 (Bitfield-Mask: 0x01)                         */
/* ========================================================  BUSSARA  ======================================================== */
#define R_CPSCU_BUSSARA_BUSSA0_Pos          (0UL)          /*!< BUSSA0 (Bit 0)                                        */
#define R_CPSCU_BUSSARA_BUSSA0_Msk          (0x1UL)        /*!< BUSSA0 (Bitfield-Mask: 0x01)                          */
/* ========================================================  BUSSARB  ======================================================== */
#define R_CPSCU_BUSSARB_BUSSB0_Pos          (0UL)          /*!< BUSSB0 (Bit 0)                                        */
#define R_CPSCU_BUSSARB_BUSSB0_Msk          (0x1UL)        /*!< BUSSB0 (Bitfield-Mask: 0x01)                          */
/* ========================================================  BUSSARC  ======================================================== */
#define R_CPSCU_BUSSARC_BUSSC0_Pos          (0UL)          /*!< BUSSC0 (Bit 0)                                        */
#define R_CPSCU_BUSSARC_BUSSC0_Msk          (0x1UL)        /*!< BUSSC0 (Bitfield-Mask: 0x01)                          */
/* =======================================================  MMPUSARB  ======================================================== */
#define R_CPSCU_MMPUSARB_MMPUBSA8_Pos       (8UL)          /*!< MMPUBSA8 (Bit 8)                                      */
#define R_CPSCU_MMPUSARB_MMPUBSA8_Msk       (0x100UL)      /*!< MMPUBSA8 (Bitfield-Mask: 0x01)                        */
/* ========================================================  TFUSAR  ========================================================= */
#define R_CPSCU_TFUSAR_TFUSA_Pos            (0UL)          /*!< TFUSA (Bit 0)                                         */
#define R_CPSCU_TFUSAR_TFUSA_Msk            (0x1UL)        /*!< TFUSA (Bitfield-Mask: 0x01)                           */
/* ========================================================  IFUSAR  ========================================================= */
#define R_CPSCU_IFUSAR_IFUSA_Pos            (0UL)          /*!< IFUSA (Bit 0)                                         */
#define R_CPSCU_IFUSAR_IFUSA_Msk            (0x1UL)        /*!< IFUSA (Bitfield-Mask: 0x01)                           */
/* ======================================================  EXDMACCHSAR  ====================================================== */
#define R_CPSCU_EXDMACCHSAR_SADMACX1_Pos    (1UL)          /*!< SADMACX1 (Bit 1)                                      */
#define R_CPSCU_EXDMACCHSAR_SADMACX1_Msk    (0x2UL)        /*!< SADMACX1 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_EXDMACCHSAR_SADMACX0_Pos    (0UL)          /*!< SADMACX0 (Bit 0)                                      */
#define R_CPSCU_EXDMACCHSAR_SADMACX0_Msk    (0x1UL)        /*!< SADMACX0 (Bitfield-Mask: 0x01)                        */
/* =======================================================  DMACCHSAR  ======================================================= */
#define R_CPSCU_DMACCHSAR_SADMAC07_Pos      (7UL)          /*!< SADMAC07 (Bit 7)                                      */
#define R_CPSCU_DMACCHSAR_SADMAC07_Msk      (0x80UL)       /*!< SADMAC07 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_DMACCHSAR_SADMAC06_Pos      (6UL)          /*!< SADMAC06 (Bit 6)                                      */
#define R_CPSCU_DMACCHSAR_SADMAC06_Msk      (0x40UL)       /*!< SADMAC06 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_DMACCHSAR_SADMAC05_Pos      (5UL)          /*!< SADMAC05 (Bit 5)                                      */
#define R_CPSCU_DMACCHSAR_SADMAC05_Msk      (0x20UL)       /*!< SADMAC05 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_DMACCHSAR_SADMAC04_Pos      (4UL)          /*!< SADMAC04 (Bit 4)                                      */
#define R_CPSCU_DMACCHSAR_SADMAC04_Msk      (0x10UL)       /*!< SADMAC04 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_DMACCHSAR_SADMAC03_Pos      (3UL)          /*!< SADMAC03 (Bit 3)                                      */
#define R_CPSCU_DMACCHSAR_SADMAC03_Msk      (0x8UL)        /*!< SADMAC03 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_DMACCHSAR_SADMAC02_Pos      (2UL)          /*!< SADMAC02 (Bit 2)                                      */
#define R_CPSCU_DMACCHSAR_SADMAC02_Msk      (0x4UL)        /*!< SADMAC02 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_DMACCHSAR_SADMAC01_Pos      (1UL)          /*!< SADMAC01 (Bit 1)                                      */
#define R_CPSCU_DMACCHSAR_SADMAC01_Msk      (0x2UL)        /*!< SADMAC01 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_DMACCHSAR_SADMAC00_Pos      (0UL)          /*!< SADMAC00 (Bit 0)                                      */
#define R_CPSCU_DMACCHSAR_SADMAC00_Msk      (0x1UL)        /*!< SADMAC00 (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_DMACCHSAR_all_Msk           (0xffUL)       /*!< SADMAC00 to 07 (Bitfield-Mask: 0xff)                  */
/* ======================================================  SRAMSABAR0  ======================================================= */
#define R_CPSCU_SRAMSABAR0_SRAMSABAR_Pos    (13UL)         /*!< SRAMSABAR (Bit 13)                                    */
#define R_CPSCU_SRAMSABAR0_SRAMSABAR_Msk    (0x001fe000UL) /*!< SRAMSABAR (Bitfield-Mask: 0xff)                       */
/* ======================================================  SRAMSABAR1  ======================================================= */
#define R_CPSCU_SRAMSABAR1_SRAMSABAR_Pos    (13UL)         /*!< SRAMSABAR (Bit 13)                                    */
#define R_CPSCU_SRAMSABAR1_SRAMSABAR_Msk    (0x001fe000UL) /*!< SRAMSABAR (Bitfield-Mask: 0xff)                       */
/* =======================================================  CACHESAR  ======================================================== */
#define R_CPSCU_CACHESAR_CACHEESA_Pos       (2UL)          /*!< CACHEESA (Bit 2)                                      */
#define R_CPSCU_CACHESAR_CACHEESA_Msk       (0x4UL)        /*!< CACHEESA (Bitfield-Mask: 0x01)                        */
#define R_CPSCU_CACHESAR_CACHESA_Pos        (0UL)          /*!< CACHESA (Bit 0)                                       */
#define R_CPSCU_CACHESAR_CACHESA_Msk        (0x1UL)        /*!< CACHESA (Bitfield-Mask: 0x01)                         */
/* ========================================================  LRMSAR  ========================================================= */
#define R_CPSCU_LRMSAR_LRMSA_Pos            (0UL)          /*!< LRMSA (Bit 0)                                         */
#define R_CPSCU_LRMSAR_LRMSA_Msk            (0x1UL)        /*!< LRMSA (Bitfield-Mask: 0x01)                           */
/* =======================================================  LRMSABAR0  ======================================================= */
#define R_CPSCU_LRMSABAR0_LRMSABA_Pos       (13UL)         /*!< LRMSABA (Bit 13)                                      */
#define R_CPSCU_LRMSABAR0_LRMSABA_Msk       (0x7e000UL)    /*!< LRMSABA (Bitfield-Mask: 0x3f)                         */
/* =======================================================  LRMSABAR1  ======================================================= */
#define R_CPSCU_LRMSABAR1_LRMSABA_Pos       (13UL)         /*!< LRMSABA (Bit 13)                                      */
#define R_CPSCU_LRMSABAR1_LRMSABA_Msk       (0x7e000UL)    /*!< LRMSABA (Bitfield-Mask: 0x3f)                         */
/* ========================================================  TEVTRCR  ======================================================== */
#define R_CPSCU_TEVTRCR_TEVTEICU0_Pos       (1UL)          /*!< TEVTEICU0 (Bit 1)                                     */
#define R_CPSCU_TEVTRCR_TEVTEICU0_Msk       (0x2UL)        /*!< TEVTEICU0 (Bitfield-Mask: 0x01)                       */
#define R_CPSCU_TEVTRCR_TEVTE_Pos           (0UL)          /*!< TEVTE (Bit 0)                                         */
#define R_CPSCU_TEVTRCR_TEVTE_Msk           (0x1UL)        /*!< TEVTE (Bitfield-Mask: 0x01)                           */
/* =======================================================  ICUNSACR  ======================================================== */
#define R_CPSCU_ICUNSACR_NSACE_Pos          (0UL)          /*!< NSACE (Bit 0)                                         */
#define R_CPSCU_ICUNSACR_NSACE_Msk          (0x1UL)        /*!< NSACE (Bitfield-Mask: 0x01)                           */
/* ========================================================  PRTZCR  ========================================================= */
#define R_CPSCU_PRTZCR_PRTZC_Pos            (0UL)          /*!< PRTZC (Bit 0)                                         */
#define R_CPSCU_PRTZCR_PRTZC_Msk            (0x1UL)        /*!< PRTZC (Bitfield-Mask: 0x01)                           */

/** @} */ /* End of group PosMask_peripherals */

#endif /* R_CPSCU_POSMSK_H */
