/*
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#ifndef R_DMAC_CFG_H_
#define R_DMAC_CFG_H_
#define DMAC_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define DMAC_CFG_MULTIPLEX_INTERRUPT_SUPPORTED (0)
#if DMAC_CFG_MULTIPLEX_INTERRUPT_SUPPORTED
 #define DMAC_CFG_MULTIPLEX_INTERRUPT_ENABLE         BSP_INTERRUPT_ENABLE
 #define DMAC_CFG_MULTIPLEX_INTERRUPT_DISABLE        BSP_INTERRUPT_DISABLE
#else
#define DMAC_CFG_MULTIPLEX_INTERRUPT_ENABLE
#define DMAC_CFG_MULTIPLEX_INTERRUPT_DISABLE
#endif

#define DMAC_CFG_CHANNEL_PRIORITY_UNIT0_CHANNEL0_7   (0)
#if BSP_MCU_GROUP_RZN2H
 #define DMAC_CFG_CHANNEL_PRIORITY_UNIT0_CHANNEL8_15  (0)
#endif
#define DMAC_CFG_CHANNEL_PRIORITY_UNIT1_CHANNEL0_7   (0)
#if BSP_MCU_GROUP_RZN2H
 #define DMAC_CFG_CHANNEL_PRIORITY_UNIT1_CHANNEL8_15  (0)
#endif
#endif /* R_DMAC_CFG_H_ */
