/*
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#ifndef R_DMAC_CFG_H_
#define R_DMAC_CFG_H_
#ifdef __cplusplus
extern "C" {
#endif

#define DMAC_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define DMAC_CFG_MULTIPLEX_INTERRUPT_SUPPORTED (0) // DEPRECATED
#if DMAC_CFG_MULTIPLEX_INTERRUPT_SUPPORTED
 #define DMAC_CFG_MULTIPLEX_INTERRUPT_ENABLE         BSP_INTERRUPT_ENABLE  // DEPRECATED
 #define DMAC_CFG_MULTIPLEX_INTERRUPT_DISABLE        BSP_INTERRUPT_DISABLE // DEPRECATED
#else
 #define DMAC_CFG_MULTIPLEX_INTERRUPT_ENABLE  // DEPRECATED
 #define DMAC_CFG_MULTIPLEX_INTERRUPT_DISABLE // DEPRECATED
#endif

#define DMAC_CFG_CHANNEL_PRIORITY_UNIT0_CHANNEL0_7   (0)
#if BSP_MCU_GROUP_RZN2H
 #define DMAC_CFG_CHANNEL_PRIORITY_UNIT0_CHANNEL8_15  (0)
#endif
#define DMAC_CFG_CHANNEL_PRIORITY_UNIT1_CHANNEL0_7   (0)
#if BSP_MCU_GROUP_RZN2H
 #define DMAC_CFG_CHANNEL_PRIORITY_UNIT1_CHANNEL8_15  (0)
#endif

#define DMAC_CFG_DACK_ACTIVE_LEVEL (DMAC_EXTERNAL_OUTPUT_SIGNAL_ACTIVE_LEVEL_LOW_ACTIVE)
#define DMAC_CFG_TEND_ACTIVE_LEVEL (DMAC_EXTERNAL_OUTPUT_SIGNAL_ACTIVE_LEVEL_LOW_ACTIVE)

#ifdef __cplusplus
}
#endif
#endif /* R_DMAC_CFG_H_ */
