/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#ifndef R_IIC_MASTER_CFG_H_
#define R_IIC_MASTER_CFG_H_
#define IIC_MASTER_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define IIC_MASTER_CFG_DMAC_ENABLE (0)
#define IIC_MASTER_CFG_ADDR_MODE_10_BIT_ENABLE (1)
#define IIC_MASTER_CFG_MULTIPLEX_INTERRUPT_SUPPORTED (0)
#if IIC_MASTER_CFG_MULTIPLEX_INTERRUPT_SUPPORTED
 #define IIC_MASTER_CFG_MULTIPLEX_INTERRUPT_ENABLE         BSP_INTERRUPT_ENABLE
 #define IIC_MASTER_CFG_MULTIPLEX_INTERRUPT_DISABLE        BSP_INTERRUPT_DISABLE
#else
#define IIC_MASTER_CFG_MULTIPLEX_INTERRUPT_ENABLE
#define IIC_MASTER_CFG_MULTIPLEX_INTERRUPT_DISABLE
#endif
#endif /* R_IIC_MASTER_CFG_H_ */
