/*
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#ifndef R_XSPI_QSPI_CFG_H_
#define R_XSPI_QSPI_CFG_H_
#define XSPI_QSPI_CFG_PARAM_CHECKING_ENABLE      (BSP_CFG_PARAM_CHECKING_ENABLE)
#define XSPI_QSPI_CFG_UNIT_0_PREFETCH_FUNCTION   (0)
#define XSPI_QSPI_CFG_UNIT_1_PREFETCH_FUNCTION   (0)
#define XSPI_QSPI_CFG_UNIT_0_IOVOLTAGE           (0)
#define XSPI_QSPI_CFG_UNIT_1_IOVOLTAGE           (0)
#define XSPI_QSPI_CFG_DMAC_SUPPORT_ENABLE        (0)
#define XSPI_QSPI_CFG_UNIT_0_CS_0_END_ADDRESS    (0x63FFFFFF)
#define XSPI_QSPI_CFG_UNIT_0_CS_1_START_ADDRESS  (0x64000000)
#define XSPI_QSPI_CFG_UNIT_0_CS_1_END_ADDRESS    (0x640FFFFF)
#define XSPI_QSPI_CFG_UNIT_1_CS_0_END_ADDRESS    (0x680FFFFF)
#define XSPI_QSPI_CFG_UNIT_1_CS_1_START_ADDRESS  (0x6C000000)
#define XSPI_QSPI_CFG_UNIT_1_CS_1_END_ADDRESS    (0x6C0FFFFF)
#define XSPI_QSPI_CFG_CUSTOM_ADDR_SPACE_ENABLE   (0)
#define XSPI_QSPI_CFG_OTFD_SUPPORT_ENABLE        (0)
#endif /* R_XSPI_QSPI_CFG_H_ */
