/*
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

/* Ensure Renesas MCU variation definitions are included to ensure MCU
 * specific register variations are handled correctly. */
#ifndef BSP_FEATURE_H
 #error "INTERNAL ERROR: bsp_feature.h must be included before renesas.h."
#endif

/** @addtogroup Renesas
 * @{
 */

/** @addtogroup RX
 * @{
 */

#ifndef RX_H
 #define RX_H

 #ifdef __cplusplus
extern "C" {
 #endif

/* IO definitions (access restrictions to peripheral registers) */

/**
 *  \defgroup CMSIS_glob_defs CMSIS Global Defines
 *
 *  <strong>IO Type Qualifiers</strong> are used
 *  \li to specify the access to peripheral variables.
 *  \li for automatic generation of peripheral register debug information.
 */
 #ifdef __cplusplus
  #define   __I       volatile         /*!< Defines 'read only' permissions */
 #else
  #define   __I       volatile const   /*!< Defines 'read only' permissions */
 #endif
 #define     __O      volatile         /*!< Defines 'write only' permissions */
 #define     __IO     volatile         /*!< Defines 'read / write' permissions */

/* following defines should be used for structure members */
 #ifdef __cplusplus
  #define   __IM      volatile         /*! Defines 'read only' structure member permissions */
 #else
  #define   __IM      volatile const   /*! Defines 'read only' structure member permissions */
 #endif
 #define     __OM     volatile         /*! Defines 'write only' structure member permissions */
 #define     __IOM    volatile         /*! Defines 'read / write' structure member permissions */

/** @addtogroup Configuration_of_RX
 * @{
 */

/* =========================================================================================================================== */
/* ================                                Interrupt Number Definition                                ================ */
/* =========================================================================================================================== */
/* IRQn_Type is provided in bsp_exceptions.h. Vectors generated by the FSP Configuration tool are in vector_data.h */

/** @} */ /* End of group Configuration_of_RX */

/* =========================================================================================================================== */
/* ================                           Processor and Core Peripheral Section                           ================ */
/* =========================================================================================================================== */

 #if BSP_MCU_GROUP_RX74M
  #include "R5K574M.h"
 #elif BSP_MCU_GROUP_RX74N
  #include "R5K574N.h"
 #else
  #if __has_include("renesas_internal.h")
   #include "renesas_internal.h"
  #else
   #warning "Unsupported MCU"
  #endif
 #endif

 #define RENESAS_RX_V3

 #ifdef __cplusplus
}
 #endif

#endif                                 /* RX_H */

/** @} */ /* End of group RX */

/** @} */ /* End of group Renesas */
