/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

/**********************************************************************************************************************
 * File Name    : riic_iobitmask.h
 * Version      : 1.00
 * Description  : IO bit mask file for riic.
 *********************************************************************************************************************/

#ifndef RIIC_IOBITMASK_H
#define RIIC_IOBITMASK_H

#define R_RIIC_ICCR1_SDAI_Msk       (0x01UL)
#define R_RIIC_ICCR1_SDAI_Pos       (0UL)
#define R_RIIC_ICCR1_SCLI_Msk       (0x02UL)
#define R_RIIC_ICCR1_SCLI_Pos       (1UL)
#define R_RIIC_ICCR1_SDAO_Msk       (0x04UL)
#define R_RIIC_ICCR1_SDAO_Pos       (2UL)
#define R_RIIC_ICCR1_SCLO_Msk       (0x08UL)
#define R_RIIC_ICCR1_SCLO_Pos       (3UL)
#define R_RIIC_ICCR1_SOWP_Msk       (0x10UL)
#define R_RIIC_ICCR1_SOWP_Pos       (4UL)
#define R_RIIC_ICCR1_CLO_Msk        (0x20UL)
#define R_RIIC_ICCR1_CLO_Pos        (5UL)
#define R_RIIC_ICCR1_IICRST_Msk     (0x40UL)
#define R_RIIC_ICCR1_IICRST_Pos     (6UL)
#define R_RIIC_ICCR1_ICE_Msk        (0x80UL)
#define R_RIIC_ICCR1_ICE_Pos        (7UL)
#define R_RIIC_ICCR2_ST_Msk         (0x02UL)
#define R_RIIC_ICCR2_ST_Pos         (1UL)
#define R_RIIC_ICCR2_RS_Msk         (0x04UL)
#define R_RIIC_ICCR2_RS_Pos         (2UL)
#define R_RIIC_ICCR2_SP_Msk         (0x08UL)
#define R_RIIC_ICCR2_SP_Pos         (3UL)
#define R_RIIC_ICCR2_TRS_Msk        (0x20UL)
#define R_RIIC_ICCR2_TRS_Pos        (5UL)
#define R_RIIC_ICCR2_MST_Msk        (0x40UL)
#define R_RIIC_ICCR2_MST_Pos        (6UL)
#define R_RIIC_ICCR2_BBSY_Msk       (0x80UL)
#define R_RIIC_ICCR2_BBSY_Pos       (7UL)
#define R_RIIC_ICMR1_BC_Msk         (0x07UL)
#define R_RIIC_ICMR1_BC_Pos         (0UL)
#define R_RIIC_ICMR1_BCWP_Msk       (0x08UL)
#define R_RIIC_ICMR1_BCWP_Pos       (3UL)
#define R_RIIC_ICMR1_CKS_Msk        (0x70UL)
#define R_RIIC_ICMR1_CKS_Pos        (4UL)
#define R_RIIC_ICMR2_TMOS_Msk       (0x01UL)
#define R_RIIC_ICMR2_TMOS_Pos       (0UL)
#define R_RIIC_ICMR2_TMOL_Msk       (0x02UL)
#define R_RIIC_ICMR2_TMOL_Pos       (1UL)
#define R_RIIC_ICMR2_TMOH_Msk       (0x04UL)
#define R_RIIC_ICMR2_TMOH_Pos       (2UL)
#define R_RIIC_ICMR2_SDDL_Msk       (0x70UL)
#define R_RIIC_ICMR2_SDDL_Pos       (4UL)
#define R_RIIC_ICMR2_DLCS_Msk       (0x80UL)
#define R_RIIC_ICMR2_DLCS_Pos       (7UL)
#define R_RIIC_ICMR3_NF_Msk         (0x03UL)
#define R_RIIC_ICMR3_NF_Pos         (0UL)
#define R_RIIC_ICMR3_ACKBR_Msk      (0x04UL)
#define R_RIIC_ICMR3_ACKBR_Pos      (2UL)
#define R_RIIC_ICMR3_ACKBT_Msk      (0x08UL)
#define R_RIIC_ICMR3_ACKBT_Pos      (3UL)
#define R_RIIC_ICMR3_ACKWP_Msk      (0x10UL)
#define R_RIIC_ICMR3_ACKWP_Pos      (4UL)
#define R_RIIC_ICMR3_RDRFS_Msk      (0x20UL)
#define R_RIIC_ICMR3_RDRFS_Pos      (5UL)
#define R_RIIC_ICMR3_WAIT_Msk       (0x40UL)
#define R_RIIC_ICMR3_WAIT_Pos       (6UL)
#define R_RIIC_ICMR3_SMBE_Msk       (0x80UL)
#define R_RIIC_ICMR3_SMBE_Pos       (7UL)
#define R_RIIC_ICFER_TMOE_Msk       (0x01UL)
#define R_RIIC_ICFER_TMOE_Pos       (0UL)
#define R_RIIC_ICFER_MALE_Msk       (0x02UL)
#define R_RIIC_ICFER_MALE_Pos       (1UL)
#define R_RIIC_ICFER_NALE_Msk       (0x04UL)
#define R_RIIC_ICFER_NALE_Pos       (2UL)
#define R_RIIC_ICFER_SALE_Msk       (0x08UL)
#define R_RIIC_ICFER_SALE_Pos       (3UL)
#define R_RIIC_ICFER_NACKE_Msk      (0x10UL)
#define R_RIIC_ICFER_NACKE_Pos      (4UL)
#define R_RIIC_ICFER_NFE_Msk        (0x20UL)
#define R_RIIC_ICFER_NFE_Pos        (5UL)
#define R_RIIC_ICFER_SCLE_Msk       (0x40UL)
#define R_RIIC_ICFER_SCLE_Pos       (6UL)
#define R_RIIC_ICFER_FMPE_Msk       (0x80UL)
#define R_RIIC_ICFER_FMPE_Pos       (7UL)
#define R_RIIC_ICSER_SAR0_Msk       (0x01UL)
#define R_RIIC_ICSER_SAR0_Pos       (0UL)
#define R_RIIC_ICSER_SAR1_Msk       (0x02UL)
#define R_RIIC_ICSER_SAR1_Pos       (1UL)
#define R_RIIC_ICSER_SAR2_Msk       (0x04UL)
#define R_RIIC_ICSER_SAR2_Pos       (2UL)
#define R_RIIC_ICSER_GCE_Msk        (0x08UL)
#define R_RIIC_ICSER_GCE_Pos        (3UL)
#define R_RIIC_ICSER_DIDE_Msk       (0x20UL)
#define R_RIIC_ICSER_DIDE_Pos       (5UL)
#define R_RIIC_ICSER_HOAE_Msk       (0x80UL)
#define R_RIIC_ICSER_HOAE_Pos       (7UL)
#define R_RIIC_ICIER_TMOIE_Msk      (0x01UL)
#define R_RIIC_ICIER_TMOIE_Pos      (0UL)
#define R_RIIC_ICIER_ALIE_Msk       (0x02UL)
#define R_RIIC_ICIER_ALIE_Pos       (1UL)
#define R_RIIC_ICIER_STIE_Msk       (0x04UL)
#define R_RIIC_ICIER_STIE_Pos       (2UL)
#define R_RIIC_ICIER_SPIE_Msk       (0x08UL)
#define R_RIIC_ICIER_SPIE_Pos       (3UL)
#define R_RIIC_ICIER_NAKIE_Msk      (0x10UL)
#define R_RIIC_ICIER_NAKIE_Pos      (4UL)
#define R_RIIC_ICIER_RIE_Msk        (0x20UL)
#define R_RIIC_ICIER_RIE_Pos        (5UL)
#define R_RIIC_ICIER_TEIE_Msk       (0x40UL)
#define R_RIIC_ICIER_TEIE_Pos       (6UL)
#define R_RIIC_ICIER_TIE_Msk        (0x80UL)
#define R_RIIC_ICIER_TIE_Pos        (7UL)
#define R_RIIC_ICSR1_AAS0_Msk       (0x01UL)
#define R_RIIC_ICSR1_AAS0_Pos       (0UL)
#define R_RIIC_ICSR1_AAS1_Msk       (0x02UL)
#define R_RIIC_ICSR1_AAS1_Pos       (1UL)
#define R_RIIC_ICSR1_AAS2_Msk       (0x04UL)
#define R_RIIC_ICSR1_AAS2_Pos       (2UL)
#define R_RIIC_ICSR1_GCA_Msk        (0x08UL)
#define R_RIIC_ICSR1_GCA_Pos        (3UL)
#define R_RIIC_ICSR1_DID_Msk        (0x20UL)
#define R_RIIC_ICSR1_DID_Pos        (5UL)
#define R_RIIC_ICSR1_HOA_Msk        (0x80UL)
#define R_RIIC_ICSR1_HOA_Pos        (7UL)
#define R_RIIC_ICSR2_TMOF_Msk       (0x01UL)
#define R_RIIC_ICSR2_TMOF_Pos       (0UL)
#define R_RIIC_ICSR2_AL_Msk         (0x02UL)
#define R_RIIC_ICSR2_AL_Pos         (1UL)
#define R_RIIC_ICSR2_START_Msk      (0x04UL)
#define R_RIIC_ICSR2_START_Pos      (2UL)
#define R_RIIC_ICSR2_STOP_Msk       (0x08UL)
#define R_RIIC_ICSR2_STOP_Pos       (3UL)
#define R_RIIC_ICSR2_NACKF_Msk      (0x10UL)
#define R_RIIC_ICSR2_NACKF_Pos      (4UL)
#define R_RIIC_ICSR2_RDRF_Msk       (0x20UL)
#define R_RIIC_ICSR2_RDRF_Pos       (5UL)
#define R_RIIC_ICSR2_TEND_Msk       (0x40UL)
#define R_RIIC_ICSR2_TEND_Pos       (6UL)
#define R_RIIC_ICSR2_TDRE_Msk       (0x80UL)
#define R_RIIC_ICSR2_TDRE_Pos       (7UL)
#define R_RIIC_ICSAR0_SVA0_Msk      (0x01UL)
#define R_RIIC_ICSAR0_SVA0_Pos      (0UL)
#define R_RIIC_ICSAR0_SVA_Msk       (0xFEUL)
#define R_RIIC_ICSAR0_SVA_Pos       (1UL)
#define R_RIIC_ICSARU0_FS_Msk       (0x01UL)
#define R_RIIC_ICSARU0_FS_Pos       (0UL)
#define R_RIIC_ICSARU0_SVA_Msk      (0x06UL)
#define R_RIIC_ICSARU0_SVA_Pos      (1UL)
#define R_RIIC_ICSAR1_SVA0_Msk      (0x01UL)
#define R_RIIC_ICSAR1_SVA0_Pos      (0UL)
#define R_RIIC_ICSAR1_SVA_Msk       (0xFEUL)
#define R_RIIC_ICSAR1_SVA_Pos       (1UL)
#define R_RIIC_ICSARU1_FS_Msk       (0x01UL)
#define R_RIIC_ICSARU1_FS_Pos       (0UL)
#define R_RIIC_ICSARU1_SVA_Msk      (0x06UL)
#define R_RIIC_ICSARU1_SVA_Pos      (1UL)
#define R_RIIC_ICSAR2_SVA0_Msk      (0x01UL)
#define R_RIIC_ICSAR2_SVA0_Pos      (0UL)
#define R_RIIC_ICSAR2_SVA_Msk       (0xFEUL)
#define R_RIIC_ICSAR2_SVA_Pos       (1UL)
#define R_RIIC_ICSARU2_FS_Msk       (0x01UL)
#define R_RIIC_ICSARU2_FS_Pos       (0UL)
#define R_RIIC_ICSARU2_SVA_Msk      (0x06UL)
#define R_RIIC_ICSARU2_SVA_Pos      (1UL)
#define R_RIIC_ICBRL_BRL_Msk        (0x1FUL)
#define R_RIIC_ICBRL_BRL_Pos        (0UL)
#define R_RIIC_ICBRH_BRH_Msk        (0x1FUL)
#define R_RIIC_ICBRH_BRH_Pos        (0UL)
#define R_RIIC_ICDRT_DRT_Msk        (0xFFUL)
#define R_RIIC_ICDRT_DRT_Pos        (0UL)
#define R_RIIC_ICDRR_DRR_Msk        (0xFFUL)
#define R_RIIC_ICDRR_DRR_Pos        (0UL)

#define R_RIIC0_ICCR1_SDAI_Msk      R_RIIC_ICCR1_SDAI_Msk
#define R_RIIC0_ICCR1_SDAI_Pos      R_RIIC_ICCR1_SDAI_Pos
#define R_RIIC0_ICCR1_SCLI_Msk      R_RIIC_ICCR1_SCLI_Msk
#define R_RIIC0_ICCR1_SCLI_Pos      R_RIIC_ICCR1_SCLI_Pos
#define R_RIIC0_ICCR1_SDAO_Msk      R_RIIC_ICCR1_SDAO_Msk
#define R_RIIC0_ICCR1_SDAO_Pos      R_RIIC_ICCR1_SDAO_Pos
#define R_RIIC0_ICCR1_SCLO_Msk      R_RIIC_ICCR1_SCLO_Msk
#define R_RIIC0_ICCR1_SCLO_Pos      R_RIIC_ICCR1_SCLO_Pos
#define R_RIIC0_ICCR1_SOWP_Msk      R_RIIC_ICCR1_SOWP_Msk
#define R_RIIC0_ICCR1_SOWP_Pos      R_RIIC_ICCR1_SOWP_Pos
#define R_RIIC0_ICCR1_CLO_Msk       R_RIIC_ICCR1_CLO_Msk
#define R_RIIC0_ICCR1_CLO_Pos       R_RIIC_ICCR1_CLO_Pos
#define R_RIIC0_ICCR1_IICRST_Msk    R_RIIC_ICCR1_IICRST_Msk
#define R_RIIC0_ICCR1_IICRST_Pos    R_RIIC_ICCR1_IICRST_Pos
#define R_RIIC0_ICCR1_ICE_Msk       R_RIIC_ICCR1_ICE_Msk
#define R_RIIC0_ICCR1_ICE_Pos       R_RIIC_ICCR1_ICE_Pos
#define R_RIIC0_ICCR2_ST_Msk        R_RIIC_ICCR2_ST_Msk
#define R_RIIC0_ICCR2_ST_Pos        R_RIIC_ICCR2_ST_Pos
#define R_RIIC0_ICCR2_RS_Msk        R_RIIC_ICCR2_RS_Msk
#define R_RIIC0_ICCR2_RS_Pos        R_RIIC_ICCR2_RS_Pos
#define R_RIIC0_ICCR2_SP_Msk        R_RIIC_ICCR2_SP_Msk
#define R_RIIC0_ICCR2_SP_Pos        R_RIIC_ICCR2_SP_Pos
#define R_RIIC0_ICCR2_TRS_Msk       R_RIIC_ICCR2_TRS_Msk
#define R_RIIC0_ICCR2_TRS_Pos       R_RIIC_ICCR2_TRS_Pos
#define R_RIIC0_ICCR2_MST_Msk       R_RIIC_ICCR2_MST_Msk
#define R_RIIC0_ICCR2_MST_Pos       R_RIIC_ICCR2_MST_Pos
#define R_RIIC0_ICCR2_BBSY_Msk      R_RIIC_ICCR2_BBSY_Msk
#define R_RIIC0_ICCR2_BBSY_Pos      R_RIIC_ICCR2_BBSY_Pos
#define R_RIIC0_ICMR1_BC_Msk        R_RIIC_ICMR1_BC_Msk
#define R_RIIC0_ICMR1_BC_Pos        R_RIIC_ICMR1_BC_Pos
#define R_RIIC0_ICMR1_BCWP_Msk      R_RIIC_ICMR1_BCWP_Msk
#define R_RIIC0_ICMR1_BCWP_Pos      R_RIIC_ICMR1_BCWP_Pos
#define R_RIIC0_ICMR1_CKS_Msk       R_RIIC_ICMR1_CKS_Msk
#define R_RIIC0_ICMR1_CKS_Pos       R_RIIC_ICMR1_CKS_Pos
#define R_RIIC0_ICMR2_TMOS_Msk      R_RIIC_ICMR2_TMOS_Msk
#define R_RIIC0_ICMR2_TMOS_Pos      R_RIIC_ICMR2_TMOS_Pos
#define R_RIIC0_ICMR2_TMOL_Msk      R_RIIC_ICMR2_TMOL_Msk
#define R_RIIC0_ICMR2_TMOL_Pos      R_RIIC_ICMR2_TMOL_Pos
#define R_RIIC0_ICMR2_TMOH_Msk      R_RIIC_ICMR2_TMOH_Msk
#define R_RIIC0_ICMR2_TMOH_Pos      R_RIIC_ICMR2_TMOH_Pos
#define R_RIIC0_ICMR2_SDDL_Msk      R_RIIC_ICMR2_SDDL_Msk
#define R_RIIC0_ICMR2_SDDL_Pos      R_RIIC_ICMR2_SDDL_Pos
#define R_RIIC0_ICMR2_DLCS_Msk      R_RIIC_ICMR2_DLCS_Msk
#define R_RIIC0_ICMR2_DLCS_Pos      R_RIIC_ICMR2_DLCS_Pos
#define R_RIIC0_ICMR3_NF_Msk        R_RIIC_ICMR3_NF_Msk
#define R_RIIC0_ICMR3_NF_Pos        R_RIIC_ICMR3_NF_Pos
#define R_RIIC0_ICMR3_ACKBR_Msk     R_RIIC_ICMR3_ACKBR_Msk
#define R_RIIC0_ICMR3_ACKBR_Pos     R_RIIC_ICMR3_ACKBR_Pos
#define R_RIIC0_ICMR3_ACKBT_Msk     R_RIIC_ICMR3_ACKBT_Msk
#define R_RIIC0_ICMR3_ACKBT_Pos     R_RIIC_ICMR3_ACKBT_Pos
#define R_RIIC0_ICMR3_ACKWP_Msk     R_RIIC_ICMR3_ACKWP_Msk
#define R_RIIC0_ICMR3_ACKWP_Pos     R_RIIC_ICMR3_ACKWP_Pos
#define R_RIIC0_ICMR3_RDRFS_Msk     R_RIIC_ICMR3_RDRFS_Msk
#define R_RIIC0_ICMR3_RDRFS_Pos     R_RIIC_ICMR3_RDRFS_Pos
#define R_RIIC0_ICMR3_WAIT_Msk      R_RIIC_ICMR3_WAIT_Msk
#define R_RIIC0_ICMR3_WAIT_Pos      R_RIIC_ICMR3_WAIT_Pos
#define R_RIIC0_ICMR3_SMBE_Msk      R_RIIC_ICMR3_SMBE_Msk
#define R_RIIC0_ICMR3_SMBE_Pos      R_RIIC_ICMR3_SMBE_Pos
#define R_RIIC0_ICFER_TMOE_Msk      R_RIIC_ICFER_TMOE_Msk
#define R_RIIC0_ICFER_TMOE_Pos      R_RIIC_ICFER_TMOE_Pos
#define R_RIIC0_ICFER_MALE_Msk      R_RIIC_ICFER_MALE_Msk
#define R_RIIC0_ICFER_MALE_Pos      R_RIIC_ICFER_MALE_Pos
#define R_RIIC0_ICFER_NALE_Msk      R_RIIC_ICFER_NALE_Msk
#define R_RIIC0_ICFER_NALE_Pos      R_RIIC_ICFER_NALE_Pos
#define R_RIIC0_ICFER_SALE_Msk      R_RIIC_ICFER_SALE_Msk
#define R_RIIC0_ICFER_SALE_Pos      R_RIIC_ICFER_SALE_Pos
#define R_RIIC0_ICFER_NACKE_Msk     R_RIIC_ICFER_NACKE_Msk
#define R_RIIC0_ICFER_NACKE_Pos     R_RIIC_ICFER_NACKE_Pos
#define R_RIIC0_ICFER_NFE_Msk       R_RIIC_ICFER_NFE_Msk
#define R_RIIC0_ICFER_NFE_Pos       R_RIIC_ICFER_NFE_Pos
#define R_RIIC0_ICFER_SCLE_Msk      R_RIIC_ICFER_SCLE_Msk
#define R_RIIC0_ICFER_SCLE_Pos      R_RIIC_ICFER_SCLE_Pos
#define R_RIIC0_ICFER_FMPE_Msk      R_RIIC_ICFER_FMPE_Msk
#define R_RIIC0_ICFER_FMPE_Pos      R_RIIC_ICFER_FMPE_Pos
#define R_RIIC0_ICSER_SAR0_Msk      R_RIIC_ICSER_SAR0_Msk
#define R_RIIC0_ICSER_SAR0_Pos      R_RIIC_ICSER_SAR0_Pos
#define R_RIIC0_ICSER_SAR1_Msk      R_RIIC_ICSER_SAR1_Msk
#define R_RIIC0_ICSER_SAR1_Pos      R_RIIC_ICSER_SAR1_Pos
#define R_RIIC0_ICSER_SAR2_Msk      R_RIIC_ICSER_SAR2_Msk
#define R_RIIC0_ICSER_SAR2_Pos      R_RIIC_ICSER_SAR2_Pos
#define R_RIIC0_ICSER_GCE_Msk       R_RIIC_ICSER_GCE_Msk
#define R_RIIC0_ICSER_GCE_Pos       R_RIIC_ICSER_GCE_Pos
#define R_RIIC0_ICSER_DIDE_Msk      R_RIIC_ICSER_DIDE_Msk
#define R_RIIC0_ICSER_DIDE_Pos      R_RIIC_ICSER_DIDE_Pos
#define R_RIIC0_ICSER_HOAE_Msk      R_RIIC_ICSER_HOAE_Msk
#define R_RIIC0_ICSER_HOAE_Pos      R_RIIC_ICSER_HOAE_Pos
#define R_RIIC0_ICIER_TMOIE_Msk     R_RIIC_ICIER_TMOIE_Msk
#define R_RIIC0_ICIER_TMOIE_Pos     R_RIIC_ICIER_TMOIE_Pos
#define R_RIIC0_ICIER_ALIE_Msk      R_RIIC_ICIER_ALIE_Msk
#define R_RIIC0_ICIER_ALIE_Pos      R_RIIC_ICIER_ALIE_Pos
#define R_RIIC0_ICIER_STIE_Msk      R_RIIC_ICIER_STIE_Msk
#define R_RIIC0_ICIER_STIE_Pos      R_RIIC_ICIER_STIE_Pos
#define R_RIIC0_ICIER_SPIE_Msk      R_RIIC_ICIER_SPIE_Msk
#define R_RIIC0_ICIER_SPIE_Pos      R_RIIC_ICIER_SPIE_Pos
#define R_RIIC0_ICIER_NAKIE_Msk     R_RIIC_ICIER_NAKIE_Msk
#define R_RIIC0_ICIER_NAKIE_Pos     R_RIIC_ICIER_NAKIE_Pos
#define R_RIIC0_ICIER_RIE_Msk       R_RIIC_ICIER_RIE_Msk
#define R_RIIC0_ICIER_RIE_Pos       R_RIIC_ICIER_RIE_Pos
#define R_RIIC0_ICIER_TEIE_Msk      R_RIIC_ICIER_TEIE_Msk
#define R_RIIC0_ICIER_TEIE_Pos      R_RIIC_ICIER_TEIE_Pos
#define R_RIIC0_ICIER_TIE_Msk       R_RIIC_ICIER_TIE_Msk
#define R_RIIC0_ICIER_TIE_Pos       R_RIIC_ICIER_TIE_Pos
#define R_RIIC0_ICSR1_AAS0_Msk      R_RIIC_ICSR1_AAS0_Msk
#define R_RIIC0_ICSR1_AAS0_Pos      R_RIIC_ICSR1_AAS0_Pos
#define R_RIIC0_ICSR1_AAS1_Msk      R_RIIC_ICSR1_AAS1_Msk
#define R_RIIC0_ICSR1_AAS1_Pos      R_RIIC_ICSR1_AAS1_Pos
#define R_RIIC0_ICSR1_AAS2_Msk      R_RIIC_ICSR1_AAS2_Msk
#define R_RIIC0_ICSR1_AAS2_Pos      R_RIIC_ICSR1_AAS2_Pos
#define R_RIIC0_ICSR1_GCA_Msk       R_RIIC_ICSR1_GCA_Msk
#define R_RIIC0_ICSR1_GCA_Pos       R_RIIC_ICSR1_GCA_Pos
#define R_RIIC0_ICSR1_DID_Msk       R_RIIC_ICSR1_DID_Msk
#define R_RIIC0_ICSR1_DID_Pos       R_RIIC_ICSR1_DID_Pos
#define R_RIIC0_ICSR1_HOA_Msk       R_RIIC_ICSR1_HOA_Msk
#define R_RIIC0_ICSR1_HOA_Pos       R_RIIC_ICSR1_HOA_Pos
#define R_RIIC0_ICSR2_TMOF_Msk      R_RIIC_ICSR2_TMOF_Msk
#define R_RIIC0_ICSR2_TMOF_Pos      R_RIIC_ICSR2_TMOF_Pos
#define R_RIIC0_ICSR2_AL_Msk        R_RIIC_ICSR2_AL_Msk
#define R_RIIC0_ICSR2_AL_Pos        R_RIIC_ICSR2_AL_Pos
#define R_RIIC0_ICSR2_START_Msk     R_RIIC_ICSR2_START_Msk
#define R_RIIC0_ICSR2_START_Pos     R_RIIC_ICSR2_START_Pos
#define R_RIIC0_ICSR2_STOP_Msk      R_RIIC_ICSR2_STOP_Msk
#define R_RIIC0_ICSR2_STOP_Pos      R_RIIC_ICSR2_STOP_Pos
#define R_RIIC0_ICSR2_NACKF_Msk     R_RIIC_ICSR2_NACKF_Msk
#define R_RIIC0_ICSR2_NACKF_Pos     R_RIIC_ICSR2_NACKF_Pos
#define R_RIIC0_ICSR2_RDRF_Msk      R_RIIC_ICSR2_RDRF_Msk
#define R_RIIC0_ICSR2_RDRF_Pos      R_RIIC_ICSR2_RDRF_Pos
#define R_RIIC0_ICSR2_TEND_Msk      R_RIIC_ICSR2_TEND_Msk
#define R_RIIC0_ICSR2_TEND_Pos      R_RIIC_ICSR2_TEND_Pos
#define R_RIIC0_ICSR2_TDRE_Msk      R_RIIC_ICSR2_TDRE_Msk
#define R_RIIC0_ICSR2_TDRE_Pos      R_RIIC_ICSR2_TDRE_Pos
#define R_RIIC0_ICSAR0_SVA0_Msk     R_RIIC_ICSAR0_SVA0_Msk
#define R_RIIC0_ICSAR0_SVA0_Pos     R_RIIC_ICSAR0_SVA0_Pos
#define R_RIIC0_ICSAR0_SVA_Msk      R_RIIC_ICSAR0_SVA_Msk
#define R_RIIC0_ICSAR0_SVA_Pos      R_RIIC_ICSAR0_SVA_Pos
#define R_RIIC0_ICSARU0_FS_Msk      R_RIIC_ICSARU0_FS_Msk
#define R_RIIC0_ICSARU0_FS_Pos      R_RIIC_ICSARU0_FS_Pos
#define R_RIIC0_ICSARU0_SVA_Msk     R_RIIC_ICSARU0_SVA_Msk
#define R_RIIC0_ICSARU0_SVA_Pos     R_RIIC_ICSARU0_SVA_Pos
#define R_RIIC0_ICSAR1_SVA0_Msk     R_RIIC_ICSAR1_SVA0_Msk
#define R_RIIC0_ICSAR1_SVA0_Pos     R_RIIC_ICSAR1_SVA0_Pos
#define R_RIIC0_ICSAR1_SVA_Msk      R_RIIC_ICSAR1_SVA_Msk
#define R_RIIC0_ICSAR1_SVA_Pos      R_RIIC_ICSAR1_SVA_Pos
#define R_RIIC0_ICSARU1_FS_Msk      R_RIIC_ICSARU1_FS_Msk
#define R_RIIC0_ICSARU1_FS_Pos      R_RIIC_ICSARU1_FS_Pos
#define R_RIIC0_ICSARU1_SVA_Msk     R_RIIC_ICSARU1_SVA_Msk
#define R_RIIC0_ICSARU1_SVA_Pos     R_RIIC_ICSARU1_SVA_Pos
#define R_RIIC0_ICSAR2_SVA0_Msk     R_RIIC_ICSAR2_SVA0_Msk
#define R_RIIC0_ICSAR2_SVA0_Pos     R_RIIC_ICSAR2_SVA0_Pos
#define R_RIIC0_ICSAR2_SVA_Msk      R_RIIC_ICSAR2_SVA_Msk
#define R_RIIC0_ICSAR2_SVA_Pos      R_RIIC_ICSAR2_SVA_Pos
#define R_RIIC0_ICSARU2_FS_Msk      R_RIIC_ICSARU2_FS_Msk
#define R_RIIC0_ICSARU2_FS_Pos      R_RIIC_ICSARU2_FS_Pos
#define R_RIIC0_ICSARU2_SVA_Msk     R_RIIC_ICSARU2_SVA_Msk
#define R_RIIC0_ICSARU2_SVA_Pos     R_RIIC_ICSARU2_SVA_Pos
#define R_RIIC0_ICBRL_BRL_Msk       R_RIIC_ICBRL_BRL_Msk
#define R_RIIC0_ICBRL_BRL_Pos       R_RIIC_ICBRL_BRL_Pos
#define R_RIIC0_ICBRH_BRH_Msk       R_RIIC_ICBRH_BRH_Msk
#define R_RIIC0_ICBRH_BRH_Pos       R_RIIC_ICBRH_BRH_Pos
#define R_RIIC0_ICDRT_DRT_Msk       R_RIIC_ICDRT_DRT_Msk
#define R_RIIC0_ICDRT_DRT_Pos       R_RIIC_ICDRT_DRT_Pos
#define R_RIIC0_ICDRR_DRR_Msk       R_RIIC_ICDRR_DRR_Msk
#define R_RIIC0_ICDRR_DRR_Pos       R_RIIC_ICDRR_DRR_Pos

#endif                                 /* RIIC_IOBITMASK_H */
