/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#ifndef BSP_MCU_CPU_MEMORY_CFG_H_
#define BSP_MCU_CPU_MEMORY_CFG_H_
#define BSP_CFG_CPU_MPU_ATTR0_TYPE        (BSP_TYPE_NORMAL_MEMORY)
#define BSP_CFG_CPU_MPU_ATTR0_INNER       (BSP_WRITE_BACK_NON_TRANSIENT)
#define BSP_CFG_CPU_MPU_ATTR0_INNER_READ  (BSP_READ_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR0_INNER_WRITE (BSP_WRITE_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR0_OUTER       (BSP_WRITE_BACK_NON_TRANSIENT)
#define BSP_CFG_CPU_MPU_ATTR0_OUTER_READ  (BSP_READ_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR0_OUTER_WRITE (BSP_WRITE_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR0_DEVICE_TYPE (BSP_DEVICE_NGNRNE)

#define BSP_CFG_CPU_MPU_ATTR1_TYPE        (BSP_TYPE_NORMAL_MEMORY)
#define BSP_CFG_CPU_MPU_ATTR1_INNER       (BSP_WRITE_NON_THROUGH)
#define BSP_CFG_CPU_MPU_ATTR1_INNER_READ  (BSP_READ_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR1_INNER_WRITE (BSP_WRITE_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR1_OUTER       (BSP_WRITE_NON_THROUGH)
#define BSP_CFG_CPU_MPU_ATTR1_OUTER_READ  (BSP_READ_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR1_OUTER_WRITE (BSP_WRITE_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR1_DEVICE_TYPE (BSP_DEVICE_NGNRNE)

#define BSP_CFG_CPU_MPU_ATTR2_TYPE        (BSP_TYPE_NORMAL_MEMORY)
#define BSP_CFG_CPU_MPU_ATTR2_INNER       (BSP_WRITE_NON_THROUGH)
#define BSP_CFG_CPU_MPU_ATTR2_INNER_READ  (BSP_READ_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR2_INNER_WRITE (BSP_WRITE_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR2_OUTER       (BSP_WRITE_NON_THROUGH)
#define BSP_CFG_CPU_MPU_ATTR2_OUTER_READ  (BSP_READ_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR2_OUTER_WRITE (BSP_WRITE_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR2_DEVICE_TYPE (BSP_DEVICE_NGNRNE)

#define BSP_CFG_CPU_MPU_ATTR3_TYPE        (BSP_TYPE_NORMAL_MEMORY)
#define BSP_CFG_CPU_MPU_ATTR3_INNER       (BSP_NON_CACHEABLE)
#define BSP_CFG_CPU_MPU_ATTR3_INNER_READ  (BSP_READ_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR3_INNER_WRITE (BSP_WRITE_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR3_OUTER       (BSP_NON_CACHEABLE)
#define BSP_CFG_CPU_MPU_ATTR3_OUTER_READ  (BSP_READ_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR3_OUTER_WRITE (BSP_WRITE_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR3_DEVICE_TYPE (BSP_DEVICE_NGNRNE)

#define BSP_CFG_CPU_MPU_ATTR4_TYPE        (BSP_TYPE_DEVICE_MEMORY)
#define BSP_CFG_CPU_MPU_ATTR4_INNER       (BSP_WRITE_THROUGH_TRANSIENT)
#define BSP_CFG_CPU_MPU_ATTR4_INNER_READ  (BSP_READ_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR4_INNER_WRITE (BSP_WRITE_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR4_OUTER       (BSP_WRITE_THROUGH_TRANSIENT)
#define BSP_CFG_CPU_MPU_ATTR4_OUTER_READ  (BSP_READ_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR4_OUTER_WRITE (BSP_WRITE_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR4_DEVICE_TYPE (BSP_DEVICE_NGNRNE)

#define BSP_CFG_CPU_MPU_ATTR5_TYPE        (BSP_TYPE_DEVICE_MEMORY)
#define BSP_CFG_CPU_MPU_ATTR5_INNER       (BSP_WRITE_THROUGH_TRANSIENT)
#define BSP_CFG_CPU_MPU_ATTR5_INNER_READ  (BSP_READ_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR5_INNER_WRITE (BSP_WRITE_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR5_OUTER       (BSP_WRITE_THROUGH_TRANSIENT)
#define BSP_CFG_CPU_MPU_ATTR5_OUTER_READ  (BSP_READ_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR5_OUTER_WRITE (BSP_WRITE_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR5_DEVICE_TYPE (BSP_DEVICE_NGNRE)

#define BSP_CFG_CPU_MPU_ATTR6_TYPE        (BSP_TYPE_DEVICE_MEMORY)
#define BSP_CFG_CPU_MPU_ATTR6_INNER       (BSP_WRITE_THROUGH_TRANSIENT)
#define BSP_CFG_CPU_MPU_ATTR6_INNER_READ  (BSP_READ_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR6_INNER_WRITE (BSP_WRITE_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR6_OUTER       (BSP_WRITE_THROUGH_TRANSIENT)
#define BSP_CFG_CPU_MPU_ATTR6_OUTER_READ  (BSP_READ_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR6_OUTER_WRITE (BSP_WRITE_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR6_DEVICE_TYPE (BSP_DEVICE_NGRE)

#define BSP_CFG_CPU_MPU_ATTR7_TYPE        (BSP_TYPE_DEVICE_MEMORY)
#define BSP_CFG_CPU_MPU_ATTR7_INNER       (BSP_WRITE_THROUGH_TRANSIENT)
#define BSP_CFG_CPU_MPU_ATTR7_INNER_READ  (BSP_READ_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR7_INNER_WRITE (BSP_WRITE_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR7_OUTER       (BSP_WRITE_THROUGH_TRANSIENT)
#define BSP_CFG_CPU_MPU_ATTR7_OUTER_READ  (BSP_READ_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR7_OUTER_WRITE (BSP_WRITE_NOT_ALLOCATE)
#define BSP_CFG_CPU_MPU_ATTR7_DEVICE_TYPE (BSP_DEVICE_GRE)

/* Region00 : ATCM */
#define BSP_CFG_EL1_MPU_REGION00_BASE      (0x00000000)
#define BSP_CFG_EL1_MPU_REGION00_LIMIT     (0x0007FFFF)
#define BSP_CFG_EL1_MPU_REGION00_SH        (BSP_OUTER_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION00_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION00_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION00_ATTRINDEX (BSP_ATTRINDEX3)
#define BSP_CFG_EL1_MPU_REGION00_ENABLE    (BSP_REGION_ENABLE)

/* Region01 : BTCM */
#define BSP_CFG_EL1_MPU_REGION01_BASE      (0x00100000)
#define BSP_CFG_EL1_MPU_REGION01_LIMIT     (0x0010FFFF)
#define BSP_CFG_EL1_MPU_REGION01_SH        (BSP_OUTER_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION01_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION01_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION01_ATTRINDEX (BSP_ATTRINDEX3)
#define BSP_CFG_EL1_MPU_REGION01_ENABLE    (BSP_REGION_ENABLE)

/* Region02 : System SRAM(Cache area) */
#define BSP_CFG_EL1_MPU_REGION02_BASE      (0x10000000)
#define BSP_CFG_EL1_MPU_REGION02_LIMIT     (0x100FFFFF)
#define BSP_CFG_EL1_MPU_REGION02_SH        (BSP_NON_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION02_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION02_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION02_ATTRINDEX (BSP_ATTRINDEX1)
#define BSP_CFG_EL1_MPU_REGION02_ENABLE    (BSP_REGION_ENABLE)

/* Region03 : System SRAM(Non-cache area) */
#define BSP_CFG_EL1_MPU_REGION03_BASE      (0x10100000)
#define BSP_CFG_EL1_MPU_REGION03_LIMIT     (0x101FFFFF)
#define BSP_CFG_EL1_MPU_REGION03_SH        (BSP_OUTER_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION03_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION03_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION03_ATTRINDEX (BSP_ATTRINDEX3)
#define BSP_CFG_EL1_MPU_REGION03_ENABLE    (BSP_REGION_ENABLE)

/* Region04 : Cortex-R52 CPU1 ATCM via AXIS */
#define BSP_CFG_EL1_MPU_REGION04_BASE      (0x21000000)
#define BSP_CFG_EL1_MPU_REGION04_LIMIT     (0x2107FFFF)
#define BSP_CFG_EL1_MPU_REGION04_SH        (BSP_OUTER_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION04_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION04_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION04_ATTRINDEX (BSP_ATTRINDEX4)
#define BSP_CFG_EL1_MPU_REGION04_ENABLE    (BSP_REGION_ENABLE)

/* Region05 : Cortex-R52 CPU1 BTCM via AXIS */
#define BSP_CFG_EL1_MPU_REGION05_BASE      (0x21100000)
#define BSP_CFG_EL1_MPU_REGION05_LIMIT     (0x2110FFFF)
#define BSP_CFG_EL1_MPU_REGION05_SH        (BSP_OUTER_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION05_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION05_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION05_ATTRINDEX (BSP_ATTRINDEX4)
#define BSP_CFG_EL1_MPU_REGION05_ENABLE    (BSP_REGION_ENABLE)

/* Region06 : External address space xSPI */
#define BSP_CFG_EL1_MPU_REGION06_BASE      (0x40000000)
#define BSP_CFG_EL1_MPU_REGION06_LIMIT     (0x5FFFFFFF)
#define BSP_CFG_EL1_MPU_REGION06_SH        (BSP_OUTER_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION06_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION06_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION06_ATTRINDEX (BSP_ATTRINDEX3)
#define BSP_CFG_EL1_MPU_REGION06_ENABLE    (BSP_REGION_ENABLE)

/* Region07 : External address space CS */
#define BSP_CFG_EL1_MPU_REGION07_BASE      (0x70000000)
#define BSP_CFG_EL1_MPU_REGION07_LIMIT     (0x7FFFFFFF)
#define BSP_CFG_EL1_MPU_REGION07_SH        (BSP_OUTER_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION07_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION07_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION07_ATTRINDEX (BSP_ATTRINDEX3)
#define BSP_CFG_EL1_MPU_REGION07_ENABLE    (BSP_REGION_ENABLE)

/* Region08 : R-Bus Non-Safety/Safety Peripheral */
#define BSP_CFG_EL1_MPU_REGION08_BASE      (0x80000000)
#define BSP_CFG_EL1_MPU_REGION08_LIMIT     (0x81FFFFFF)
#define BSP_CFG_EL1_MPU_REGION08_SH        (BSP_OUTER_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION08_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION08_XN        (BSP_EXECUTE_NEVER)
#define BSP_CFG_EL1_MPU_REGION08_ATTRINDEX (BSP_ATTRINDEX5)
#define BSP_CFG_EL1_MPU_REGION08_ENABLE    (BSP_REGION_ENABLE)

/* Region09 : R-Bus Non-Safety Peripheral 1 */
#define BSP_CFG_EL1_MPU_REGION09_BASE      (0x88000000)
#define BSP_CFG_EL1_MPU_REGION09_LIMIT     (0x89FFFFFF)
#define BSP_CFG_EL1_MPU_REGION09_SH        (BSP_OUTER_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION09_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION09_XN        (BSP_EXECUTE_NEVER)
#define BSP_CFG_EL1_MPU_REGION09_ATTRINDEX (BSP_ATTRINDEX5)
#define BSP_CFG_EL1_MPU_REGION09_ENABLE    (BSP_REGION_ENABLE)

/* Region10 : Debug Private */
#define BSP_CFG_EL1_MPU_REGION10_BASE      (0x8C000000)
#define BSP_CFG_EL1_MPU_REGION10_LIMIT     (0x8CFFFFFF)
#define BSP_CFG_EL1_MPU_REGION10_SH        (BSP_OUTER_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION10_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION10_XN        (BSP_EXECUTE_NEVER)
#define BSP_CFG_EL1_MPU_REGION10_ATTRINDEX (BSP_ATTRINDEX4)
#define BSP_CFG_EL1_MPU_REGION10_ENABLE    (BSP_REGION_ENABLE)

/* Region11 : LLPP Peripheral */
#define BSP_CFG_EL1_MPU_REGION11_BASE      (0x90000000)
#define BSP_CFG_EL1_MPU_REGION11_LIMIT     (0x903FFFFF)
#define BSP_CFG_EL1_MPU_REGION11_SH        (BSP_OUTER_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION11_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION11_XN        (BSP_EXECUTE_NEVER)
#define BSP_CFG_EL1_MPU_REGION11_ATTRINDEX (BSP_ATTRINDEX5)
#define BSP_CFG_EL1_MPU_REGION11_ENABLE    (BSP_REGION_ENABLE)

/* Region12 : A-Bus Peripheral */
#define BSP_CFG_EL1_MPU_REGION12_BASE      (0x92000000)
#define BSP_CFG_EL1_MPU_REGION12_LIMIT     (0x92FFFFFF)
#define BSP_CFG_EL1_MPU_REGION12_SH        (BSP_OUTER_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION12_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION12_XN        (BSP_EXECUTE_NEVER)
#define BSP_CFG_EL1_MPU_REGION12_ATTRINDEX (BSP_ATTRINDEX5)
#define BSP_CFG_EL1_MPU_REGION12_ENABLE    (BSP_REGION_ENABLE)

/* Region13 : Cortex-R52 CPU0 GIC */
#define BSP_CFG_EL1_MPU_REGION13_BASE      (0x94000000)
#define BSP_CFG_EL1_MPU_REGION13_LIMIT     (0x941FFFFF)
#define BSP_CFG_EL1_MPU_REGION13_SH        (BSP_OUTER_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION13_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION13_XN        (BSP_EXECUTE_NEVER)
#define BSP_CFG_EL1_MPU_REGION13_ATTRINDEX (BSP_ATTRINDEX4)
#define BSP_CFG_EL1_MPU_REGION13_ENABLE    (BSP_REGION_ENABLE)

/* Region14 : PCIE mirror */
#define BSP_CFG_EL1_MPU_REGION14_BASE      (0xA0000000)
#define BSP_CFG_EL1_MPU_REGION14_LIMIT     (0xBFFFFFFF)
#define BSP_CFG_EL1_MPU_REGION14_SH        (BSP_OUTER_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION14_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION14_XN        (BSP_EXECUTE_NEVER)
#define BSP_CFG_EL1_MPU_REGION14_ATTRINDEX (BSP_ATTRINDEX5)
#define BSP_CFG_EL1_MPU_REGION14_ENABLE    (BSP_REGION_ENABLE)

/* Region15 : DDR mirror */
#define BSP_CFG_EL1_MPU_REGION15_BASE      (0xC0000000)
#define BSP_CFG_EL1_MPU_REGION15_LIMIT     (0xFFFFFFFF)
#define BSP_CFG_EL1_MPU_REGION15_SH        (BSP_NON_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION15_AP        (BSP_EL1RW_EL0RW)
#define BSP_CFG_EL1_MPU_REGION15_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION15_ATTRINDEX (BSP_ATTRINDEX1)
#define BSP_CFG_EL1_MPU_REGION15_ENABLE    (BSP_REGION_ENABLE)

/* Region16 : Not Used */
#define BSP_CFG_EL1_MPU_REGION16_BASE      (0x00000000)
#define BSP_CFG_EL1_MPU_REGION16_LIMIT     (0x00000000)
#define BSP_CFG_EL1_MPU_REGION16_SH        (BSP_NON_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION16_AP        (BSP_EL1RW_EL0NO)
#define BSP_CFG_EL1_MPU_REGION16_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION16_ATTRINDEX (BSP_ATTRINDEX0)
#define BSP_CFG_EL1_MPU_REGION16_ENABLE    (BSP_REGION_DISABLE)

/* Region17 : Not Used */
#define BSP_CFG_EL1_MPU_REGION17_BASE      (0x00000000)
#define BSP_CFG_EL1_MPU_REGION17_LIMIT     (0x00000000)
#define BSP_CFG_EL1_MPU_REGION17_SH        (BSP_NON_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION17_AP        (BSP_EL1RW_EL0NO)
#define BSP_CFG_EL1_MPU_REGION17_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION17_ATTRINDEX (BSP_ATTRINDEX0)
#define BSP_CFG_EL1_MPU_REGION17_ENABLE    (BSP_REGION_DISABLE)

/* Region18 : Not Used */
#define BSP_CFG_EL1_MPU_REGION18_BASE      (0x00000000)
#define BSP_CFG_EL1_MPU_REGION18_LIMIT     (0x00000000)
#define BSP_CFG_EL1_MPU_REGION18_SH        (BSP_NON_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION18_AP        (BSP_EL1RW_EL0NO)
#define BSP_CFG_EL1_MPU_REGION18_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION18_ATTRINDEX (BSP_ATTRINDEX0)
#define BSP_CFG_EL1_MPU_REGION18_ENABLE    (BSP_REGION_DISABLE)

/* Region19 : Not Used */
#define BSP_CFG_EL1_MPU_REGION19_BASE      (0x00000000)
#define BSP_CFG_EL1_MPU_REGION19_LIMIT     (0x00000000)
#define BSP_CFG_EL1_MPU_REGION19_SH        (BSP_NON_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION19_AP        (BSP_EL1RW_EL0NO)
#define BSP_CFG_EL1_MPU_REGION19_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION19_ATTRINDEX (BSP_ATTRINDEX0)
#define BSP_CFG_EL1_MPU_REGION19_ENABLE    (BSP_REGION_DISABLE)

/* Region20 : Not Used */
#define BSP_CFG_EL1_MPU_REGION20_BASE      (0x00000000)
#define BSP_CFG_EL1_MPU_REGION20_LIMIT     (0x00000000)
#define BSP_CFG_EL1_MPU_REGION20_SH        (BSP_NON_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION20_AP        (BSP_EL1RW_EL0NO)
#define BSP_CFG_EL1_MPU_REGION20_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION20_ATTRINDEX (BSP_ATTRINDEX0)
#define BSP_CFG_EL1_MPU_REGION20_ENABLE    (BSP_REGION_DISABLE)

/* Region21 : Not Used */
#define BSP_CFG_EL1_MPU_REGION21_BASE      (0x00000000)
#define BSP_CFG_EL1_MPU_REGION21_LIMIT     (0x00000000)
#define BSP_CFG_EL1_MPU_REGION21_SH        (BSP_NON_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION21_AP        (BSP_EL1RW_EL0NO)
#define BSP_CFG_EL1_MPU_REGION21_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION21_ATTRINDEX (BSP_ATTRINDEX0)
#define BSP_CFG_EL1_MPU_REGION21_ENABLE    (BSP_REGION_DISABLE)

/* Region22 : Not Used */
#define BSP_CFG_EL1_MPU_REGION22_BASE      (0x00000000)
#define BSP_CFG_EL1_MPU_REGION22_LIMIT     (0x00000000)
#define BSP_CFG_EL1_MPU_REGION22_SH        (BSP_NON_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION22_AP        (BSP_EL1RW_EL0NO)
#define BSP_CFG_EL1_MPU_REGION22_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION22_ATTRINDEX (BSP_ATTRINDEX0)
#define BSP_CFG_EL1_MPU_REGION22_ENABLE    (BSP_REGION_DISABLE)

/* Region23 : Not Used */
#define BSP_CFG_EL1_MPU_REGION23_BASE      (0x00000000)
#define BSP_CFG_EL1_MPU_REGION23_LIMIT     (0x00000000)
#define BSP_CFG_EL1_MPU_REGION23_SH        (BSP_NON_SHAREABLE)
#define BSP_CFG_EL1_MPU_REGION23_AP        (BSP_EL1RW_EL0NO)
#define BSP_CFG_EL1_MPU_REGION23_XN        (BSP_EXECUTE_ENABLE)
#define BSP_CFG_EL1_MPU_REGION23_ATTRINDEX (BSP_ATTRINDEX0)
#define BSP_CFG_EL1_MPU_REGION23_ENABLE    (BSP_REGION_DISABLE)

#define BSP_CFG_SCTLR_BR_BIT               (BSP_BG_REGION_DISABLE)
#define BSP_CFG_SCTLR_I_BIT                (BSP_ICACHE_ENABLE)
#define BSP_CFG_SCTLR_C_BIT                (BSP_DATACACHE_ENABLE)
#endif /* BSP_MCU_CPU_MEMORY_CFG_H_ */
