/*
 * Copyright (c) 2020, Renesas Electronics Corporation. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _OCTA_REG_H_
#define _OCTA_REG_H_

#define OCTA_DCR	0x0000	/* Device command register */
#define OCTA_DAR	0x0004	/* Device address register */
#define OCTA_DCSR	0x0008	/* Device command setting register */
#define OCTA_DSR0	0x000C	/* Device size register 0 */
#define OCTA_DSR1	0x0010	/* Device size register 1 */
#define OCTA_MDTR	0x0014	/* Memory delay trim register */
#define OCTA_ACTR	0x0018	/* Auto-calibration timer register */
#define OCTA_ACAR0	0x001C	/* Auto-calibration address register 0 */
#define OCTA_ACAR1	0x0020	/* Auto-calibration address register 1 */
#define OCTA_DRCSTR	0x0034	/* Device memory map read chip select timing setting register */
#define OCTA_DWCSTR	0x0038	/* Device memory map write chip select timing setting register */
#define OCTA_DCSTR	0x003C	/* Device chip select timing setting register */
#define OCTA_CDSR	0x0040	/* Controller and device setting register */
#define OCTA_MDLR	0x0044	/* Memory map dummy length register */
#define OCTA_MRWCR0	0x0048	/* Memory map read/write command register 0 */
#define OCTA_MRWCR1	0x004C	/* Memory map read/write command register 1 */
#define OCTA_MRWCSR	0x0050	/* Memory map read/write setting register */
#define OCTA_ESR	0x0054	/* Error status register */
#define OCTA_CWNDR	0x0058	/* Configure write without data register */
#define OCTA_CWDR	0x005C	/* Configure write data register */
#define OCTA_CRR	0x0060	/* Configure read register */
#define OCTA_RSTCNT	0x0080	/* Device reset register */
#define OCTA_AER	0x0084	/* Address extend register */

/* DCR field */
#define OCTA_DCR_DVCMD1_POS		(8UL)
#define OCTA_DCR_DVCMD1			(0xFFUL << OCTA_DCR_DVCMD1_POS)
#define OCTA_DCR_DVCMD0_POS		(0UL)
#define OCTA_DCR_DVCMD0			(0xFFUL << OCTA_DCR_DVCMD0_POS)

/* DAR field */
#define OCTA_DAR_DVAD3_POS		(24UL)
#define OCTA_DAR_DVAD3			(0xFFUL << OCTA_DAR_DVAD3_POS)
#define OCTA_DAR_DVAD2_POS		(16UL)
#define OCTA_DAR_DVAD2			(0xFFUL << OCTA_DAR_DVAD2_POS)
#define OCTA_DAR_DVAD1_POS		(8UL)
#define OCTA_DAR_DVAD1			(0xFFUL << OCTA_DAR_DVAD1_POS)
#define OCTA_DAR_DVAD0_POS		(0UL)
#define OCTA_DAR_DVAD0			(0xFFUL << OCTA_DAR_DVAD0_POS)

/* DCSR field */
#define OCTA_DCSR_ACDA_POS		(28UL)
#define OCTA_DCSR_ACDA			(0x1UL << OCTA_DCSR_ACDA_POS)
#define OCTA_DCSR_DOPI_POS		(27UL)
#define OCTA_DCSR_DOPI			(0x1UL << OCTA_DCSR_DOPI_POS)
#define OCTA_DCSR_ADLEN_POS		(24UL)
#define OCTA_DCSR_ADLEN			(0x7UL << OCTA_DCSR_ADLEN_POS)
#define OCTA_DCSR_DAOR_POS		(23UL)
#define OCTA_DCSR_DAOR			(0x1UL << OCTA_DCSR_DAOR_POS)
#define OCTA_DCSR_CMDLEN_POS		(20UL)
#define OCTA_DCSR_CMDLEN		(0x7UL << OCTA_DCSR_CMDLEN_POS)
#define OCTA_DCSR_ACDV_POS		(19UL)
#define OCTA_DCSR_ACDV			(0x1UL << OCTA_DCSR_ACDV_POS)
#define OCTA_DCSR_DMLEN_POS		(8UL)
#define OCTA_DCSR_DMLEN			(0xFFUL << OCTA_DCSR_DMLEN_POS)
#define OCTA_DCSR_DALEN_POS		(0UL)
#define OCTA_DCSR_DALEN			(0xFFUL << OCTA_DCSR_DALEN_POS)

/* DSR0 field */
#define OCTA_DSR0_DV0TYP_POS		(30UL)
#define OCTA_DSR0_DV0TYP		(0x3UL << OCTA_DSR0_DV0TYP_POS)
#define OCTA_DSR0_DV0SZ_POS		(0UL)
#define OCTA_DSR0_DV0SZ			(0x3FFFFFFFUL << OCTA_DSR0_DV0SZ_POS)
#define OCTA_DSR_TYP_FLASH		0u
#define OCTA_DSR_TYP_RAM		1u
#define OCTA_DSR_TYP_NONE		2u

/* DSR1 field */
#define OCTA_DSR1_DV1TYP_POS		(30UL)
#define OCTA_DSR1_DV1TYP		(0x3UL << OCTA_DSR1_DV1TYP_POS)
#define OCTA_DSR1_DV1SZ_POS		(0UL)
#define OCTA_DSR1_DV1SZ			(0x3FFFFFFFUL << OCTA_DSR1_DV1SZ_POS)

/* MDTR field */
#define OCTA_MDTR_DQSEDOPI_POS		(24UL)
#define OCTA_MDTR_DQSEDOPI		(0xFUL << OCTA_MDTR_DQSEDOPI_POS)
#define OCTA_MDTR_DV1DEL_POS		(16UL)
#define OCTA_MDTR_DV1DEL		(0xFFUL << OCTA_MDTR_DV1DEL_POS)
#define OCTA_MDTR_DQSESOPI_POS		(12UL)
#define OCTA_MDTR_DQSESOPI		(0xFUL << OCTA_MDTR_DQSESOPI_POS)
#define OCTA_MDTR_DQSERAM_POS		(8UL)
#define OCTA_MDTR_DQSERAM		(0xFUL << OCTA_MDTR_DQSERAM_POS)
#define OCTA_MDTR_DV0DEL_POS		(0UL)
#define OCTA_MDTR_DV0DEL		(0xFFUL << OCTA_MDTR_DV0DEL_POS)

/* ACTR field */
#define OCTA_ACTR_CTP_POS		(0UL)
#define OCTA_ACTR_CTP			(0xFFFFFFFFUL << OCTA_ACTR_CTP_POS)

/* ACAR0 field */
#define OCTA_ACAR0_CAD0_POS		(0UL)
#define OCTA_ACAR0_CAD0			(0xFFFFFFFFUL << OCTA_ACAR0_CAD0_POS)

/* ACAR1 field */
#define OCTA_ACAR1_CAD1_POS		(0UL)
#define OCTA_ACAR1_CAD1			(0xFFFFFFFFUL << OCTA_ACAR1_CAD1_POS)

/* DRCSTR field */
#define OCTA_DRCSTR_DVRDLO1_POS		(30UL)
#define OCTA_DRCSTR_DVRDLO1		(0x3UL << OCTA_DRCSTR_DVRDLO1_POS)
#define OCTA_DRCSTR_DVRDHI1_POS		(27UL)
#define OCTA_DRCSTR_DVRDHI1		(0x7UL << OCTA_DRCSTR_DVRDHI1_POS)
#define OCTA_DRCSTR_DVRDCMD1_POS	(24UL)
#define OCTA_DRCSTR_DVRDCMD1		(0x7UL << OCTA_DRCSTR_DVRDCMD1_POS)
/* CTR1 and CTRW1 are not available in RZ */
#define OCTA_DRCSTR_CTR1_POS		(23UL)
#define OCTA_DRCSTR_CTR1		(0x1UL << OCTA_DRCSTR_CTR1_POS)
#define OCTA_DRCSTR_CTRW1_POS		(16UL)
#define OCTA_DRCSTR_CTRW1		(0x7FUL << OCTA_DRCSTR_CTRW1_POS)
#define OCTA_DRCSTR_DVRDLO0_POS		(14UL)
#define OCTA_DRCSTR_DVRDLO0		(0x3UL << OCTA_DRCSTR_DVRDLO0_POS)
#define OCTA_DRCSTR_DVRDHI0_POS		(11UL)
#define OCTA_DRCSTR_DVRDHI0		(0x7UL << OCTA_DRCSTR_DVRDHI0_POS)
#define OCTA_DRCSTR_DVRDCMD0_POS	(8UL)
#define OCTA_DRCSTR_DVRDCMD0		(0x7UL << OCTA_DRCSTR_DVRDCMD0_POS)
#define OCTA_DRCSTR_CTR0_POS		(7UL)
#define OCTA_DRCSTR_CTR0		(0x1UL << OCTA_DRCSTR_CTR0_POS)
#define OCTA_DRCSTR_CTRW0_POS		(0UL)
#define OCTA_DRCSTR_CTRW0		(0x7FUL << OCTA_DRCSTR_CTRW0_POS)

/* DWCSTR field */
#define OCTA_DWCSTR_DVWLO1_POS		(30UL)
#define OCTA_DWCSTR_DVWLO1		(0x3UL << OCTA_DWCSTR_DVWLO1_POS)
#define OCTA_DWCSTR_DVWHI1_POS		(27UL)
#define OCTA_DWCSTR_DVWHI1		(0x7UL << OCTA_DWCSTR_DVWHI1_POS)
#define OCTA_DWCSTR_DVWCMD1_POS		(24UL)
#define OCTA_DWCSTR_DVWCMD1		(0x7UL << OCTA_DWCSTR_DVWCMD1_POS)
/* CTW1 and CTWW1 are not available in RZ */
#define OCTA_DWCSTR_CTW1_POS		(23UL)
#define OCTA_DWCSTR_CTW1		(0x1UL << OCTA_DWCSTR_CTW1_POS)
#define OCTA_DWCSTR_CTWW1_POS		(16UL)
#define OCTA_DWCSTR_CTWW1		(0x7FUL << OCTA_DWCSTR_CTWW1_POS)
#define OCTA_DWCSTR_DVWLO0_POS		(14UL)
#define OCTA_DWCSTR_DVWLO0		(0x3UL << OCTA_DWCSTR_DVWLO0_POS)
#define OCTA_DWCSTR_DVWHI0_POS		(11UL)
#define OCTA_DWCSTR_DVWHI0		(0x7UL << OCTA_DWCSTR_DVWHI0_POS)
#define OCTA_DWCSTR_DVWCMD0_POS		(8UL)
#define OCTA_DWCSTR_DVWCMD0		(0x7UL << OCTA_DWCSTR_DVWCMD0_POS)
/* CTW0 and CTWW0 are not available in RZ */
#define OCTA_DWCSTR_CTW0_POS		(7UL)
#define OCTA_DWCSTR_CTW0		(0x1UL << OCTA_DWCSTR_CTW0_POS)
#define OCTA_DWCSTR_CTWW0_POS		(0UL)
#define OCTA_DWCSTR_CTWW0		(0x7FUL << OCTA_DWCSTR_CTWW0_POS)

/* DCSTR field */
#define OCTA_DCSTR_DVSELLO_POS		(14UL)
#define OCTA_DCSTR_DVSELLO		(0x3UL << OCTA_DCSTR_DVSELLO_POS)
#define OCTA_DCSTR_DVSELHI_POS		(11UL)
#define OCTA_DCSTR_DVSELHI		(0x7UL << OCTA_DCSTR_DVSELHI_POS)
#define OCTA_DCSTR_DVSELCMD_POS		(8UL)
#define OCTA_DCSTR_DVSELCMD		(0x7UL << OCTA_DCSTR_DVSELCMD_POS)

/* CDSR field */
#define OCTA_CDSR_DLFT_POS		(31UL)
#define OCTA_CDSR_DLFT			(0x1UL << OCTA_CDSR_DLFT_POS)
#define OCTA_CDSR_ACMODE_POS		(12UL)
#define OCTA_CDSR_ACMODE		(0x3UL << OCTA_CDSR_ACMODE_POS)
#define OCTA_CDSR_ACMODE_DISABLE	0u
#define OCTA_CDSR_ACMODE_ENABLE		1u
#define OCTA_CDSR_ACMEME1_POS		(11UL)
#define OCTA_CDSR_ACMEME1		(0x1UL << OCTA_CDSR_ACMEME1_POS)
#define OCTA_CDSR_ACMEME0_POS		(10UL)
#define OCTA_CDSR_ACMEME0		(0x1UL << OCTA_CDSR_ACMEME0_POS)
#define OCTA_CDSR_DV1PC_POS		(5UL)
#define OCTA_CDSR_DV1PC			(0x1UL << OCTA_CDSR_DV1PC_POS)
#define OCTA_CDSR_DV0PC_POS		(4UL)
#define OCTA_CDSR_DV0PC			(0x1UL << OCTA_CDSR_DV0PC_POS)
#define OCTA_CDSR_DV1TTYP_POS		(2UL)
#define OCTA_CDSR_DV1TTYP		(0x3UL << OCTA_CDSR_DV1TTYP_POS)
#define OCTA_CDSR_DV0TTYP_POS		(0UL)
#define OCTA_CDSR_DV0TTYP		(0x3UL << OCTA_CDSR_DV0TTYP_POS)
#define OCTA_CDSR_DVTTYP_SPI		0u
#define OCTA_CDSR_DVTTYP_SOPI		1u
#define OCTA_CDSR_DVTTYP_DOPI		2u

/* MDLR field */
#define OCTA_MDLR_DV1WDL_POS		(24UL)
#define OCTA_MDLR_DV1WDL		(0xFFUL << OCTA_MDLR_DV1WDL_POS)
#define OCTA_MDLR_DV1RDL_POS		(16UL)
#define OCTA_MDLR_DV1RDL		(0xFFUL << OCTA_MDLR_DV1RDL_POS)
#define OCTA_MDLR_DV0WDL_POS		(8UL)
#define OCTA_MDLR_DV0WDL		(0xFFUL << OCTA_MDLR_DV0WDL_POS)
#define OCTA_MDLR_DV0RDL_POS		(0UL)
#define OCTA_MDLR_DV0RDL		(0xFFUL << OCTA_MDLR_DV0RDL_POS)

/* MRWCR0 field */
#define OCTA_MRWCR0_D0MWCMD1_POS	(24UL)
#define OCTA_MRWCR0_D0MWCMD1		(0xFFUL << OCTA_MRWCR0_D0MWCMD1_POS)
#define OCTA_MRWCR0_D0MWCMD0_POS	(16UL)
#define OCTA_MRWCR0_D0MWCMD0		(0xFFUL << OCTA_MRWCR0_D0MWCMD0_POS)
#define OCTA_MRWCR0_D0MRCMD1_POS	(8UL)
#define OCTA_MRWCR0_D0MRCMD1		(0xFFUL << OCTA_MRWCR0_D0MRCMD1_POS)
#define OCTA_MRWCR0_D0MRCMD0_POS	(0UL)
#define OCTA_MRWCR0_D0MRCMD0		(0xFFUL << OCTA_MRWCR0_D0MRCMD0_POS)

/* MRWCR1 field */
#define OCTA_MRWCR1_D1MWCMD1_POS	(24UL)
#define OCTA_MRWCR1_D1MWCMD1		(0xFFUL << OCTA_MRWCR1_D1MWCMD1_POS)
#define OCTA_MRWCR1_D1MWCMD0_POS	(16UL)
#define OCTA_MRWCR1_D1MWCMD0		(0xFFUL << OCTA_MRWCR1_D1MWCMD0_POS)
#define OCTA_MRWCR1_D1MRCMD1_POS	(8UL)
#define OCTA_MRWCR1_D1MRCMD1		(0xFFUL << OCTA_MRWCR1_D1MRCMD1_POS)
#define OCTA_MRWCR1_D1MRCMD0_POS	(0UL)
#define OCTA_MRWCR1_D1MRCMD0		(0xFFUL << OCTA_MRWCR1_D1MRCMD0_POS)

/* MRWCSR field */
#define OCTA_MRWCSR_MWO1_POS		(30UL)
#define OCTA_MRWCSR_MWO1		(0x1UL << OCTA_MRWCSR_MWO1_POS)
#define OCTA_MRWCSR_MWCL1_POS		(27UL)
#define OCTA_MRWCSR_MWCL1		(0x7UL << OCTA_MRWCSR_MWCL1_POS)
#define OCTA_MRWCSR_MWAL1_POS		(24UL)
#define OCTA_MRWCSR_MWAL1		(0x7UL << OCTA_MRWCSR_MWAL1_POS)
#define OCTA_MRWCSR_MRO1_POS		(22UL)
#define OCTA_MRWCSR_MRO1		(0x1UL << OCTA_MRWCSR_MRO1_POS)
#define OCTA_MRWCSR_MRCL1_POS		(19UL)
#define OCTA_MRWCSR_MRCL1		(0x7UL << OCTA_MRWCSR_MRCL1_POS)
#define OCTA_MRWCSR_MRAL1_POS		(16UL)
#define OCTA_MRWCSR_MRAL1		(0x7UL << OCTA_MRWCSR_MRAL1_POS)
#define OCTA_MRWCSR_MWO0_POS		(14UL)
#define OCTA_MRWCSR_MWO0		(0x1UL << OCTA_MRWCSR_MWO0_POS)
#define OCTA_MRWCSR_MWCL0_POS		(11UL)
#define OCTA_MRWCSR_MWCL0		(0x7UL << OCTA_MRWCSR_MWCL0_POS)
#define OCTA_MRWCSR_MWAL0_POS		(8UL)
#define OCTA_MRWCSR_MWAL0		(0x7UL << OCTA_MRWCSR_MWAL0_POS)
#define OCTA_MRWCSR_MRO0_POS		(6UL)
#define OCTA_MRWCSR_MRO0		(0x1UL << OCTA_MRWCSR_MRO0_POS)
#define OCTA_MRWCSR_MRCL0_POS		(3UL)
#define OCTA_MRWCSR_MRCL0		(0x7UL << OCTA_MRWCSR_MRCL0_POS)
#define OCTA_MRWCSR_MRAL0_POS		(0UL)
#define OCTA_MRWCSR_MRAL0		(0x7UL << OCTA_MRWCSR_MRAL0_POS)

/* ESR field */
#define OCTA_ESR_MWESR_POS		(8UL)
#define OCTA_ESR_MWESR			(0xFFUL << OCTA_ESR_MWESR_POS)
#define OCTA_ESR_MRESR_POS		(0UL)
#define OCTA_ESR_MRESR			(0xFFUL << OCTA_ESR_MRESR_POS)

/* CWDR field */
#define OCTA_CWDR_WD3_POS		(24UL)
#define OCTA_CWDR_WD3			(0xFFUL << OCTA_CWDR_WD3_POS)
#define OCTA_CWDR_WD2_POS		(16UL)
#define OCTA_CWDR_WD2			(0xFFUL << OCTA_CWDR_WD2_POS)
#define OCTA_CWDR_WD1_POS		(8UL)
#define OCTA_CWDR_WD1			(0xFFUL << OCTA_CWDR_WD1_POS)
#define OCTA_CWDR_WD0_POS		(0UL)
#define OCTA_CWDR_WD0			(0xFFUL << OCTA_CWDR_WD0_POS)

/* CRR field */
#define OCTA_CRR_RD3_POS		(24UL)
#define OCTA_CRR_RD3			(0xFFUL << OCTA_CRR_RD3_POS)
#define OCTA_CRR_RD2_POS		(16UL)
#define OCTA_CRR_RD2			(0xFFUL << OCTA_CRR_RD2_POS)
#define OCTA_CRR_RD1_POS		(8UL)
#define OCTA_CRR_RD1			(0xFFUL << OCTA_CRR_RD1_POS)
#define OCTA_CRR_RD0_POS		(0UL)
#define OCTA_CRR_RD0			(0xFFUL << OCTA_CRR_RD0_POS)

/* RSTCN field */
#define OCTA_RSTCNT_RSTVAL_POS		(0UL)
#define OCTA_RSTCNT_RSTVAL		(0x1UL << OCTA_RSTCNT_RSTVAL_POS)

/* AER field */
#define OCTA_AER_POS			(0UL)
#define OCTA_AER_LE64MB			(0x0UL << OCTA_AER_POS)
#define OCTA_AER_128MB			(0x1UL << OCTA_AER_POS)
#define OCTA_AER_256MB			(0x3UL << OCTA_AER_POS)
#define OCTA_AER_512MB			(0x7UL << OCTA_AER_POS)

#endif	/* _OCTA_REG_H_ */

