/*
* Copyright (c) 2020 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

/**********************************************************************************************************************
 * File Name    : adc_e_iobitmask.h
 * Version      : 1.00
 * Description  : IO bit mask file for adc_e.
 *********************************************************************************************************************/

#ifndef ADC_E_IOBITMASK_H
#define ADC_E_IOBITMASK_H

#define R_ADC_E_ADCSR_DBLANS_Msk          (0x001FUL)
#define R_ADC_E_ADCSR_DBLANS_Pos          (0UL)
#define R_ADC_E_ADCSR_GBADIE_Msk          (0x0040UL)
#define R_ADC_E_ADCSR_GBADIE_Pos          (6UL)
#define R_ADC_E_ADCSR_DBLE_Msk            (0x0080UL)
#define R_ADC_E_ADCSR_DBLE_Pos            (7UL)
#define R_ADC_E_ADCSR_EXTRG_Msk           (0x0100UL)
#define R_ADC_E_ADCSR_EXTRG_Pos           (8UL)
#define R_ADC_E_ADCSR_TRGE_Msk            (0x0200UL)
#define R_ADC_E_ADCSR_TRGE_Pos            (9UL)
#define R_ADC_E_ADCSR_ADIE_Msk            (0x1000UL)
#define R_ADC_E_ADCSR_ADIE_Pos            (12UL)
#define R_ADC_E_ADCSR_ADCS_Msk            (0x6000UL)
#define R_ADC_E_ADCSR_ADCS_Pos            (13UL)
#define R_ADC_E_ADCSR_ADST_Msk            (0x8000UL)
#define R_ADC_E_ADCSR_ADST_Pos            (15UL)
#define R_ADC_E_ADREF_ADF_Msk             (0x01UL)
#define R_ADC_E_ADREF_ADF_Pos             (0UL)
#define R_ADC_E_ADREF_ADSCACT_Msk         (0x80UL)
#define R_ADC_E_ADREF_ADSCACT_Pos         (7UL)
#define R_ADC_E_ADANSA0_ANSA0_Msk         (0x00FFUL)
#define R_ADC_E_ADANSA0_ANSA0_Pos         (0UL)
#define R_ADC_E_ADADS0_ADS0_Msk           (0x00FFUL)
#define R_ADC_E_ADADS0_ADS0_Pos           (0UL)
#define R_ADC_E_ADADC_ADC_Msk             (0x07UL)
#define R_ADC_E_ADADC_ADC_Pos             (0UL)
#define R_ADC_E_ADADC_AVEE_Msk            (0x80UL)
#define R_ADC_E_ADADC_AVEE_Pos            (7UL)
#define R_ADC_E_ADCER_ADPRC_Msk           (0x0006UL)
#define R_ADC_E_ADCER_ADPRC_Pos           (1UL)
#define R_ADC_E_ADCER_ACE_Msk             (0x0020UL)
#define R_ADC_E_ADCER_ACE_Pos             (5UL)
#define R_ADC_E_ADCER_ADRFMT_Msk          (0x8000UL)
#define R_ADC_E_ADCER_ADRFMT_Pos          (15UL)
#define R_ADC_E_ADSTRGR_TRSB_Msk          (0x003FUL)
#define R_ADC_E_ADSTRGR_TRSB_Pos          (0UL)
#define R_ADC_E_ADSTRGR_TRSA_Msk          (0x3F00UL)
#define R_ADC_E_ADSTRGR_TRSA_Pos          (8UL)
#define R_ADC_E_ADANSB0_ANSB0_Msk         (0x00FFUL)
#define R_ADC_E_ADANSB0_ANSB0_Pos         (0UL)
#define R_ADC_E_ADDBLDR_DBLDR_Msk         (0xFFFFUL)
#define R_ADC_E_ADDBLDR_DBLDR_Pos         (0UL)
#define R_ADC_E_ADDR0_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR0_DR_Pos              (0UL)
#define R_ADC_E_ADDR1_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR1_DR_Pos              (0UL)
#define R_ADC_E_ADDR2_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR2_DR_Pos              (0UL)
#define R_ADC_E_ADDR3_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR3_DR_Pos              (0UL)
#define R_ADC_E_ADDR4_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR4_DR_Pos              (0UL)
#define R_ADC_E_ADDR5_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR5_DR_Pos              (0UL)
#define R_ADC_E_ADDR6_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR6_DR_Pos              (0UL)
#define R_ADC_E_ADDR7_DR_Msk              (0xFFFFUL)
#define R_ADC_E_ADDR7_DR_Pos              (0UL)
#define R_ADC_E_ADELCCR_ELCC_Msk          (0x03UL)
#define R_ADC_E_ADELCCR_ELCC_Pos          (0UL)
#define R_ADC_E_ADELCCR_GCELC_Msk         (0x04UL)
#define R_ADC_E_ADELCCR_GCELC_Pos         (2UL)
#define R_ADC_E_ADGSPCR_PGS_Msk           (0x0001UL)
#define R_ADC_E_ADGSPCR_PGS_Pos           (0UL)
#define R_ADC_E_ADGSPCR_GBRSCN_Msk        (0x0002UL)
#define R_ADC_E_ADGSPCR_GBRSCN_Pos        (1UL)
#define R_ADC_E_ADGSPCR_LGRRS_Msk         (0x4000UL)
#define R_ADC_E_ADGSPCR_LGRRS_Pos         (14UL)
#define R_ADC_E_ADGSPCR_GBRP_Msk          (0x8000UL)
#define R_ADC_E_ADGSPCR_GBRP_Pos          (15UL)
#define R_ADC_E_ADDBLDRA_DBLDRA_Msk       (0xFFFFUL)
#define R_ADC_E_ADDBLDRA_DBLDRA_Pos       (0UL)
#define R_ADC_E_ADDBLDRB_DBLDRB_Msk       (0xFFFFUL)
#define R_ADC_E_ADDBLDRB_DBLDRB_Pos       (0UL)
#define R_ADC_E_ADWINMON_MONCOMB_Msk      (0x01UL)
#define R_ADC_E_ADWINMON_MONCOMB_Pos      (0UL)
#define R_ADC_E_ADWINMON_MONCMPA_Msk      (0x10UL)
#define R_ADC_E_ADWINMON_MONCMPA_Pos      (4UL)
#define R_ADC_E_ADWINMON_MONCMPB_Msk      (0x20UL)
#define R_ADC_E_ADWINMON_MONCMPB_Pos      (5UL)
#define R_ADC_E_ADCMPCR_CMPAB_Msk         (0x0003UL)
#define R_ADC_E_ADCMPCR_CMPAB_Pos         (0UL)
#define R_ADC_E_ADCMPCR_CMPBE_Msk         (0x0200UL)
#define R_ADC_E_ADCMPCR_CMPBE_Pos         (9UL)
#define R_ADC_E_ADCMPCR_CMPAE_Msk         (0x0800UL)
#define R_ADC_E_ADCMPCR_CMPAE_Pos         (11UL)
#define R_ADC_E_ADCMPCR_CMPBIE_Msk        (0x2000UL)
#define R_ADC_E_ADCMPCR_CMPBIE_Pos        (13UL)
#define R_ADC_E_ADCMPCR_WCMPE_Msk         (0x4000UL)
#define R_ADC_E_ADCMPCR_WCMPE_Pos         (14UL)
#define R_ADC_E_ADCMPCR_CMPAIE_Msk        (0x8000UL)
#define R_ADC_E_ADCMPCR_CMPAIE_Pos        (15UL)
#define R_ADC_E_ADCMPANSR0_CMPCHA0_Msk    (0x00FFUL)
#define R_ADC_E_ADCMPANSR0_CMPCHA0_Pos    (0UL)
#define R_ADC_E_ADCMPLR0_CMPLCHA0_Msk     (0x00FFUL)
#define R_ADC_E_ADCMPLR0_CMPLCHA0_Pos     (0UL)
#define R_ADC_E_ADCMPDR0_CMPLLA_Msk       (0xFFFFUL)
#define R_ADC_E_ADCMPDR0_CMPLLA_Pos       (0UL)
#define R_ADC_E_ADCMPDR1_CMPULA_Msk       (0xFFFFUL)
#define R_ADC_E_ADCMPDR1_CMPULA_Pos       (0UL)
#define R_ADC_E_ADCMPSR0_CMPSTCHA0_Msk    (0x00FFUL)
#define R_ADC_E_ADCMPSR0_CMPSTCHA0_Pos    (0UL)
#define R_ADC_E_ADCMPBNSR_CMPCHB_Msk      (0x3FUL)
#define R_ADC_E_ADCMPBNSR_CMPCHB_Pos      (0UL)
#define R_ADC_E_ADCMPBNSR_CMPLB_Msk       (0x80UL)
#define R_ADC_E_ADCMPBNSR_CMPLB_Pos       (7UL)
#define R_ADC_E_ADWINLLB_CMPLLB_Msk       (0xFFFFUL)
#define R_ADC_E_ADWINLLB_CMPLLB_Pos       (0UL)
#define R_ADC_E_ADWINULB_CMPULB_Msk       (0xFFFFUL)
#define R_ADC_E_ADWINULB_CMPULB_Pos       (0UL)
#define R_ADC_E_ADCMPBSR_CMPSTB_Msk       (0x01UL)
#define R_ADC_E_ADCMPBSR_CMPSTB_Pos       (0UL)
#define R_ADC_E_ADANSC0_ANSC0_Msk         (0x00FFUL)
#define R_ADC_E_ADANSC0_ANSC0_Pos         (0UL)
#define R_ADC_E_ADGCTRGR_TRSC_Msk         (0x3FUL)
#define R_ADC_E_ADGCTRGR_TRSC_Pos         (0UL)
#define R_ADC_E_ADGCTRGR_GCADIE_Msk       (0x40UL)
#define R_ADC_E_ADGCTRGR_GCADIE_Pos       (6UL)
#define R_ADC_E_ADGCTRGR_GRCE_Msk         (0x80UL)
#define R_ADC_E_ADGCTRGR_GRCE_Pos         (7UL)
#define R_ADC_E_ADERCR_OWEIE_Msk          (0x04UL)
#define R_ADC_E_ADERCR_OWEIE_Pos          (2UL)
#define R_ADC_E_ADERCLR_OWEC_Msk          (0x04UL)
#define R_ADC_E_ADERCLR_OWEC_Pos          (2UL)
#define R_ADC_E_ADOWER_OWE_Msk            (0x00FFUL)
#define R_ADC_E_ADOWER_OWE_Pos            (0UL)
#define R_ADC_E_ADOWEER_DBOWE_Msk         (0x0001UL)
#define R_ADC_E_ADOWEER_DBOWE_Pos         (0UL)
#define R_ADC_E_ADOWEER_DAOWE_Msk         (0x0002UL)
#define R_ADC_E_ADOWEER_DAOWE_Pos         (1UL)
#define R_ADC_E_ADOWEER_DOWE_Msk          (0x0004UL)
#define R_ADC_E_ADOWEER_DOWE_Pos          (2UL)

#define R_ADC_E0_ADCSR_DBLANS_Msk         R_ADC_E_ADCSR_DBLANS_Msk
#define R_ADC_E0_ADCSR_DBLANS_Pos         R_ADC_E_ADCSR_DBLANS_Pos
#define R_ADC_E0_ADCSR_GBADIE_Msk         R_ADC_E_ADCSR_GBADIE_Msk
#define R_ADC_E0_ADCSR_GBADIE_Pos         R_ADC_E_ADCSR_GBADIE_Pos
#define R_ADC_E0_ADCSR_DBLE_Msk           R_ADC_E_ADCSR_DBLE_Msk
#define R_ADC_E0_ADCSR_DBLE_Pos           R_ADC_E_ADCSR_DBLE_Pos
#define R_ADC_E0_ADCSR_EXTRG_Msk          R_ADC_E_ADCSR_EXTRG_Msk
#define R_ADC_E0_ADCSR_EXTRG_Pos          R_ADC_E_ADCSR_EXTRG_Pos
#define R_ADC_E0_ADCSR_TRGE_Msk           R_ADC_E_ADCSR_TRGE_Msk
#define R_ADC_E0_ADCSR_TRGE_Pos           R_ADC_E_ADCSR_TRGE_Pos
#define R_ADC_E0_ADCSR_ADIE_Msk           R_ADC_E_ADCSR_ADIE_Msk
#define R_ADC_E0_ADCSR_ADIE_Pos           R_ADC_E_ADCSR_ADIE_Pos
#define R_ADC_E0_ADCSR_ADCS_Msk           R_ADC_E_ADCSR_ADCS_Msk
#define R_ADC_E0_ADCSR_ADCS_Pos           R_ADC_E_ADCSR_ADCS_Pos
#define R_ADC_E0_ADCSR_ADST_Msk           R_ADC_E_ADCSR_ADST_Msk
#define R_ADC_E0_ADCSR_ADST_Pos           R_ADC_E_ADCSR_ADST_Pos
#define R_ADC_E0_ADREF_ADF_Msk            R_ADC_E_ADREF_ADF_Msk
#define R_ADC_E0_ADREF_ADF_Pos            R_ADC_E_ADREF_ADF_Pos
#define R_ADC_E0_ADREF_ADSCACT_Msk        R_ADC_E_ADREF_ADSCACT_Msk
#define R_ADC_E0_ADREF_ADSCACT_Pos        R_ADC_E_ADREF_ADSCACT_Pos
#define R_ADC_E0_ADANSA0_ANSA0_Msk        R_ADC_E_ADANSA0_ANSA0_Msk
#define R_ADC_E0_ADANSA0_ANSA0_Pos        R_ADC_E_ADANSA0_ANSA0_Pos
#define R_ADC_E0_ADADS0_ADS0_Msk          R_ADC_E_ADADS0_ADS0_Msk
#define R_ADC_E0_ADADS0_ADS0_Pos          R_ADC_E_ADADS0_ADS0_Pos
#define R_ADC_E0_ADADC_ADC_Msk            R_ADC_E_ADADC_ADC_Msk
#define R_ADC_E0_ADADC_ADC_Pos            R_ADC_E_ADADC_ADC_Pos
#define R_ADC_E0_ADADC_AVEE_Msk           R_ADC_E_ADADC_AVEE_Msk
#define R_ADC_E0_ADADC_AVEE_Pos           R_ADC_E_ADADC_AVEE_Pos
#define R_ADC_E0_ADCER_ADPRC_Msk          R_ADC_E_ADCER_ADPRC_Msk
#define R_ADC_E0_ADCER_ADPRC_Pos          R_ADC_E_ADCER_ADPRC_Pos
#define R_ADC_E0_ADCER_ACE_Msk            R_ADC_E_ADCER_ACE_Msk
#define R_ADC_E0_ADCER_ACE_Pos            R_ADC_E_ADCER_ACE_Pos
#define R_ADC_E0_ADCER_ADRFMT_Msk         R_ADC_E_ADCER_ADRFMT_Msk
#define R_ADC_E0_ADCER_ADRFMT_Pos         R_ADC_E_ADCER_ADRFMT_Pos
#define R_ADC_E0_ADSTRGR_TRSB_Msk         R_ADC_E_ADSTRGR_TRSB_Msk
#define R_ADC_E0_ADSTRGR_TRSB_Pos         R_ADC_E_ADSTRGR_TRSB_Pos
#define R_ADC_E0_ADSTRGR_TRSA_Msk         R_ADC_E_ADSTRGR_TRSA_Msk
#define R_ADC_E0_ADSTRGR_TRSA_Pos         R_ADC_E_ADSTRGR_TRSA_Pos
#define R_ADC_E0_ADANSB0_ANSB0_Msk        R_ADC_E_ADANSB0_ANSB0_Msk
#define R_ADC_E0_ADANSB0_ANSB0_Pos        R_ADC_E_ADANSB0_ANSB0_Pos
#define R_ADC_E0_ADDBLDR_DBLDR_Msk        R_ADC_E_ADDBLDR_DBLDR_Msk
#define R_ADC_E0_ADDBLDR_DBLDR_Pos        R_ADC_E_ADDBLDR_DBLDR_Pos
#define R_ADC_E0_ADDR0_DR_Msk             R_ADC_E_ADDR0_DR_Msk
#define R_ADC_E0_ADDR0_DR_Pos             R_ADC_E_ADDR0_DR_Pos
#define R_ADC_E0_ADDR1_DR_Msk             R_ADC_E_ADDR1_DR_Msk
#define R_ADC_E0_ADDR1_DR_Pos             R_ADC_E_ADDR1_DR_Pos
#define R_ADC_E0_ADDR2_DR_Msk             R_ADC_E_ADDR2_DR_Msk
#define R_ADC_E0_ADDR2_DR_Pos             R_ADC_E_ADDR2_DR_Pos
#define R_ADC_E0_ADDR3_DR_Msk             R_ADC_E_ADDR3_DR_Msk
#define R_ADC_E0_ADDR3_DR_Pos             R_ADC_E_ADDR3_DR_Pos
#define R_ADC_E0_ADDR4_DR_Msk             R_ADC_E_ADDR4_DR_Msk
#define R_ADC_E0_ADDR4_DR_Pos             R_ADC_E_ADDR4_DR_Pos
#define R_ADC_E0_ADDR5_DR_Msk             R_ADC_E_ADDR5_DR_Msk
#define R_ADC_E0_ADDR5_DR_Pos             R_ADC_E_ADDR5_DR_Pos
#define R_ADC_E0_ADDR6_DR_Msk             R_ADC_E_ADDR6_DR_Msk
#define R_ADC_E0_ADDR6_DR_Pos             R_ADC_E_ADDR6_DR_Pos
#define R_ADC_E0_ADDR7_DR_Msk             R_ADC_E_ADDR7_DR_Msk
#define R_ADC_E0_ADDR7_DR_Pos             R_ADC_E_ADDR7_DR_Pos
#define R_ADC_E0_ADELCCR_ELCC_Msk         R_ADC_E_ADELCCR_ELCC_Msk
#define R_ADC_E0_ADELCCR_ELCC_Pos         R_ADC_E_ADELCCR_ELCC_Pos
#define R_ADC_E0_ADELCCR_GCELC_Msk        R_ADC_E_ADELCCR_GCELC_Msk
#define R_ADC_E0_ADELCCR_GCELC_Pos        R_ADC_E_ADELCCR_GCELC_Pos
#define R_ADC_E0_ADGSPCR_PGS_Msk          R_ADC_E_ADGSPCR_PGS_Msk
#define R_ADC_E0_ADGSPCR_PGS_Pos          R_ADC_E_ADGSPCR_PGS_Pos
#define R_ADC_E0_ADGSPCR_GBRSCN_Msk       R_ADC_E_ADGSPCR_GBRSCN_Msk
#define R_ADC_E0_ADGSPCR_GBRSCN_Pos       R_ADC_E_ADGSPCR_GBRSCN_Pos
#define R_ADC_E0_ADGSPCR_LGRRS_Msk        R_ADC_E_ADGSPCR_LGRRS_Msk
#define R_ADC_E0_ADGSPCR_LGRRS_Pos        R_ADC_E_ADGSPCR_LGRRS_Pos
#define R_ADC_E0_ADGSPCR_GBRP_Msk         R_ADC_E_ADGSPCR_GBRP_Msk
#define R_ADC_E0_ADGSPCR_GBRP_Pos         R_ADC_E_ADGSPCR_GBRP_Pos
#define R_ADC_E0_ADDBLDRA_DBLDRA_Msk      R_ADC_E_ADDBLDRA_DBLDRA_Msk
#define R_ADC_E0_ADDBLDRA_DBLDRA_Pos      R_ADC_E_ADDBLDRA_DBLDRA_Pos
#define R_ADC_E0_ADDBLDRB_DBLDRB_Msk      R_ADC_E_ADDBLDRB_DBLDRB_Msk
#define R_ADC_E0_ADDBLDRB_DBLDRB_Pos      R_ADC_E_ADDBLDRB_DBLDRB_Pos
#define R_ADC_E0_ADWINMON_MONCOMB_Msk     R_ADC_E_ADWINMON_MONCOMB_Msk
#define R_ADC_E0_ADWINMON_MONCOMB_Pos     R_ADC_E_ADWINMON_MONCOMB_Pos
#define R_ADC_E0_ADWINMON_MONCMPA_Msk     R_ADC_E_ADWINMON_MONCMPA_Msk
#define R_ADC_E0_ADWINMON_MONCMPA_Pos     R_ADC_E_ADWINMON_MONCMPA_Pos
#define R_ADC_E0_ADWINMON_MONCMPB_Msk     R_ADC_E_ADWINMON_MONCMPB_Msk
#define R_ADC_E0_ADWINMON_MONCMPB_Pos     R_ADC_E_ADWINMON_MONCMPB_Pos
#define R_ADC_E0_ADCMPCR_CMPAB_Msk        R_ADC_E_ADCMPCR_CMPAB_Msk
#define R_ADC_E0_ADCMPCR_CMPAB_Pos        R_ADC_E_ADCMPCR_CMPAB_Pos
#define R_ADC_E0_ADCMPCR_CMPBE_Msk        R_ADC_E_ADCMPCR_CMPBE_Msk
#define R_ADC_E0_ADCMPCR_CMPBE_Pos        R_ADC_E_ADCMPCR_CMPBE_Pos
#define R_ADC_E0_ADCMPCR_CMPAE_Msk        R_ADC_E_ADCMPCR_CMPAE_Msk
#define R_ADC_E0_ADCMPCR_CMPAE_Pos        R_ADC_E_ADCMPCR_CMPAE_Pos
#define R_ADC_E0_ADCMPCR_CMPBIE_Msk       R_ADC_E_ADCMPCR_CMPBIE_Msk
#define R_ADC_E0_ADCMPCR_CMPBIE_Pos       R_ADC_E_ADCMPCR_CMPBIE_Pos
#define R_ADC_E0_ADCMPCR_WCMPE_Msk        R_ADC_E_ADCMPCR_WCMPE_Msk
#define R_ADC_E0_ADCMPCR_WCMPE_Pos        R_ADC_E_ADCMPCR_WCMPE_Pos
#define R_ADC_E0_ADCMPCR_CMPAIE_Msk       R_ADC_E_ADCMPCR_CMPAIE_Msk
#define R_ADC_E0_ADCMPCR_CMPAIE_Pos       R_ADC_E_ADCMPCR_CMPAIE_Pos
#define R_ADC_E0_ADCMPANSR0_CMPCHA0_Msk   R_ADC_E_ADCMPANSR0_CMPCHA0_Msk
#define R_ADC_E0_ADCMPANSR0_CMPCHA0_Pos   R_ADC_E_ADCMPANSR0_CMPCHA0_Pos
#define R_ADC_E0_ADCMPLR0_CMPLCHA0_Msk    R_ADC_E_ADCMPLR0_CMPLCHA0_Msk
#define R_ADC_E0_ADCMPLR0_CMPLCHA0_Pos    R_ADC_E_ADCMPLR0_CMPLCHA0_Pos
#define R_ADC_E0_ADCMPDR0_CMPLLA_Msk      R_ADC_E_ADCMPDR0_CMPLLA_Msk
#define R_ADC_E0_ADCMPDR0_CMPLLA_Pos      R_ADC_E_ADCMPDR0_CMPLLA_Pos
#define R_ADC_E0_ADCMPDR1_CMPULA_Msk      R_ADC_E_ADCMPDR1_CMPULA_Msk
#define R_ADC_E0_ADCMPDR1_CMPULA_Pos      R_ADC_E_ADCMPDR1_CMPULA_Pos
#define R_ADC_E0_ADCMPSR0_CMPSTCHA0_Msk   R_ADC_E_ADCMPSR0_CMPSTCHA0_Msk
#define R_ADC_E0_ADCMPSR0_CMPSTCHA0_Pos   R_ADC_E_ADCMPSR0_CMPSTCHA0_Pos
#define R_ADC_E0_ADCMPBNSR_CMPCHB_Msk     R_ADC_E_ADCMPBNSR_CMPCHB_Msk
#define R_ADC_E0_ADCMPBNSR_CMPCHB_Pos     R_ADC_E_ADCMPBNSR_CMPCHB_Pos
#define R_ADC_E0_ADCMPBNSR_CMPLB_Msk      R_ADC_E_ADCMPBNSR_CMPLB_Msk
#define R_ADC_E0_ADCMPBNSR_CMPLB_Pos      R_ADC_E_ADCMPBNSR_CMPLB_Pos
#define R_ADC_E0_ADWINLLB_CMPLLB_Msk      R_ADC_E_ADWINLLB_CMPLLB_Msk
#define R_ADC_E0_ADWINLLB_CMPLLB_Pos      R_ADC_E_ADWINLLB_CMPLLB_Pos
#define R_ADC_E0_ADWINULB_CMPULB_Msk      R_ADC_E_ADWINULB_CMPULB_Msk
#define R_ADC_E0_ADWINULB_CMPULB_Pos      R_ADC_E_ADWINULB_CMPULB_Pos
#define R_ADC_E0_ADCMPBSR_CMPSTB_Msk      R_ADC_E_ADCMPBSR_CMPSTB_Msk
#define R_ADC_E0_ADCMPBSR_CMPSTB_Pos      R_ADC_E_ADCMPBSR_CMPSTB_Pos
#define R_ADC_E0_ADANSC0_ANSC0_Msk        R_ADC_E_ADANSC0_ANSC0_Msk
#define R_ADC_E0_ADANSC0_ANSC0_Pos        R_ADC_E_ADANSC0_ANSC0_Pos
#define R_ADC_E0_ADGCTRGR_TRSC_Msk        R_ADC_E_ADGCTRGR_TRSC_Msk
#define R_ADC_E0_ADGCTRGR_TRSC_Pos        R_ADC_E_ADGCTRGR_TRSC_Pos
#define R_ADC_E0_ADGCTRGR_GCADIE_Msk      R_ADC_E_ADGCTRGR_GCADIE_Msk
#define R_ADC_E0_ADGCTRGR_GCADIE_Pos      R_ADC_E_ADGCTRGR_GCADIE_Pos
#define R_ADC_E0_ADGCTRGR_GRCE_Msk        R_ADC_E_ADGCTRGR_GRCE_Msk
#define R_ADC_E0_ADGCTRGR_GRCE_Pos        R_ADC_E_ADGCTRGR_GRCE_Pos
#define R_ADC_E0_ADERCR_OWEIE_Msk         R_ADC_E_ADERCR_OWEIE_Msk
#define R_ADC_E0_ADERCR_OWEIE_Pos         R_ADC_E_ADERCR_OWEIE_Pos
#define R_ADC_E0_ADERCLR_OWEC_Msk         R_ADC_E_ADERCLR_OWEC_Msk
#define R_ADC_E0_ADERCLR_OWEC_Pos         R_ADC_E_ADERCLR_OWEC_Pos
#define R_ADC_E0_ADOWER_OWE_Msk           R_ADC_E_ADOWER_OWE_Msk
#define R_ADC_E0_ADOWER_OWE_Pos           R_ADC_E_ADOWER_OWE_Pos
#define R_ADC_E0_ADOWEER_DBOWE_Msk        R_ADC_E_ADOWEER_DBOWE_Msk
#define R_ADC_E0_ADOWEER_DBOWE_Pos        R_ADC_E_ADOWEER_DBOWE_Pos
#define R_ADC_E0_ADOWEER_DAOWE_Msk        R_ADC_E_ADOWEER_DAOWE_Msk
#define R_ADC_E0_ADOWEER_DAOWE_Pos        R_ADC_E_ADOWEER_DAOWE_Pos
#define R_ADC_E0_ADOWEER_DOWE_Msk         R_ADC_E_ADOWEER_DOWE_Msk
#define R_ADC_E0_ADOWEER_DOWE_Pos         R_ADC_E_ADOWEER_DOWE_Pos

#endif
