/*
* Copyright (c) 2020 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#ifndef BSP_SYSTEM_RESET_H
#define BSP_SYSTEM_RESET_H

/***********************************************************************************************************************
 * Includes
 **********************************************************************************************************************/

/** Common macro for FSP header files. There is also a corresponding FSP_FOOTER macro at the end of this file. */
FSP_HEADER

/***********************************************************************************************************************
 * Macro definitions
 **********************************************************************************************************************/
#ifndef BSP_SYSTEM_RESET_STATUS_REG_BASE
 #define BSP_SYSTEM_RESET_STATUS_REG_BASE    (&R_CPG->CPG_WDTOVF_RST)
#endif

/***********************************************************************************************************************
 * Typedef definitions
 **********************************************************************************************************************/

/** BSP System Reset Status */
typedef enum e_bsp_system_reset_status
{
    BSP_SYSTEM_RESET_STATUS_NOT_GENERATED = 0, ///< System reset has not been generated by the signal.
    BSP_SYSTEM_RESET_STATUS_GENERATED     = 1, ///< System reset has been generated by the signal.
} bsp_system_reset_status_t;

#ifndef BSP_OVERRIDE_BSP_SYSTEM_RESET_SIGNAL_T

/** BSP System Reset Signals */
typedef enum e_bsp_system_reset_signal
{
    BSP_SYSTEM_RESET_SIGNAL_WDT_CA55_0 = 0, ///< WDT for Cortex-A55 Core 0.
    BSP_SYSTEM_RESET_SIGNAL_WDT_CA55_1 = 1, ///< WDT for Cortex-A55 Core 1.
    BSP_SYSTEM_RESET_SIGNAL_WDT_CM33   = 2, ///< WDT for Cortex-M33.
    BSP_SYSTEM_RESET_SIGNAL_MAX        = 3, ///< The number of supported system reset signals.
} bsp_system_reset_signal_t;

#endif

/***********************************************************************************************************************
 * Exported global variables
 **********************************************************************************************************************/
extern bsp_system_reset_status_t g_bsp_system_reset_status_table[BSP_SYSTEM_RESET_SIGNAL_MAX];

/***********************************************************************************************************************
 * Exported global functions (to be accessed by other files)
 **********************************************************************************************************************/

/** Common macro for FSP header files. There is also a corresponding FSP_HEADER macro at the top of this file. */
FSP_FOOTER

#endif
