/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#ifndef BSP_ELC_H
#define BSP_ELC_H

/***********************************************************************************************************************
 * Includes   <System Includes> , "Project Includes"
 **********************************************************************************************************************/

/** Common macro for FSP header files. There is also a corresponding FSP_FOOTER macro at the end of this file. */
FSP_HEADER

/***********************************************************************************************************************
 * Macro definitions
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Typedef definitions
 **********************************************************************************************************************/

/*******************************************************************************************************************//**
 * @addtogroup BSP_MCU_RZT2H
 * @{
 **********************************************************************************************************************/

/** Sources of event signals to be linked to other peripherals or the CPU
 * @note This list may change based on based on the device.
 * */
typedef enum e_elc_event_rzt2h
{
    ELC_EVENT_INTCPU0                                  = (0),   // Software interrupt 0
    ELC_EVENT_INTCPU1                                  = (1),   // Software interrupt 1
    ELC_EVENT_INTCPU2                                  = (2),   // Software interrupt 2
    ELC_EVENT_INTCPU3                                  = (3),   // Software interrupt 3
    ELC_EVENT_INTCPU4                                  = (4),   // Software interrupt 4
    ELC_EVENT_INTCPU5                                  = (5),   // Software interrupt 5
    ELC_EVENT_INTCPU6                                  = (6),   // Software interrupt 6
    ELC_EVENT_INTCPU7                                  = (7),   // Software interrupt 7
    ELC_EVENT_INTCPU8                                  = (8),   // Software interrupt 8
    ELC_EVENT_INTCPU9                                  = (9),   // Software interrupt 9
    ELC_EVENT_INTCPU10                                 = (10),  // Software interrupt 10
    ELC_EVENT_INTCPU11                                 = (11),  // Software interrupt 11
    ELC_EVENT_INTCPU12                                 = (12),  // Software interrupt 12
    ELC_EVENT_INTCPU13                                 = (13),  // Software interrupt 13
    ELC_EVENT_INTCPU14                                 = (14),  // Software interrupt 14
    ELC_EVENT_INTCPU15                                 = (15),  // Software interrupt 15
    ELC_EVENT_IRQ0                                     = (16),  // External pin interrupt0
    ELC_EVENT_IRQ1                                     = (17),  // External pin interrupt1
    ELC_EVENT_IRQ2                                     = (18),  // External pin interrupt2
    ELC_EVENT_IRQ3                                     = (19),  // External pin interrupt3
    ELC_EVENT_IRQ4                                     = (20),  // External pin interrupt4
    ELC_EVENT_IRQ5                                     = (21),  // External pin interrupt5
    ELC_EVENT_IRQ6                                     = (22),  // External pin interrupt6
    ELC_EVENT_IRQ7                                     = (23),  // External pin interrupt7
    ELC_EVENT_IRQ8                                     = (24),  // External pin interrupt8
    ELC_EVENT_IRQ9                                     = (25),  // External pin interrupt9
    ELC_EVENT_IRQ10                                    = (26),  // External pin interrupt10
    ELC_EVENT_IRQ11                                    = (27),  // External pin interrupt11
    ELC_EVENT_IRQ12                                    = (28),  // External pin interrupt12
    ELC_EVENT_IRQ13                                    = (29),  // External pin interrupt13
    ELC_EVENT_IRQ14                                    = (30),  // External pin interrupt14
    ELC_EVENT_IRQ15                                    = (31),  // External pin interrupt15
    ELC_EVENT_DMAC0_INT0                               = (32),  // DMAC0 transfercompletion 0
    ELC_EVENT_DMAC0_INT1                               = (33),  // DMAC0 transfercompletion 1
    ELC_EVENT_DMAC0_INT2                               = (34),  // DMAC0 transfercompletion 2
    ELC_EVENT_DMAC0_INT3                               = (35),  // DMAC0 transfercompletion 3
    ELC_EVENT_DMAC0_INT4                               = (36),  // DMAC0 transfercompletion 4
    ELC_EVENT_DMAC0_INT5                               = (37),  // DMAC0 transfercompletion 5
    ELC_EVENT_DMAC0_INT6                               = (38),  // DMAC0 transfercompletion 6
    ELC_EVENT_DMAC0_INT7                               = (39),  // DMAC0 transfercompletion 7
    ELC_EVENT_DMAC0_INT8                               = (40),  // DMAC0 transfercompletion 8
    ELC_EVENT_DMAC0_INT9                               = (41),  // DMAC0 transfercompletion 9
    ELC_EVENT_DMAC0_INT10                              = (42),  // DMAC0 transfercompletion 10
    ELC_EVENT_DMAC0_INT11                              = (43),  // DMAC0 transfercompletion 11
    ELC_EVENT_DMAC0_INT12                              = (44),  // DMAC0 transfercompletion 12
    ELC_EVENT_DMAC0_INT13                              = (45),  // DMAC0 transfercompletion 13
    ELC_EVENT_DMAC0_INT14                              = (46),  // DMAC0 transfercompletion 14
    ELC_EVENT_DMAC0_INT15                              = (47),  // DMAC0 transfercompletion 15
    ELC_EVENT_DMAC1_INT0                               = (48),  // DMAC1 transfercompletion 0
    ELC_EVENT_DMAC1_INT1                               = (49),  // DMAC1 transfercompletion 1
    ELC_EVENT_DMAC1_INT2                               = (50),  // DMAC1 transfercompletion 2
    ELC_EVENT_DMAC1_INT3                               = (51),  // DMAC1 transfercompletion 3
    ELC_EVENT_DMAC1_INT4                               = (52),  // DMAC1 transfercompletion 4
    ELC_EVENT_DMAC1_INT5                               = (53),  // DMAC1 transfercompletion 5
    ELC_EVENT_DMAC1_INT6                               = (54),  // DMAC1 transfercompletion 6
    ELC_EVENT_DMAC1_INT7                               = (55),  // DMAC1 transfercompletion 7
    ELC_EVENT_DMAC1_INT8                               = (56),  // DMAC1 transfercompletion 8
    ELC_EVENT_DMAC1_INT9                               = (57),  // DMAC1 transfercompletion 9
    ELC_EVENT_DMAC1_INT10                              = (58),  // DMAC1 transfercompletion 10
    ELC_EVENT_DMAC1_INT11                              = (59),  // DMAC1 transfercompletion 11
    ELC_EVENT_DMAC1_INT12                              = (60),  // DMAC1 transfercompletion 12
    ELC_EVENT_DMAC1_INT13                              = (61),  // DMAC1 transfercompletion 13
    ELC_EVENT_DMAC1_INT14                              = (62),  // DMAC1 transfercompletion 14
    ELC_EVENT_DMAC1_INT15                              = (63),  // DMAC1 transfercompletion 15
    ELC_EVENT_DMAC2_INT0                               = (64),  // DMAC2 transfercompletion 0
    ELC_EVENT_DMAC2_INT1                               = (65),  // DMAC2 transfercompletion 1
    ELC_EVENT_DMAC2_INT2                               = (66),  // DMAC2 transfercompletion 2
    ELC_EVENT_DMAC2_INT3                               = (67),  // DMAC2 transfercompletion 3
    ELC_EVENT_DMAC2_INT4                               = (68),  // DMAC2 transfercompletion 4
    ELC_EVENT_DMAC2_INT5                               = (69),  // DMAC2 transfercompletion 5
    ELC_EVENT_DMAC2_INT6                               = (70),  // DMAC2 transfercompletion 6
    ELC_EVENT_DMAC2_INT7                               = (71),  // DMAC2 transfercompletion 7
    ELC_EVENT_DMAC2_INT8                               = (72),  // DMAC2 transfercompletion 8
    ELC_EVENT_DMAC2_INT9                               = (73),  // DMAC2 transfercompletion 9
    ELC_EVENT_DMAC2_INT10                              = (74),  // DMAC2 transfercompletion 10
    ELC_EVENT_DMAC2_INT11                              = (75),  // DMAC2 transfercompletion 11
    ELC_EVENT_DMAC2_INT12                              = (76),  // DMAC2 transfercompletion 12
    ELC_EVENT_DMAC2_INT13                              = (77),  // DMAC2 transfercompletion 13
    ELC_EVENT_DMAC2_INT14                              = (78),  // DMAC2 transfercompletion 14
    ELC_EVENT_DMAC2_INT15                              = (79),  // DMAC2 transfercompletion 15
    ELC_EVENT_GPT00_0_INT0                             = (97),  // GPT00_0 selectedinterrupt 0
    ELC_EVENT_GPT00_0_INT1                             = (98),  // GPT00_0 selectedinterrupt 1
    ELC_EVENT_GPT00_0_INT2                             = (99),  // GPT00_0 selectedinterrupt 2
    ELC_EVENT_GPT00_0_INT3                             = (100), // GPT00_0 selectedinterrupt 3
    ELC_EVENT_GPT00_0_INT4                             = (101), // GPT00_0 combinedinterrupt
    ELC_EVENT_GPT00_1_INT0                             = (102), // GPT00_1 selectedinterrupt 0
    ELC_EVENT_GPT00_1_INT1                             = (103), // GPT00_1 selectedinterrupt 1
    ELC_EVENT_GPT00_1_INT2                             = (104), // GPT00_1 selectedinterrupt 2
    ELC_EVENT_GPT00_1_INT3                             = (105), // GPT00_1 selectedinterrupt 3
    ELC_EVENT_GPT00_1_INT4                             = (106), // GPT00_1 combinedinterrupt
    ELC_EVENT_GPT00_2_INT0                             = (107), // GPT00_2 selectedinterrupt 0
    ELC_EVENT_GPT00_2_INT1                             = (108), // GPT00_2 selectedinterrupt 1
    ELC_EVENT_GPT00_2_INT2                             = (109), // GPT00_2 selectedinterrupt 2
    ELC_EVENT_GPT00_2_INT3                             = (110), // GPT00_2 selectedinterrupt 3
    ELC_EVENT_GPT00_2_INT4                             = (111), // GPT00_2 combinedinterrupt
    ELC_EVENT_GPT00_3_INT0                             = (112), // GPT00_3 selectedinterrupt 0
    ELC_EVENT_GPT00_3_INT1                             = (113), // GPT00_3 selectedinterrupt 1
    ELC_EVENT_GPT00_3_INT2                             = (114), // GPT00_3 selectedinterrupt 2
    ELC_EVENT_GPT00_3_INT3                             = (115), // GPT00_3 selectedinterrupt 3
    ELC_EVENT_GPT00_3_INT4                             = (116), // GPT00_3 combinedinterrupt
    ELC_EVENT_GPT00_4_INT0                             = (117), // GPT00_4 selectedinterrupt 0
    ELC_EVENT_GPT00_4_INT1                             = (118), // GPT00_4 selectedinterrupt 1
    ELC_EVENT_GPT00_4_INT2                             = (119), // GPT00_4 selectedinterrupt 2
    ELC_EVENT_GPT00_4_INT3                             = (120), // GPT00_4 selectedinterrupt 3
    ELC_EVENT_GPT00_4_INT4                             = (121), // GPT00_4 combinedinterrupt
    ELC_EVENT_GPT01_0_INT0                             = (122), // GPT01_0 selectedinterrupt 0
    ELC_EVENT_GPT01_0_INT1                             = (123), // GPT01_0 selectedinterrupt 1
    ELC_EVENT_GPT01_0_INT2                             = (124), // GPT01_0 selectedinterrupt 2
    ELC_EVENT_GPT01_0_INT3                             = (125), // GPT01_0 selectedinterrupt 3
    ELC_EVENT_GPT01_0_INT4                             = (126), // GPT01_0 combinedinterrupt
    ELC_EVENT_GPT01_1_INT0                             = (127), // GPT01_1 selectedinterrupt 0
    ELC_EVENT_GPT01_1_INT1                             = (128), // GPT01_1 selectedinterrupt 1
    ELC_EVENT_GPT01_1_INT2                             = (129), // GPT01_1 selectedinterrupt 2
    ELC_EVENT_GPT01_1_INT3                             = (130), // GPT01_1 selectedinterrupt 3
    ELC_EVENT_GPT01_1_INT4                             = (131), // GPT01_1 combinedinterrupt
    ELC_EVENT_GPT01_2_INT0                             = (132), // GPT01_2 selectedinterrupt 0
    ELC_EVENT_GPT01_2_INT1                             = (133), // GPT01_2 selectedinterrupt 1
    ELC_EVENT_GPT01_2_INT2                             = (134), // GPT01_2 selectedinterrupt 2
    ELC_EVENT_GPT01_2_INT3                             = (135), // GPT01_2 selectedinterrupt 3
    ELC_EVENT_GPT01_2_INT4                             = (136), // GPT01_2 combinedinterrupt
    ELC_EVENT_GPT01_3_INT0                             = (137), // GPT01_3 selectedinterrupt 0
    ELC_EVENT_GPT01_3_INT1                             = (138), // GPT01_3 selectedinterrupt 1
    ELC_EVENT_GPT01_3_INT2                             = (139), // GPT01_3 selectedinterrupt 2
    ELC_EVENT_GPT01_3_INT3                             = (140), // GPT01_3 selectedinterrupt 3
    ELC_EVENT_GPT01_3_INT4                             = (141), // GPT01_3 combinedinterrupt
    ELC_EVENT_GPT01_4_INT0                             = (142), // GPT01_4 selectedinterrupt 0
    ELC_EVENT_GPT01_4_INT1                             = (143), // GPT01_4 selectedinterrupt 1
    ELC_EVENT_GPT01_4_INT2                             = (144), // GPT01_4 selectedinterrupt 2
    ELC_EVENT_GPT01_4_INT3                             = (145), // GPT01_4 selectedinterrupt 3
    ELC_EVENT_GPT01_4_INT4                             = (146), // GPT01_4 combinedinterrupt
    ELC_EVENT_GPT02_0_INT0                             = (147), // GPT02_0 selectedinterrupt 0
    ELC_EVENT_GPT02_0_INT1                             = (148), // GPT02_0 selectedinterrupt 1
    ELC_EVENT_GPT02_0_INT2                             = (149), // GPT02_0 selectedinterrupt 2
    ELC_EVENT_GPT02_0_INT3                             = (150), // GPT02_0 selectedinterrupt 3
    ELC_EVENT_GPT02_0_INT4                             = (151), // GPT02_0 combinedinterrupt
    ELC_EVENT_GPT02_1_INT0                             = (152), // GPT02_1 selectedinterrupt 0
    ELC_EVENT_GPT02_1_INT1                             = (153), // GPT02_1 selectedinterrupt 1
    ELC_EVENT_GPT02_1_INT2                             = (154), // GPT02_1 selectedinterrupt 2
    ELC_EVENT_GPT02_1_INT3                             = (155), // GPT02_1 selectedinterrupt 3
    ELC_EVENT_GPT02_1_INT4                             = (156), // GPT02_1 combinedinterrupt
    ELC_EVENT_GPT02_2_INT0                             = (157), // GPT02_2 selectedinterrupt 0
    ELC_EVENT_GPT02_2_INT1                             = (158), // GPT02_2 selectedinterrupt 1
    ELC_EVENT_GPT02_2_INT2                             = (159), // GPT02_2 selectedinterrupt 2
    ELC_EVENT_GPT02_2_INT3                             = (160), // GPT02_2 selectedinterrupt 3
    ELC_EVENT_GPT02_2_INT4                             = (161), // GPT02_2 combinedinterrupt
    ELC_EVENT_GPT02_3_INT0                             = (162), // GPT02_3 selectedinterrupt 0
    ELC_EVENT_GPT02_3_INT1                             = (163), // GPT02_3 selectedinterrupt 1
    ELC_EVENT_GPT02_3_INT2                             = (164), // GPT02_3 selectedinterrupt 2
    ELC_EVENT_GPT02_3_INT3                             = (165), // GPT02_3 selectedinterrupt 3
    ELC_EVENT_GPT02_3_INT4                             = (166), // GPT02_3 combinedinterrupt
    ELC_EVENT_GPT02_4_INT0                             = (167), // GPT02_4 selectedinterrupt 0
    ELC_EVENT_GPT02_4_INT1                             = (168), // GPT02_4 selectedinterrupt 1
    ELC_EVENT_GPT02_4_INT2                             = (169), // GPT02_4 selectedinterrupt 2
    ELC_EVENT_GPT02_4_INT3                             = (170), // GPT02_4 selectedinterrupt 3
    ELC_EVENT_GPT02_4_INT4                             = (171), // GPT02_4 combinedinterrupt
    ELC_EVENT_GPT03_0_INT0                             = (172), // GPT03_0 selectedinterrupt 0
    ELC_EVENT_GPT03_0_INT1                             = (173), // GPT03_0 selectedinterrupt 1
    ELC_EVENT_GPT03_0_INT2                             = (174), // GPT03_0 selectedinterrupt 2
    ELC_EVENT_GPT03_0_INT3                             = (175), // GPT03_0 selectedinterrupt 3
    ELC_EVENT_GPT03_0_INT4                             = (176), // GPT03_0 combinedinterrupt
    ELC_EVENT_GPT03_1_INT0                             = (177), // GPT03_1 selectedinterrupt 0
    ELC_EVENT_GPT03_1_INT1                             = (178), // GPT03_1 selectedinterrupt 1
    ELC_EVENT_GPT03_1_INT2                             = (179), // GPT03_1 selectedinterrupt 2
    ELC_EVENT_GPT03_1_INT3                             = (180), // GPT03_1 selectedinterrupt 3
    ELC_EVENT_GPT03_1_INT4                             = (181), // GPT03_1 combinedinterrupt
    ELC_EVENT_GPT03_2_INT0                             = (182), // GPT03_2 selectedinterrupt 0
    ELC_EVENT_GPT03_2_INT1                             = (183), // GPT03_2 selectedinterrupt 1
    ELC_EVENT_GPT03_2_INT2                             = (184), // GPT03_2 selectedinterrupt 2
    ELC_EVENT_GPT03_2_INT3                             = (185), // GPT03_2 selectedinterrupt 3
    ELC_EVENT_GPT03_2_INT4                             = (186), // GPT03_2 combinedinterrupt
    ELC_EVENT_GPT03_3_INT0                             = (187), // GPT03_3 selectedinterrupt 0
    ELC_EVENT_GPT03_3_INT1                             = (188), // GPT03_3 selectedinterrupt 1
    ELC_EVENT_GPT03_3_INT2                             = (189), // GPT03_3 selectedinterrupt 2
    ELC_EVENT_GPT03_3_INT3                             = (190), // GPT03_3 selectedinterrupt 3
    ELC_EVENT_GPT03_3_INT4                             = (191), // GPT03_3 combinedinterrupt
    ELC_EVENT_GPT03_4_INT0                             = (192), // GPT03_4 selectedinterrupt 0
    ELC_EVENT_GPT03_4_INT1                             = (193), // GPT03_4 selectedinterrupt 1
    ELC_EVENT_GPT03_4_INT2                             = (194), // GPT03_4 selectedinterrupt 2
    ELC_EVENT_GPT03_4_INT3                             = (195), // GPT03_4 selectedinterrupt 3
    ELC_EVENT_GPT03_4_INT4                             = (196), // GPT03_4 combinedinterrupt
    ELC_EVENT_GPT04_0_INT0                             = (197), // GPT04_0 selectedinterrupt 0
    ELC_EVENT_GPT04_0_INT1                             = (198), // GPT04_0 selectedinterrupt 1
    ELC_EVENT_GPT04_0_INT2                             = (199), // GPT04_0 selectedinterrupt 2
    ELC_EVENT_GPT04_0_INT3                             = (200), // GPT04_0 selectedinterrupt 3
    ELC_EVENT_GPT04_0_INT4                             = (201), // GPT04_0 combinedinterrupt
    ELC_EVENT_GPT04_1_INT0                             = (202), // GPT04_1 selectedinterrupt 0
    ELC_EVENT_GPT04_1_INT1                             = (203), // GPT04_1 selectedinterrupt 1
    ELC_EVENT_GPT04_1_INT2                             = (204), // GPT04_1 selectedinterrupt 2
    ELC_EVENT_GPT04_1_INT3                             = (205), // GPT04_1 selectedinterrupt 3
    ELC_EVENT_GPT04_1_INT4                             = (206), // GPT04_1 combinedinterrupt
    ELC_EVENT_GPT04_2_INT0                             = (207), // GPT04_2 selectedinterrupt 0
    ELC_EVENT_GPT04_2_INT1                             = (208), // GPT04_2 selectedinterrupt 1
    ELC_EVENT_GPT04_2_INT2                             = (209), // GPT04_2 selectedinterrupt 2
    ELC_EVENT_GPT04_2_INT3                             = (210), // GPT04_2 selectedinterrupt 3
    ELC_EVENT_GPT04_2_INT4                             = (211), // GPT04_2 combinedinterrupt
    ELC_EVENT_GPT04_3_INT0                             = (212), // GPT04_3 selectedinterrupt 0
    ELC_EVENT_GPT04_3_INT1                             = (213), // GPT04_3 selectedinterrupt 1
    ELC_EVENT_GPT04_3_INT2                             = (214), // GPT04_3 selectedinterrupt 2
    ELC_EVENT_GPT04_3_INT3                             = (215), // GPT04_3 selectedinterrupt 3
    ELC_EVENT_GPT04_3_INT4                             = (216), // GPT04_3 combinedinterrupt
    ELC_EVENT_GPT04_4_INT0                             = (217), // GPT04_4 selectedinterrupt 0
    ELC_EVENT_GPT04_4_INT1                             = (218), // GPT04_4 selectedinterrupt 1
    ELC_EVENT_GPT04_4_INT2                             = (219), // GPT04_4 selectedinterrupt 2
    ELC_EVENT_GPT04_4_INT3                             = (220), // GPT04_4 selectedinterrupt 3
    ELC_EVENT_GPT04_4_INT4                             = (221), // GPT04_4 combinedinterrupt
    ELC_EVENT_GPT05_0_INT0                             = (222), // GPT05_0 selectedinterrupt 0
    ELC_EVENT_GPT05_0_INT1                             = (223), // GPT05_0 selectedinterrupt 1
    ELC_EVENT_GPT05_0_INT2                             = (224), // GPT05_0 selectedinterrupt 2
    ELC_EVENT_GPT05_0_INT3                             = (225), // GPT05_0 selectedinterrupt 3
    ELC_EVENT_GPT05_0_INT4                             = (226), // GPT05_0 combinedinterrupt
    ELC_EVENT_GPT05_1_INT0                             = (227), // GPT05_1 selectedinterrupt 0
    ELC_EVENT_GPT05_1_INT1                             = (228), // GPT05_1 selectedinterrupt 1
    ELC_EVENT_GPT05_1_INT2                             = (229), // GPT05_1 selectedinterrupt 2
    ELC_EVENT_GPT05_1_INT3                             = (230), // GPT05_1 selectedinterrupt 3
    ELC_EVENT_GPT05_1_INT4                             = (231), // GPT05_1 combinedinterrupt
    ELC_EVENT_GPT05_2_INT0                             = (232), // GPT05_2 selectedinterrupt 0
    ELC_EVENT_GPT05_2_INT1                             = (233), // GPT05_2 selectedinterrupt 1
    ELC_EVENT_GPT05_2_INT2                             = (234), // GPT05_2 selectedinterrupt 2
    ELC_EVENT_GPT05_2_INT3                             = (235), // GPT05_2 selectedinterrupt 3
    ELC_EVENT_GPT05_2_INT4                             = (236), // GPT05_2 combinedinterrupt
    ELC_EVENT_GPT05_3_INT0                             = (237), // GPT05_3 selectedinterrupt 0
    ELC_EVENT_GPT05_3_INT1                             = (238), // GPT05_3 selectedinterrupt 1
    ELC_EVENT_GPT05_3_INT2                             = (239), // GPT05_3 selectedinterrupt 2
    ELC_EVENT_GPT05_3_INT3                             = (240), // GPT05_3 selectedinterrupt 3
    ELC_EVENT_GPT05_3_INT4                             = (241), // GPT05_3 combinedinterrupt
    ELC_EVENT_GPT05_4_INT0                             = (242), // GPT05_4 selectedinterrupt 0
    ELC_EVENT_GPT05_4_INT1                             = (243), // GPT05_4 selectedinterrupt 1
    ELC_EVENT_GPT05_4_INT2                             = (244), // GPT05_4 selectedinterrupt 2
    ELC_EVENT_GPT05_4_INT3                             = (245), // GPT05_4 selectedinterrupt 3
    ELC_EVENT_GPT05_4_INT4                             = (246), // GPT05_4 combinedinterrupt
    ELC_EVENT_GPT06_0_INT0                             = (247), // GPT06_0 selectedinterrupt 0
    ELC_EVENT_GPT06_0_INT1                             = (248), // GPT06_0 selectedinterrupt 1
    ELC_EVENT_GPT06_0_INT2                             = (249), // GPT06_0 selectedinterrupt 2
    ELC_EVENT_GPT06_0_INT3                             = (250), // GPT06_0 selectedinterrupt 3
    ELC_EVENT_GPT06_0_INT4                             = (251), // GPT06_0 combinedinterrupt
    ELC_EVENT_GPT06_1_INT0                             = (252), // GPT06_1 selectedinterrupt 0
    ELC_EVENT_GPT06_1_INT1                             = (253), // GPT06_1 selectedinterrupt 1
    ELC_EVENT_GPT06_1_INT2                             = (254), // GPT06_1 selectedinterrupt 2
    ELC_EVENT_GPT06_1_INT3                             = (255), // GPT06_1 selectedinterrupt 3
    ELC_EVENT_GPT06_1_INT4                             = (256), // GPT06_1 combinedinterrupt
    ELC_EVENT_GPT06_2_INT0                             = (257), // GPT06_2 selectedinterrupt 0
    ELC_EVENT_GPT06_2_INT1                             = (258), // GPT06_2 selectedinterrupt 1
    ELC_EVENT_GPT06_2_INT2                             = (259), // GPT06_2 selectedinterrupt 2
    ELC_EVENT_GPT06_2_INT3                             = (260), // GPT06_2 selectedinterrupt 3
    ELC_EVENT_GPT06_2_INT4                             = (261), // GPT06_2 combinedinterrupt
    ELC_EVENT_GPT06_3_INT0                             = (262), // GPT06_3 selectedinterrupt 0
    ELC_EVENT_GPT06_3_INT1                             = (263), // GPT06_3 selectedinterrupt 1
    ELC_EVENT_GPT06_3_INT2                             = (264), // GPT06_3 selectedinterrupt 2
    ELC_EVENT_GPT06_3_INT3                             = (265), // GPT06_3 selectedinterrupt 3
    ELC_EVENT_GPT06_3_INT4                             = (266), // GPT06_3 combinedinterrupt
    ELC_EVENT_GPT06_4_INT0                             = (267), // GPT06_4 selectedinterrupt 0
    ELC_EVENT_GPT06_4_INT1                             = (268), // GPT06_4 selectedinterrupt 1
    ELC_EVENT_GPT06_4_INT2                             = (269), // GPT06_4 selectedinterrupt 2
    ELC_EVENT_GPT06_4_INT3                             = (270), // GPT06_4 selectedinterrupt 3
    ELC_EVENT_GPT06_4_INT4                             = (271), // GPT06_4 combinedinterrupt
    ELC_EVENT_GPT07_0_INT0                             = (272), // GPT07_0 selectedinterrupt 0
    ELC_EVENT_GPT07_0_INT1                             = (273), // GPT07_0 selectedinterrupt 1
    ELC_EVENT_GPT07_0_INT2                             = (274), // GPT07_0 selectedinterrupt 2
    ELC_EVENT_GPT07_0_INT3                             = (275), // GPT07_0 selectedinterrupt 3
    ELC_EVENT_GPT07_0_INT4                             = (276), // GPT07_0 combinedinterrupt
    ELC_EVENT_GPT07_1_INT0                             = (277), // GPT07_1 selectedinterrupt 0
    ELC_EVENT_GPT07_1_INT1                             = (278), // GPT07_1 selectedinterrupt 1
    ELC_EVENT_GPT07_1_INT2                             = (279), // GPT07_1 selectedinterrupt 2
    ELC_EVENT_GPT07_1_INT3                             = (280), // GPT07_1 selectedinterrupt 3
    ELC_EVENT_GPT07_1_INT4                             = (281), // GPT07_1 combinedinterrupt
    ELC_EVENT_GPT07_2_INT0                             = (282), // GPT07_2 selectedinterrupt 0
    ELC_EVENT_GPT07_2_INT1                             = (283), // GPT07_2 selectedinterrupt 1
    ELC_EVENT_GPT07_2_INT2                             = (284), // GPT07_2 selectedinterrupt 2
    ELC_EVENT_GPT07_2_INT3                             = (285), // GPT07_2 selectedinterrupt 3
    ELC_EVENT_GPT07_2_INT4                             = (286), // GPT07_2 combinedinterrupt
    ELC_EVENT_GPT07_3_INT0                             = (287), // GPT07_3 selectedinterrupt 0
    ELC_EVENT_GPT07_3_INT1                             = (288), // GPT07_3 selectedinterrupt 1
    ELC_EVENT_GPT07_3_INT2                             = (289), // GPT07_3 selectedinterrupt 2
    ELC_EVENT_GPT07_3_INT3                             = (290), // GPT07_3 selectedinterrupt 3
    ELC_EVENT_GPT07_3_INT4                             = (291), // GPT07_3 combinedinterrupt
    ELC_EVENT_GPT07_4_INT0                             = (292), // GPT07_4 selectedinterrupt 0
    ELC_EVENT_GPT07_4_INT1                             = (293), // GPT07_4 selectedinterrupt 1
    ELC_EVENT_GPT07_4_INT2                             = (294), // GPT07_4 selectedinterrupt 2
    ELC_EVENT_GPT07_4_INT3                             = (295), // GPT07_4 selectedinterrupt 3
    ELC_EVENT_GPT07_4_INT4                             = (296), // GPT07_4 combinedinterrupt
    ELC_EVENT_GPT08_0_INT0                             = (297), // GPT08_0 selectedinterrupt 0
    ELC_EVENT_GPT08_0_INT1                             = (298), // GPT08_0 selectedinterrupt 1
    ELC_EVENT_GPT08_0_INT2                             = (299), // GPT08_0 selectedinterrupt 2
    ELC_EVENT_GPT08_0_INT3                             = (300), // GPT08_0 selectedinterrupt 3
    ELC_EVENT_GPT08_0_INT4                             = (301), // GPT08_0 combinedinterrupt
    ELC_EVENT_GPT08_1_INT0                             = (302), // GPT08_1 selectedinterrupt 0
    ELC_EVENT_GPT08_1_INT1                             = (303), // GPT08_1 selectedinterrupt 1
    ELC_EVENT_GPT08_1_INT2                             = (304), // GPT08_1 selectedinterrupt 2
    ELC_EVENT_GPT08_1_INT3                             = (305), // GPT08_1 selectedinterrupt 3
    ELC_EVENT_GPT08_1_INT4                             = (306), // GPT08_1 combinedinterrupt
    ELC_EVENT_GPT08_2_INT0                             = (307), // GPT08_2 selectedinterrupt 0
    ELC_EVENT_GPT08_2_INT1                             = (308), // GPT08_2 selectedinterrupt 1
    ELC_EVENT_GPT08_2_INT2                             = (309), // GPT08_2 selectedinterrupt 2
    ELC_EVENT_GPT08_2_INT3                             = (310), // GPT08_2 selectedinterrupt 3
    ELC_EVENT_GPT08_2_INT4                             = (311), // GPT08_2 combinedinterrupt
    ELC_EVENT_GPT08_3_INT0                             = (312), // GPT08_3 selectedinterrupt 0
    ELC_EVENT_GPT08_3_INT1                             = (313), // GPT08_3 selectedinterrupt 1
    ELC_EVENT_GPT08_3_INT2                             = (314), // GPT08_3 selectedinterrupt 2
    ELC_EVENT_GPT08_3_INT3                             = (315), // GPT08_3 selectedinterrupt 3
    ELC_EVENT_GPT08_3_INT4                             = (316), // GPT08_3 combinedinterrupt
    ELC_EVENT_GPT08_4_INT0                             = (317), // GPT08_4 selectedinterrupt 0
    ELC_EVENT_GPT08_4_INT1                             = (318), // GPT08_4 selectedinterrupt 1
    ELC_EVENT_GPT08_4_INT2                             = (319), // GPT08_4 selectedinterrupt 2
    ELC_EVENT_GPT08_4_INT3                             = (320), // GPT08_4 selectedinterrupt 3
    ELC_EVENT_GPT08_4_INT4                             = (321), // GPT08_4 combinedinterrupt
    ELC_EVENT_GPT09_0_INT0                             = (322), // GPT09_0 selectedinterrupt 0
    ELC_EVENT_GPT09_0_INT1                             = (323), // GPT09_0 selectedinterrupt 1
    ELC_EVENT_GPT09_0_INT2                             = (324), // GPT09_0 selectedinterrupt 2
    ELC_EVENT_GPT09_0_INT3                             = (325), // GPT09_0 selectedinterrupt 3
    ELC_EVENT_GPT09_0_INT4                             = (326), // GPT09_0 combinedinterrupt
    ELC_EVENT_GPT09_1_INT0                             = (327), // GPT09_1 selectedinterrupt 0
    ELC_EVENT_GPT09_1_INT1                             = (328), // GPT09_1 selectedinterrupt 1
    ELC_EVENT_GPT09_1_INT2                             = (329), // GPT09_1 selectedinterrupt 2
    ELC_EVENT_GPT09_1_INT3                             = (330), // GPT09_1 selectedinterrupt 3
    ELC_EVENT_GPT09_1_INT4                             = (331), // GPT09_1 combinedinterrupt
    ELC_EVENT_GPT09_2_INT0                             = (332), // GPT09_2 selectedinterrupt 0
    ELC_EVENT_GPT09_2_INT1                             = (333), // GPT09_2 selectedinterrupt 1
    ELC_EVENT_GPT09_2_INT2                             = (334), // GPT09_2 selectedinterrupt 2
    ELC_EVENT_GPT09_2_INT3                             = (335), // GPT09_2 selectedinterrupt 3
    ELC_EVENT_GPT09_2_INT4                             = (336), // GPT09_2 combinedinterrupt
    ELC_EVENT_GPT09_3_INT0                             = (337), // GPT09_3 selectedinterrupt 0
    ELC_EVENT_GPT09_3_INT1                             = (338), // GPT09_3 selectedinterrupt 1
    ELC_EVENT_GPT09_3_INT2                             = (339), // GPT09_3 selectedinterrupt 2
    ELC_EVENT_GPT09_3_INT3                             = (340), // GPT09_3 selectedinterrupt 3
    ELC_EVENT_GPT09_3_INT4                             = (341), // GPT09_3 combinedinterrupt
    ELC_EVENT_GPT09_4_INT0                             = (342), // GPT09_4 selectedinterrupt 0
    ELC_EVENT_GPT09_4_INT1                             = (343), // GPT09_4 selectedinterrupt 1
    ELC_EVENT_GPT09_4_INT2                             = (344), // GPT09_4 selectedinterrupt 2
    ELC_EVENT_GPT09_4_INT3                             = (345), // GPT09_4 selectedinterrupt 3
    ELC_EVENT_GPT09_4_INT4                             = (346), // GPT09_4 combinedinterrupt
    ELC_EVENT_GPT09_5_INT0                             = (347), // GPT09_5 selectedinterrupt 0
    ELC_EVENT_GPT09_5_INT1                             = (348), // GPT09_5 selectedinterrupt 1
    ELC_EVENT_GPT09_5_INT2                             = (349), // GPT09_5 selectedinterrupt 2
    ELC_EVENT_GPT09_5_INT3                             = (350), // GPT09_5 selectedinterrupt 3
    ELC_EVENT_GPT09_5_INT4                             = (351), // GPT09_5 combinedinterrupt
    ELC_EVENT_GPT09_6_INT0                             = (352), // GPT09_6 selectedinterrupt 0
    ELC_EVENT_GPT09_6_INT1                             = (353), // GPT09_6 selectedinterrupt 1
    ELC_EVENT_GPT09_6_INT2                             = (354), // GPT09_6 selectedinterrupt 2
    ELC_EVENT_GPT09_6_INT3                             = (355), // GPT09_6 selectedinterrupt 3
    ELC_EVENT_GPT09_6_INT4                             = (356), // GPT09_6 combinedinterrupt
    ELC_EVENT_GPT10_0_INT0                             = (357), // GPT10_0 selectedinterrupt 0
    ELC_EVENT_GPT10_0_INT1                             = (358), // GPT10_0 selectedinterrupt 1
    ELC_EVENT_GPT10_0_INT2                             = (359), // GPT10_0 selectedinterrupt 2
    ELC_EVENT_GPT10_0_INT3                             = (360), // GPT10_0 selectedinterrupt 3
    ELC_EVENT_GPT10_0_INT4                             = (361), // GPT10_0 combinedinterrupt
    ELC_EVENT_GPT10_1_INT0                             = (362), // GPT10_1 selectedinterrupt 0
    ELC_EVENT_GPT10_1_INT1                             = (363), // GPT10_1 selectedinterrupt 1
    ELC_EVENT_GPT10_1_INT2                             = (364), // GPT10_1 selectedinterrupt 2
    ELC_EVENT_GPT10_1_INT3                             = (365), // GPT10_1 selectedinterrupt 3
    ELC_EVENT_GPT10_1_INT4                             = (366), // GPT10_1 combinedinterrupt
    ELC_EVENT_GPT10_2_INT0                             = (367), // GPT10_2 selectedinterrupt 0
    ELC_EVENT_GPT10_2_INT1                             = (368), // GPT10_2 selectedinterrupt 1
    ELC_EVENT_GPT10_2_INT2                             = (369), // GPT10_2 selectedinterrupt 2
    ELC_EVENT_GPT10_2_INT3                             = (370), // GPT10_2 selectedinterrupt 3
    ELC_EVENT_GPT10_2_INT4                             = (371), // GPT10_2 combinedinterrupt
    ELC_EVENT_GPT10_3_INT0                             = (372), // GPT10_3 selectedinterrupt 0
    ELC_EVENT_GPT10_3_INT1                             = (373), // GPT10_3 selectedinterrupt 1
    ELC_EVENT_GPT10_3_INT2                             = (374), // GPT10_3 selectedinterrupt 2
    ELC_EVENT_GPT10_3_INT3                             = (375), // GPT10_3 selectedinterrupt 3
    ELC_EVENT_GPT10_3_INT4                             = (376), // GPT10_3 combinedinterrupt
    ELC_EVENT_MBX_INT0                                 = (377), // Mailbox (Host toCA55/CR52) interrupt0
    ELC_EVENT_MBX_INT1                                 = (378), // Mailbox (Host toCA55/CR52) interrupt1
    ELC_EVENT_MBX_INT2                                 = (379), // Mailbox (Host toCA55/CR52) interrupt2
    ELC_EVENT_MBX_INT3                                 = (380), // Mailbox (Host toCA55/CR52) interrupt3
    ELC_EVENT_MBX_INTAR0                               = (381), // Mailbox (CA55 toCR52_0) interrupt
    ELC_EVENT_MBX_INTR1R0                              = (382), // Mailbox (CR52_1 toCR52_0) interrupt
    ELC_EVENT_MBX_INTAR1                               = (383), // Mailbox (CA55 toCR52_1) interrupt
    ELC_EVENT_MBX_INTR0R1                              = (384), // Mailbox (CR52_0 toCR52_1) interrupt
    ELC_EVENT_MBX_INTR0A0                              = (385), // Mailbox (CR52_0 toCA55 core0) interrupt
    ELC_EVENT_MBX_INTR0A1                              = (386), // Mailbox (CR52_0 toCA55 core1) interrupt
    ELC_EVENT_MBX_INTR0A2                              = (387), // Mailbox (CR52_0 toCA55 core2) interrupt
    ELC_EVENT_MBX_INTR0A3                              = (388), // Mailbox (CR52_0 toCA55 core3) interrupt
    ELC_EVENT_MBX_INTR1A0                              = (389), // Mailbox (CR52_1 toCA55 core0) interrupt
    ELC_EVENT_MBX_INTR1A1                              = (390), // Mailbox (CR52_1 toCA55 core1) interrupt
    ELC_EVENT_MBX_INTR1A2                              = (391), // Mailbox (CR52_1 toCA55 core2) interrupt
    ELC_EVENT_MBX_INTR1A3                              = (392), // Mailbox (CR52_1 toCA55 core3) interrupt
    ELC_EVENT_MBX_INTA0A1                              = (393), // Mailbox (CA55 core0to CA55 core1)interrupt
    ELC_EVENT_MBX_INTA0A2                              = (394), // Mailbox (CA55 core0to CA55 core2)interrupt
    ELC_EVENT_MBX_INTA0A3                              = (395), // Mailbox (CA55 core0to CA55 core3)interrupt
    ELC_EVENT_MBX_INTA1A0                              = (396), // Mailbox (CA55 core1to CA55 core0)interrupt
    ELC_EVENT_MBX_INTA1A2                              = (397), // Mailbox (CA55 core1to CA55 core2)interrupt
    ELC_EVENT_MBX_INTA1A3                              = (398), // Mailbox (CA55 core1to CA55 core3)interrupt
    ELC_EVENT_MBX_INTA2A0                              = (399), // Mailbox (CA55 core2to CA55 core0)interrupt
    ELC_EVENT_MBX_INTA2A1                              = (400), // Mailbox (CA55 core2to CA55 core1)interrupt
    ELC_EVENT_MBX_INTA2A3                              = (401), // Mailbox (CA55 core2to CA55 core3)interrupt
    ELC_EVENT_MBX_INTA3A0                              = (402), // Mailbox (CA55 core3to CA55 core0)interrupt
    ELC_EVENT_MBX_INTA3A1                              = (403), // Mailbox (CA55 core3to CA55 core1)interrupt
    ELC_EVENT_MBX_INTA3A2                              = (404), // Mailbox (CA55 core3to CA55 core2)interrupt
    ELC_EVENT_nCLUSTERPMUIRQ                           = (405), // Cluster PMU interrupt request
    ELC_EVENT_SEI                                      = (406), // System error interrupt
    ELC_EVENT_CA55_ERR0                                = (407), // Cortex-A55 errorevent 0
    ELC_EVENT_CA55_ERR1                                = (408), // Cortex-A55 errorevent 1
    ELC_EVENT_CR520_ERR0                               = (409), // Cortex-R52 CPU0error event 0
    ELC_EVENT_CR520_ERR1                               = (410), // Cortex-R52 CPU0error event 1
    ELC_EVENT_CR521_ERR0                               = (411), // Cortex-R52 CPU1error event 0
    ELC_EVENT_CR521_ERR1                               = (412), // Cortex-R52 CPU1error event 1
    ELC_EVENT_PERI_ERR0                                = (413), // Peripherals errorevent 0
    ELC_EVENT_PERI_ERR1                                = (414), // Peripherals errorevent 1
    ELC_EVENT_DSMIF_ERR0                               = (415), // DSMIF error event 0
    ELC_EVENT_DSMIF_ERR1                               = (416), // DSMIF error event 1
    ELC_EVENT_ENCIF_ERR0                               = (417), // ENCIF error event 0
    ELC_EVENT_ENCIF_ERR1                               = (418), // ENCIF error event 1
    ELC_EVENT_BSC_CMI                                  = (419), // Refresh comparematch interrupt
    ELC_EVENT_TGIA0                                    = (420), // MTU0.TGRA inputcapture/comparematch
    ELC_EVENT_TGIB0                                    = (421), // MTU0.TGRB inputcapture/comparematch
    ELC_EVENT_TGIC0                                    = (422), // MTU0.TGRC inputcapture/comparematch
    ELC_EVENT_TGID0                                    = (423), // MTU0.TGRD inputcapture/comparematch
    ELC_EVENT_TCIV0                                    = (424), // MTU0.TCNT overflow
    ELC_EVENT_TGIE0                                    = (425), // MTU0.TGREcompare match
    ELC_EVENT_TGIF0                                    = (426), // MTU0.TGRFcompare match
    ELC_EVENT_TGIA1                                    = (427), // MTU1.TGRA inputcapture/comparematch
    ELC_EVENT_TGIB1                                    = (428), // MTU1.TGRB inputcapture/comparematch
    ELC_EVENT_TCIV1                                    = (429), // MTU1.TCNT overflow
    ELC_EVENT_TCIU1                                    = (430), // MTU1.TCNTunderflow
    ELC_EVENT_TGIA2                                    = (431), // MTU2.TGRA inputcapture/comparematch
    ELC_EVENT_TGIB2                                    = (432), // MTU2.TGRB inputcapture/comparematch
    ELC_EVENT_TCIV2                                    = (433), // MTU2.TCNT overflow
    ELC_EVENT_TCIU2                                    = (434), // MTU2.TCNTunderflow
    ELC_EVENT_TGIA3                                    = (435), // MTU3.TGRA inputcapture/comparematch
    ELC_EVENT_TGIB3                                    = (436), // MTU3.TGRB inputcapture/comparematch
    ELC_EVENT_TGIC3                                    = (437), // MTU3.TGRC inputcapture/comparematch
    ELC_EVENT_TGID3                                    = (438), // MTU3.TGRD inputcapture/comparematch
    ELC_EVENT_TCIV3                                    = (439), // MTU3.TCNT overflow
    ELC_EVENT_TGIA4                                    = (440), // MTU4.TGRA inputcapture/comparematch
    ELC_EVENT_TGIB4                                    = (441), // MTU4.TGRB inputcapture/comparematch
    ELC_EVENT_TGIC4                                    = (442), // MTU4.TGRC inputcapture/comparematch
    ELC_EVENT_TGID4                                    = (443), // MTU4.TGRD inputcapture/comparematch
    ELC_EVENT_TCIV4                                    = (444), // MTU4.TCNToverflow/underflow
    ELC_EVENT_TGIU5                                    = (445), // MTU5.TGRU inputcapture/comparematch
    ELC_EVENT_TGIV5                                    = (446), // MTU5.TGRV inputcapture/comparematch
    ELC_EVENT_TGIW5                                    = (447), // MTU5.TGRW inputcapture/comparematch
    ELC_EVENT_TGIA6                                    = (448), // MTU6.TGRA inputcapture/comparematch
    ELC_EVENT_TGIB6                                    = (449), // MTU6.TGRB inputcapture/comparematch
    ELC_EVENT_TGIC6                                    = (450), // MTU6.TGRC inputcapture/comparematch
    ELC_EVENT_TGID6                                    = (451), // MTU6.TGRD inputcapture/comparematch
    ELC_EVENT_TCIV6                                    = (452), // MTU6.TCNT overflow
    ELC_EVENT_TGIA7                                    = (453), // MTU7.TGRA inputcapture/comparematch
    ELC_EVENT_TGIB7                                    = (454), // MTU7.TGRB inputcapture/comparematch
    ELC_EVENT_TGIC7                                    = (455), // MTU7.TGRC inputcapture/comparematch
    ELC_EVENT_TGID7                                    = (456), // MTU7.TGRD inputcapture/comparematch
    ELC_EVENT_TCIV7                                    = (457), // MTU7.TCNToverflow/underflow*1
    ELC_EVENT_TGIA8                                    = (458), // MTU8.TGRA inputcapture/comparematch
    ELC_EVENT_TGIB8                                    = (459), // MTU8.TGRB inputcapture/comparematch
    ELC_EVENT_TGIC8                                    = (460), // MTU8.TGRC inputcapture/comparematch
    ELC_EVENT_TGID8                                    = (461), // MTU8.TGRD inputcapture/comparematch
    ELC_EVENT_TCIV8                                    = (462), // MTU8.TCNT overflow
    ELC_EVENT_OEI1                                     = (463), // Output enableinterrupt 1
    ELC_EVENT_OEI2                                     = (464), // Output enableinterrupt 2
    ELC_EVENT_OEI3                                     = (465), // Output enableinterrupt 3
    ELC_EVENT_OEI4                                     = (466), // Output enableinterrupt 4
    ELC_EVENT_POEG0_GROUP0                             = (467), // POEG group Ainterrupt for channelsin LLPP
    ELC_EVENT_POEG0_GROUP1                             = (468), // POEG group Binterrupt for channelsin LLPP
    ELC_EVENT_POEG0_GROUP2                             = (469), // POEG group Cinterrupt for channelsin LLPP
    ELC_EVENT_POEG0_GROUP3                             = (470), // POEG group Dinterrupt for channelsin LLPP
    ELC_EVENT_POEG1_GROUP0                             = (471), // POEG group Ainterrupt for channelsin NONSAFETY
    ELC_EVENT_POEG1_GROUP1                             = (472), // POEG group Binterrupt for channelsin NONSAFETY
    ELC_EVENT_POEG1_GROUP2                             = (473), // POEG group Cinterrupt for channelsin NONSAFETY
    ELC_EVENT_POEG1_GROUP3                             = (474), // POEG group Dinterrupt for channelsin NONSAFETY
    ELC_EVENT_POEG2_GROUP0                             = (475), // POEG group Ainterrupt for channelsin SAFETY
    ELC_EVENT_POEG2_GROUP1                             = (476), // POEG group Binterrupt for channelsin SAFETY
    ELC_EVENT_POEG2_GROUP2                             = (477), // POEG group Cinterrupt for channelsin SAFETY
    ELC_EVENT_POEG2_GROUP3                             = (478), // POEG group Dinterrupt for channelsin SAFETY
    ELC_EVENT_CMT0_CMI                                 = (479), // CMT0 Comparematch
    ELC_EVENT_CMT1_CMI                                 = (480), // CMT1 Comparematch
    ELC_EVENT_CMT2_CMI                                 = (481), // CMT2 Comparematch
    ELC_EVENT_CMT3_CMI                                 = (482), // CMT3 Comparematch
    ELC_EVENT_CMT4_CMI                                 = (483), // CMT4 Comparematch
    ELC_EVENT_CMT5_CMI                                 = (484), // CMT5 Comparematch
    ELC_EVENT_CMTW0_CMWI                               = (485), // CMTW0 Comparematch
    ELC_EVENT_CMTW0_IC0I                               = (486), // CMTW0 Inputcapture of register 0
    ELC_EVENT_CMTW0_IC1I                               = (487), // CMTW0 Inputcapture of register 1
    ELC_EVENT_CMTW0_OC0I                               = (488), // CMTW0 Outputcompare of register 0
    ELC_EVENT_CMTW0_OC1I                               = (489), // CMTW0 Outputcompare of register 1
    ELC_EVENT_CMTW1_CMWI                               = (490), // CMTW1 Comparematch
    ELC_EVENT_CMTW1_IC0I                               = (491), // CMTW1 Inputcapture of register 0
    ELC_EVENT_CMTW1_IC1I                               = (492), // CMTW1 Inputcapture of register 1
    ELC_EVENT_CMTW1_OC0I                               = (493), // CMTW1 Outputcompare of register 0
    ELC_EVENT_CMTW1_OC1I                               = (494), // CMTW1 Outputcompare of register 1
    ELC_EVENT_RTC_ALM                                  = (495), // Alarm interrupt
    ELC_EVENT_RTC_1S                                   = (496), // 1 second interrupt
    ELC_EVENT_RTC_PRD                                  = (497), // Fixed intervalinterrupt
    ELC_EVENT_GMAC0_sbd_intr_o                         = (498), // GMAC0 Subsysteminterrupt
    ELC_EVENT_GMAC0_lpi_intr_o                         = (499), // GMAC0 LPI interrupt
    ELC_EVENT_GMAC0_pmt_intr_o                         = (500), // GMAC0 PMTInterrupt
    ELC_EVENT_GMAC0_sbd_perch_tx_intr_o0               = (501), // GMAC0 Per channelTransmit Interrupt 0
    ELC_EVENT_GMAC0_sbd_perch_tx_intr_o1               = (502), // GMAC0 Per channelTransmit Interrupt 1
    ELC_EVENT_GMAC0_sbd_perch_tx_intr_o2               = (503), // GMAC0 Per channelTransmit Interrupt 2
    ELC_EVENT_GMAC0_sbd_perch_tx_intr_o3               = (504), // GMAC0 Per channelTransmit Interrupt 3
    ELC_EVENT_GMAC0_sbd_perch_tx_intr_o4               = (505), // GMAC0 Per channelTransmit Interrupt 4
    ELC_EVENT_GMAC0_sbd_perch_tx_intr_o5               = (506), // GMAC0 Per channelTransmit Interrupt 5
    ELC_EVENT_GMAC0_sbd_perch_tx_intr_o6               = (507), // GMAC0 Per channelTransmit Interrupt 6
    ELC_EVENT_GMAC0_sbd_perch_tx_intr_o7               = (508), // GMAC0 Per channelTransmit Interrupt 7
    ELC_EVENT_GMAC0_sbd_perch_rx_intr_o0               = (509), // GMAC0 Per channelReceive Interrupt 0
    ELC_EVENT_GMAC0_sbd_perch_rx_intr_o1               = (510), // GMAC0 Per channelReceive Interrupt 1
    ELC_EVENT_GMAC0_sbd_perch_rx_intr_o2               = (511), // GMAC0 Per channelReceive Interrupt 2
    ELC_EVENT_GMAC0_sbd_perch_rx_intr_o3               = (512), // GMAC0 Per channelReceive Interrupt 3
    ELC_EVENT_GMAC0_sbd_perch_rx_intr_o4               = (513), // GMAC0 Per channelReceive Interrupt 4
    ELC_EVENT_GMAC0_sbd_perch_rx_intr_o5               = (514), // GMAC0 Per channelReceive Interrupt 5
    ELC_EVENT_GMAC0_sbd_perch_rx_intr_o6               = (515), // GMAC0 Per channelReceive Interrupt 6
    ELC_EVENT_GMAC0_sbd_perch_rx_intr_o7               = (516), // GMAC0 Per channelReceive Interrupt 7
    ELC_EVENT_GMAC1_sbd_intr_o                         = (517), // GMAC1 Subsysteminterrupt
    ELC_EVENT_GMAC1_lpi_intr_o                         = (518), // GMAC1 LPI interrupt
    ELC_EVENT_GMAC1_pmt_intr_o                         = (519), // GMAC1 PMTInterrupt
    ELC_EVENT_GMAC1_sbd_perch_tx_intr_o0               = (520), // GMAC1 Per channelTransmit Interrupt 0
    ELC_EVENT_GMAC1_sbd_perch_tx_intr_o1               = (521), // GMAC1 Per channelTransmit Interrupt 1
    ELC_EVENT_GMAC1_sbd_perch_tx_intr_o2               = (522), // GMAC1 Per channelTransmit Interrupt 2
    ELC_EVENT_GMAC1_sbd_perch_tx_intr_o3               = (523), // GMAC1 Per channelTransmit Interrupt 3
    ELC_EVENT_GMAC1_sbd_perch_tx_intr_o4               = (524), // GMAC1 Per channelTransmit Interrupt 4
    ELC_EVENT_GMAC1_sbd_perch_tx_intr_o5               = (525), // GMAC1 Per channelTransmit Interrupt 5
    ELC_EVENT_GMAC1_sbd_perch_tx_intr_o6               = (526), // GMAC1 Per channelTransmit Interrupt 6
    ELC_EVENT_GMAC1_sbd_perch_tx_intr_o7               = (527), // GMAC1 Per channelTransmit Interrupt 7
    ELC_EVENT_GMAC1_sbd_perch_rx_intr_o0               = (528), // GMAC1 Per channelReceive Interrupt 0
    ELC_EVENT_GMAC1_sbd_perch_rx_intr_o1               = (529), // GMAC1 Per channelReceive Interrupt 1
    ELC_EVENT_GMAC1_sbd_perch_rx_intr_o2               = (530), // GMAC1 Per channelReceive Interrupt 2
    ELC_EVENT_GMAC1_sbd_perch_rx_intr_o3               = (531), // GMAC1 Per channelReceive Interrupt 3
    ELC_EVENT_GMAC1_sbd_perch_rx_intr_o4               = (532), // GMAC1 Per channelReceive Interrupt 4
    ELC_EVENT_GMAC1_sbd_perch_rx_intr_o5               = (533), // GMAC1 Per channelReceive Interrupt 5
    ELC_EVENT_GMAC1_sbd_perch_rx_intr_o6               = (534), // GMAC1 Per channelReceive Interrupt 6
    ELC_EVENT_GMAC1_sbd_perch_rx_intr_o7               = (535), // GMAC1 Per channelReceive Interrupt 7
    ELC_EVENT_GMAC2_sbd_intr_o                         = (536), // GMAC2 Subsysteminterrupt
    ELC_EVENT_GMAC2_lpi_intr_o                         = (537), // GMAC2 LPI interrupt
    ELC_EVENT_GMAC2_pmt_intr_o                         = (538), // GMAC2 PMTInterrupt
    ELC_EVENT_GMAC2_sbd_perch_tx_intr_o0               = (539), // GMAC2 Per channelTransmit Interrupt 0
    ELC_EVENT_GMAC2_sbd_perch_tx_intr_o1               = (540), // GMAC2 Per channelTransmit Interrupt 1
    ELC_EVENT_GMAC2_sbd_perch_tx_intr_o2               = (541), // GMAC2 Per channelTransmit Interrupt 2
    ELC_EVENT_GMAC2_sbd_perch_tx_intr_o3               = (542), // GMAC2 Per channelTransmit Interrupt 3
    ELC_EVENT_GMAC2_sbd_perch_tx_intr_o4               = (543), // GMAC2 Per channelTransmit Interrupt 4
    ELC_EVENT_GMAC2_sbd_perch_tx_intr_o5               = (544), // GMAC2 Per channelTransmit Interrupt 5
    ELC_EVENT_GMAC2_sbd_perch_tx_intr_o6               = (545), // GMAC2 Per channelTransmit Interrupt 6
    ELC_EVENT_GMAC2_sbd_perch_tx_intr_o7               = (546), // GMAC2 Per channelTransmit Interrupt 7
    ELC_EVENT_GMAC2_sbd_perch_rx_intr_o0               = (547), // GMAC2 Per channelReceive Interrupt 0
    ELC_EVENT_GMAC2_sbd_perch_rx_intr_o1               = (548), // GMAC2 Per channelReceive Interrupt 1
    ELC_EVENT_GMAC2_sbd_perch_rx_intr_o2               = (549), // GMAC2 Per channelReceive Interrupt 2
    ELC_EVENT_GMAC2_sbd_perch_rx_intr_o3               = (550), // GMAC2 Per channelReceive Interrupt 3
    ELC_EVENT_GMAC2_sbd_perch_rx_intr_o4               = (551), // GMAC2 Per channelReceive Interrupt 4
    ELC_EVENT_GMAC2_sbd_perch_rx_intr_o5               = (552), // GMAC2 Per channelReceive Interrupt 5
    ELC_EVENT_GMAC2_sbd_perch_rx_intr_o6               = (553), // GMAC2 Per channelReceive Interrupt 6
    ELC_EVENT_GMAC2_sbd_perch_rx_intr_o7               = (554), // GMAC2 Per channelReceive Interrupt 7
    ELC_EVENT_ETHSW_INTR                               = (555), // Ethernet Switchinterrupt
    ELC_EVENT_ETHSW_DLR                                = (556), // Ethernet Switch DLRinterrupt
    ELC_EVENT_ETHSW_PRP                                = (557), // Ethernet Switch PRPinterrupt
    ELC_EVENT_ETHSW_IHUB                               = (558), // Ethernet SwitchIntegrated Hubinterrupt
    ELC_EVENT_ETHSW_PTRN0                              = (559), // Ethernet Switch RXPattern Matcherinterrupt 0
    ELC_EVENT_ETHSW_PTRN1                              = (560), // Ethernet Switch RXPattern Matcherinterrupt 1
    ELC_EVENT_ETHSW_PTRN2                              = (561), // Ethernet Switch RXPattern Matcherinterrupt 2
    ELC_EVENT_ETHSW_PTRN3                              = (562), // Ethernet Switch RXPattern Matcherinterrupt 3
    ELC_EVENT_ETHSW_PTRN4                              = (563), // Ethernet Switch RXPattern Matcherinterrupt 4
    ELC_EVENT_ETHSW_PTRN5                              = (564), // Ethernet Switch RXPattern Matcherinterrupt 5
    ELC_EVENT_ETHSW_PTRN6                              = (565), // Ethernet Switch RXPattern Matcherinterrupt 6
    ELC_EVENT_ETHSW_PTRN7                              = (566), // Ethernet Switch RXPattern Matcherinterrupt 7
    ELC_EVENT_ETHSW_PTRN8                              = (567), // Ethernet Switch RXPattern Matcherinterrupt 8
    ELC_EVENT_ETHSW_PTRN9                              = (568), // Ethernet Switch RXPattern Matcherinterrupt 9
    ELC_EVENT_ETHSW_PTRN10                             = (569), // Ethernet Switch RXPattern Matcherinterrupt 10
    ELC_EVENT_ETHSW_PTRN11                             = (570), // Ethernet Switch RXPattern Matcherinterrupt 11
    ELC_EVENT_ETHSW_PTPOUT0                            = (571), // Ethernet switch timerpulse output 0
    ELC_EVENT_ETHSW_PTPOUT1                            = (572), // Ethernet switch timerpulse output 1
    ELC_EVENT_ETHSW_PTPOUT2                            = (573), // Ethernet switch timerpulse output 2
    ELC_EVENT_ETHSW_PTPOUT3                            = (574), // Ethernet switch timerpulse output 3
    ELC_EVENT_ETHSW_TDMAOUT0                           = (575), // Ethernet SwitchTDMA timer output 0
    ELC_EVENT_ETHSW_TDMAOUT1                           = (576), // Ethernet SwitchTDMA timer output 1
    ELC_EVENT_ETHSW_TDMAOUT2                           = (577), // Ethernet SwitchTDMA timer output 2
    ELC_EVENT_ETHSW_TDMAOUT3                           = (578), // Ethernet SwitchTDMA timer output 3
    ELC_EVENT_ESC_SYNC0                                = (579), // EtherCAT Sync0interrupt
    ELC_EVENT_ESC_SYNC1                                = (580), // EtherCAT Sync1interrupt
    ELC_EVENT_ESC_CAT                                  = (581), // EtherCAT interrupt
    ELC_EVENT_ESC_SOF                                  = (582), // EtherCAT SOFinterrupt
    ELC_EVENT_ESC_EOF                                  = (583), // EtherCAT EOFinterrupt
    ELC_EVENT_ESC_WDT                                  = (584), // EtherCAT WDTinterrupt
    ELC_EVENT_ESC_RST                                  = (585), // EtherCAT RESETinterrupt
    ELC_EVENT_USB_HI                                   = (586), // USB (Host) interrupt
    ELC_EVENT_USB_FI                                   = (587), // USB (Function)interrupt
    ELC_EVENT_USB_FDMA0                                = (588), // USB (Function) DMA0 transmit completion
    ELC_EVENT_USB_FDMA1                                = (589), // USB (Function) DMA1 transmit completion
    ELC_EVENT_SCI0_ERI                                 = (590), // SCI0 Receive error
    ELC_EVENT_SCI0_RXI                                 = (591), // SCI0 Receive datafull
    ELC_EVENT_SCI0_TXI                                 = (592), // SCI0 Transmit dataempty
    ELC_EVENT_SCI0_TEI                                 = (593), // SCI0 Transmit end
    ELC_EVENT_SCI1_ERI                                 = (594), // SCI1 Receive error
    ELC_EVENT_SCI1_RXI                                 = (595), // SCI1 Receive datafull
    ELC_EVENT_SCI1_TXI                                 = (596), // SCI1 Transmit dataempty
    ELC_EVENT_SCI1_TEI                                 = (597), // SCI1 Transmit end
    ELC_EVENT_SCI2_ERI                                 = (598), // SCI2 Receive error
    ELC_EVENT_SCI2_RXI                                 = (599), // SCI2 Receive datafull
    ELC_EVENT_SCI2_TXI                                 = (600), // SCI2 Transmit dataempty
    ELC_EVENT_SCI2_TEI                                 = (601), // SCI2 Transmit end
    ELC_EVENT_SCI3_ERI                                 = (602), // SCI3 Receive error
    ELC_EVENT_SCI3_RXI                                 = (603), // SCI3 Receive datafull
    ELC_EVENT_SCI3_TXI                                 = (604), // SCI3 Transmit dataempty
    ELC_EVENT_SCI3_TEI                                 = (605), // SCI3 Transmit end
    ELC_EVENT_SCI4_ERI                                 = (606), // SCI4 Receive error
    ELC_EVENT_SCI4_RXI                                 = (607), // SCI4 Receive datafull
    ELC_EVENT_SCI4_TXI                                 = (608), // SCI4 Transmit dataempty
    ELC_EVENT_SCI4_TEI                                 = (609), // SCI4 Transmit end
    ELC_EVENT_SCI5_ERI                                 = (610), // SCI5 Receive error
    ELC_EVENT_SCI5_RXI                                 = (611), // SCI5 Receive datafull
    ELC_EVENT_SCI5_TXI                                 = (612), // SCI5 Transmit dataempty
    ELC_EVENT_SCI5_TEI                                 = (613), // SCI5 Transmit end
    ELC_EVENT_IIC0_EEI                                 = (614), // IIC0 Transfer error orevent generation
    ELC_EVENT_IIC0_RXI                                 = (615), // IIC0 Receive data full
    ELC_EVENT_IIC0_TXI                                 = (616), // IIC0 Transmit dataempty
    ELC_EVENT_IIC0_TEI                                 = (617), // IIC0 Transmit end
    ELC_EVENT_IIC1_EEI                                 = (618), // IIC1 Transfer error orevent generation
    ELC_EVENT_IIC1_RXI                                 = (619), // IIC1 Receive data full
    ELC_EVENT_IIC1_TXI                                 = (620), // IIC1 Transmit dataempty
    ELC_EVENT_IIC1_TEI                                 = (621), // IIC1 Transmit end
    ELC_EVENT_IIC2_EEI                                 = (622), // IIC2 Transfer error orevent generation
    ELC_EVENT_IIC2_RXI                                 = (623), // IIC2 Receive data full
    ELC_EVENT_IIC2_TXI                                 = (624), // IIC2 Transmit dataempty
    ELC_EVENT_IIC2_TEI                                 = (625), // IIC2 Transmit end
    ELC_EVENT_CAN0_TX                                  = (626), // CAFND0 Channel TXinterrupt
    ELC_EVENT_CAN0_CHERR                               = (627), // CAFND0 ChannelCAN error interrupt
    ELC_EVENT_CAN0_COMFRX                              = (628), // CAFND0 CommonRX FIFO or TXQinterrupt
    ELC_EVENT_CAN1_TX                                  = (629), // CAFND1 Channel TXinterrupt
    ELC_EVENT_CAN1_CHERR                               = (630), // CAFND1 ChannelCAN error interrupt
    ELC_EVENT_CAN1_COMFRX                              = (631), // CAFND1 CommonRX FIFO or TXQinterrupt
    ELC_EVENT_CAN_RXF                                  = (632), // CANFD RX FIFO interrupt
    ELC_EVENT_CAN_GLERR                                = (633), // CANFD Global error Interrupt
    ELC_EVENT_SPI0_SPRI                                = (634), // SPI0 Reception buffer full
    ELC_EVENT_SPI0_SPTI                                = (635), // SPI0 Transmit bufferempty
    ELC_EVENT_SPI0_SPII                                = (636), // SPI0 SPI idle
    ELC_EVENT_SPI0_SPEI                                = (637), // SPI0 errors (mode fault,underrun, overrun, parity error,and received data ready)
    ELC_EVENT_SPI0_SPCEND                              = (638), // SPI0 Communicationcomplete
    ELC_EVENT_SPI1_SPRI                                = (639), // SPI1 Reception buffer full
    ELC_EVENT_SPI1_SPTI                                = (640), // SPI1 Transmit bufferempty
    ELC_EVENT_SPI1_SPII                                = (641), // SPI1 SPI idle
    ELC_EVENT_SPI1_SPEI                                = (642), // SPI1 errors (mode fault,underrun, overrun, parity error,and received data ready)
    ELC_EVENT_SPI1_SPCEND                              = (643), // SPI1 Communicationcomplete
    ELC_EVENT_SPI2_SPRI                                = (644), // SPI2 Reception buffer full
    ELC_EVENT_SPI2_SPTI                                = (645), // SPI2 Transmit bufferempty
    ELC_EVENT_SPI2_SPII                                = (646), // SPI2 SPI idle
    ELC_EVENT_SPI2_SPEI                                = (647), // SPI2 errors (mode fault,underrun, overrun, parity error,and received data ready)
    ELC_EVENT_SPI2_SPCEND                              = (648), // SPI2 Communicationcomplete
    ELC_EVENT_SPI3_SPRI                                = (649), // SPI3 Reception buffer full
    ELC_EVENT_SPI3_SPTI                                = (650), // SPI3 Transmit bufferempty
    ELC_EVENT_SPI3_SPII                                = (651), // SPI3 SPI idle
    ELC_EVENT_SPI3_SPEI                                = (652), // SPI3 errors (mode fault,underrun, overrun, parity error,and received data ready)
    ELC_EVENT_SPI3_SPCEND                              = (653), // SPI3 Communicationcomplete
    ELC_EVENT_XSPI0_INT                                = (654), // xSPI0 Interrupt
    ELC_EVENT_XSPI0_INTERR                             = (655), // xSPI0 Error interrupt
    ELC_EVENT_XSPI1_INT                                = (656), // xSPI1 Interrupt
    ELC_EVENT_XSPI1_INTERR                             = (657), // xSPI1 Error interrupt
    ELC_EVENT_DSMIF0_CDRUI                             = (658), // DSMIF0 Current Dataregister Update(Combined with ch0to ch2)
    ELC_EVENT_DSMIF0_CDUPDC                            = (659), // DSMIF0 Current Dataregister UpdateCommon
    ELC_EVENT_DSMIF0_CDACUPDC                          = (660), // DSMIF0 CurrentCapture Data registerA Update Common
    ELC_EVENT_DSMIF0_CDBCUPDC                          = (661), // DSMIF0 CurrentCapture Data registerB Update Common
    ELC_EVENT_DSMIF1_CDRUI                             = (662), // DSMIF1 Current Dataregister Update(Combined with ch0to ch2)
    ELC_EVENT_DSMIF1_CDUPDC                            = (663), // DSMIF1 Current Dataregister UpdateCommon
    ELC_EVENT_DSMIF1_CDACUPDC                          = (664), // DSMIF1 CurrentCapture Data registerA Update Common
    ELC_EVENT_DSMIF1_CDBCUPDC                          = (665), // DSMIF1 CurrentCapture Data registerB Update Common
    ELC_EVENT_DSMIF2_CDRUI                             = (666), // DSMIF2 Current Dataregister Update(Combined with ch0to ch2)
    ELC_EVENT_DSMIF2_CDUPDC                            = (667), // DSMIF2 Current Dataregister UpdateCommon
    ELC_EVENT_DSMIF2_CDACUPDC                          = (668), // DSMIF2 CurrentCapture Data registerA Update Common
    ELC_EVENT_DSMIF2_CDBCUPDC                          = (669), // DSMIF2 CurrentCapture Data registerB Update Common
    ELC_EVENT_DSMIF3_CDRUI                             = (670), // DSMIF3 Current Dataregister Update(Combined with ch0to ch2)
    ELC_EVENT_DSMIF3_CDUPDC                            = (671), // DSMIF3 Current Dataregister UpdateCommon
    ELC_EVENT_DSMIF3_CDACUPDC                          = (672), // DSMIF3 CurrentCapture Data registerA Update Common
    ELC_EVENT_DSMIF3_CDBCUPDC                          = (673), // DSMIF3 CurrentCapture Data registerB Update Common
    ELC_EVENT_DSMIF4_CDRUI                             = (674), // DSMIF4 Current Dataregister Update(Combined with ch0to ch2)
    ELC_EVENT_DSMIF4_CDUPDC                            = (675), // DSMIF4 Current Dataregister UpdateCommon
    ELC_EVENT_DSMIF4_CDACUPDC                          = (676), // DSMIF4 CurrentCapture Data registerA Update Common
    ELC_EVENT_DSMIF4_CDBCUPDC                          = (677), // DSMIF4 CurrentCapture Data registerB Update Common
    ELC_EVENT_DSMIF5_CDRUI                             = (678), // DSMIF5 Current Dataregister Update(Combined with ch0to ch2)
    ELC_EVENT_DSMIF5_CDUPDC                            = (679), // DSMIF5 Current Dataregister UpdateCommon
    ELC_EVENT_DSMIF5_CDACUPDC                          = (680), // DSMIF5 CurrentCapture Data registerA Update Common
    ELC_EVENT_DSMIF5_CDBCUPDC                          = (681), // DSMIF5 CurrentCapture Data registerB Update Common
    ELC_EVENT_DSMIF6_CDRUI                             = (682), // DSMIF6 Current Dataregister Update(Combined with ch0to ch2)
    ELC_EVENT_DSMIF6_CDUPDC                            = (683), // DSMIF6 Current Dataregister UpdateCommon
    ELC_EVENT_DSMIF6_CDACUPDC                          = (684), // DSMIF6 CurrentCapture Data registerA Update Common
    ELC_EVENT_DSMIF6_CDBCUPDC                          = (685), // DSMIF6 CurrentCapture Data registerB Update Common
    ELC_EVENT_DSMIF7_CDRUI                             = (686), // DSMIF7 Current Dataregister Update(Combined with ch0to ch2)
    ELC_EVENT_DSMIF7_CDUPDC                            = (687), // DSMIF7 Current Dataregister UpdateCommon
    ELC_EVENT_DSMIF7_CDACUPDC                          = (688), // DSMIF7 CurrentCapture Data registerA Update Common
    ELC_EVENT_DSMIF7_CDBCUPDC                          = (689), // DSMIF7 CurrentCapture Data registerB Update Common
    ELC_EVENT_DSMIF8_CDRUI                             = (690), // DSMIF8 Current Dataregister Update(Combined with ch0to ch2)
    ELC_EVENT_DSMIF8_CDUPDC                            = (691), // DSMIF8 Current Dataregister UpdateCommon
    ELC_EVENT_DSMIF8_CDACUPDC                          = (692), // DSMIF8 CurrentCapture Data registerA Update Common
    ELC_EVENT_DSMIF8_CDBCUPDC                          = (693), // DSMIF8 CurrentCapture Data registerB Update Common
    ELC_EVENT_DSMIF9_CDRUI                             = (694), // DSMIF9 Current Dataregister Update(Combined with ch0to ch2)
    ELC_EVENT_DSMIF9_CDUPDC                            = (695), // DSMIF9 Current Dataregister UpdateCommon
    ELC_EVENT_DSMIF9_CDACUPDC                          = (696), // DSMIF9 CurrentCapture Data registerA Update Common
    ELC_EVENT_DSMIF9_CDBCUPDC                          = (697), // DSMIF9 CurrentCapture Data registerB Update Common
    ELC_EVENT_ADC120_ADI                               = (698), // ADC120 A/D scanend interrupt
    ELC_EVENT_ADC120_GBADI                             = (699), // ADC120 A/D scanend interrupt forGroup B
    ELC_EVENT_ADC120_GCADI                             = (700), // ADC120 A/D scanend interrupt forGroup C
    ELC_EVENT_ADC120_CMPAI                             = (701), // ADC120 Window Acompare match
    ELC_EVENT_ADC120_CMPBI                             = (702), // ADC120 Window Bcompare match
    ELC_EVENT_ADC121_ADI                               = (703), // ADC121 A/D scanend interrupt
    ELC_EVENT_ADC121_GBADI                             = (704), // ADC121 A/D scanend interrupt forGroup B
    ELC_EVENT_ADC121_GCADI                             = (705), // ADC121 A/D scanend interrupt forGroup C
    ELC_EVENT_ADC121_CMPAI                             = (706), // ADC121 Window Acompare match
    ELC_EVENT_ADC121_CMPBI                             = (707), // ADC121 Window Bcompare match
    ELC_EVENT_ADC122_ADI                               = (708), // ADC122 A/D scanend interrupt
    ELC_EVENT_ADC122_GBADI                             = (709), // ADC122 A/D scanend interrupt forGroup B
    ELC_EVENT_ADC122_GCADI                             = (710), // ADC122 A/D scanend interrupt forGroup C
    ELC_EVENT_ADC122_CMPAI                             = (711), // ADC122 Window Acompare match
    ELC_EVENT_ADC122_CMPBI                             = (712), // ADC122 Window Bcompare match
    ELC_EVENT_TSU0_ADI                                 = (713), // A/D conversion-end
    ELC_EVENT_TSU0_ADCMPI                              = (714), // Window comparematch
    ELC_EVENT_SHOST_INT                                = (715), // SHOSTIF interrupt
    ELC_EVENT_ENCIF00_INT0                             = (716), // ENCIF00 combinedinterrupt 0
    ELC_EVENT_ENCIF00_INT1                             = (717), // ENCIF00 combinedinterrupt 1
    ELC_EVENT_ENCIF00_INT2                             = (718), // ENCIF00 combinedinterrupt 2
    ELC_EVENT_ENCIF00_INT3                             = (719), // ENCIF00 combinedinterrupt 3
    ELC_EVENT_ENCIF01_INT0                             = (720), // ENCIF01 combinedinterrupt 0
    ELC_EVENT_ENCIF01_INT1                             = (721), // ENCIF01 combinedinterrupt 1
    ELC_EVENT_ENCIF01_INT2                             = (722), // ENCIF01 combinedinterrupt 2
    ELC_EVENT_ENCIF01_INT3                             = (723), // ENCIF01 combinedinterrupt 3
    ELC_EVENT_ENCIF02_INT0                             = (724), // ENCIF02 combinedinterrupt 0
    ELC_EVENT_ENCIF02_INT1                             = (725), // ENCIF02 combinedinterrupt 1
    ELC_EVENT_ENCIF02_INT2                             = (726), // ENCIF02 combinedinterrupt 2
    ELC_EVENT_ENCIF02_INT3                             = (727), // ENCIF02 combinedinterrupt 3
    ELC_EVENT_ENCIF03_INT0                             = (728), // ENCIF03 combinedinterrupt 0
    ELC_EVENT_ENCIF03_INT1                             = (729), // ENCIF03 combinedinterrupt 1
    ELC_EVENT_ENCIF03_INT2                             = (730), // ENCIF03 combinedinterrupt 2
    ELC_EVENT_ENCIF03_INT3                             = (731), // ENCIF03 combinedinterrupt 3
    ELC_EVENT_ENCIF04_INT0                             = (732), // ENCIF04 combinedinterrupt 0
    ELC_EVENT_ENCIF04_INT1                             = (733), // ENCIF04 combinedinterrupt 1
    ELC_EVENT_ENCIF04_INT2                             = (734), // ENCIF04 combinedinterrupt 2
    ELC_EVENT_ENCIF04_INT3                             = (735), // ENCIF04 combinedinterrupt 3
    ELC_EVENT_ENCIF05_INT0                             = (736), // ENCIF05 combinedinterrupt 0
    ELC_EVENT_ENCIF05_INT1                             = (737), // ENCIF05 combinedinterrupt 1
    ELC_EVENT_ENCIF05_INT2                             = (738), // ENCIF05 combinedinterrupt 2
    ELC_EVENT_ENCIF05_INT3                             = (739), // ENCIF05 combinedinterrupt 3
    ELC_EVENT_ENCIF06_INT0                             = (740), // ENCIF06 combinedinterrupt 0
    ELC_EVENT_ENCIF06_INT1                             = (741), // ENCIF06 combinedinterrupt 1
    ELC_EVENT_ENCIF06_INT2                             = (742), // ENCIF06 combinedinterrupt 2
    ELC_EVENT_ENCIF06_INT3                             = (743), // ENCIF06 combinedinterrupt 3
    ELC_EVENT_ENCIF07_INT0                             = (744), // ENCIF07 combinedinterrupt 0
    ELC_EVENT_ENCIF07_INT1                             = (745), // ENCIF07 combinedinterrupt 1
    ELC_EVENT_ENCIF07_INT2                             = (746), // ENCIF07 combinedinterrupt 2
    ELC_EVENT_ENCIF07_INT3                             = (747), // ENCIF07 combinedinterrupt 3
    ELC_EVENT_ENCIF08_INT0                             = (748), // ENCIF08 combinedinterrupt 0
    ELC_EVENT_ENCIF08_INT1                             = (749), // ENCIF08 combinedinterrupt 1
    ELC_EVENT_ENCIF08_INT2                             = (750), // ENCIF08 combinedinterrupt 2
    ELC_EVENT_ENCIF08_INT3                             = (751), // ENCIF08 combinedinterrupt 3
    ELC_EVENT_ENCIF09_INT0                             = (752), // ENCIF09 combinedinterrupt 0
    ELC_EVENT_ENCIF09_INT1                             = (753), // ENCIF09 combinedinterrupt 1
    ELC_EVENT_ENCIF09_INT2                             = (754), // ENCIF09 combinedinterrupt 2
    ELC_EVENT_ENCIF09_INT3                             = (755), // ENCIF09 combinedinterrupt 3
    ELC_EVENT_ENCIF10_INT0                             = (756), // ENCIF10 combinedinterrupt 0
    ELC_EVENT_ENCIF10_INT1                             = (757), // ENCIF10 combinedinterrupt 1
    ELC_EVENT_ENCIF10_INT2                             = (758), // ENCIF10 combinedinterrupt 2
    ELC_EVENT_ENCIF10_INT3                             = (759), // ENCIF10 combinedinterrupt 3
    ELC_EVENT_ENCIF11_INT0                             = (760), // ENCIF11 combinedinterrupt 0
    ELC_EVENT_ENCIF11_INT1                             = (761), // ENCIF11 combinedinterrupt 1
    ELC_EVENT_ENCIF11_INT2                             = (762), // ENCIF11 combinedinterrupt 2
    ELC_EVENT_ENCIF11_INT3                             = (763), // ENCIF11 combinedinterrupt 3
    ELC_EVENT_ENCIF12_INT0                             = (764), // ENCIF12 combinedinterrupt 0
    ELC_EVENT_ENCIF12_INT1                             = (765), // ENCIF12 combinedinterrupt 1
    ELC_EVENT_ENCIF12_INT2                             = (766), // ENCIF12 combinedinterrupt 2
    ELC_EVENT_ENCIF12_INT3                             = (767), // ENCIF12 combinedinterrupt 3
    ELC_EVENT_ENCIF13_INT0                             = (768), // ENCIF13 combinedinterrupt 0
    ELC_EVENT_ENCIF13_INT1                             = (769), // ENCIF13 combinedinterrupt 1
    ELC_EVENT_ENCIF13_INT2                             = (770), // ENCIF13 combinedinterrupt 2
    ELC_EVENT_ENCIF13_INT3                             = (771), // ENCIF13 combinedinterrupt 3
    ELC_EVENT_ENCIF14_INT0                             = (772), // ENCIF14 combinedinterrupt 0
    ELC_EVENT_ENCIF14_INT1                             = (773), // ENCIF14 combinedinterrupt 1
    ELC_EVENT_ENCIF14_INT2                             = (774), // ENCIF14 combinedinterrupt 2
    ELC_EVENT_ENCIF14_INT3                             = (775), // ENCIF14 combinedinterrupt 3
    ELC_EVENT_ENCIF15_INT0                             = (776), // ENCIF15 combinedinterrupt 0
    ELC_EVENT_ENCIF15_INT1                             = (777), // ENCIF15 combinedinterrupt 1
    ELC_EVENT_ENCIF15_INT2                             = (778), // ENCIF15 combinedinterrupt 2
    ELC_EVENT_ENCIF15_INT3                             = (779), // ENCIF15 combinedinterrupt 3
    ELC_EVENT_LCDC_VSPD_INT                            = (780), // LCDC VSPD interrupt
    ELC_EVENT_LCDC_DU_INT                              = (781), // LCDC DU interrupt
    ELC_EVENT_SDHI0_OXMNIRQ                            = (782), // SDHI0 interrupt
    ELC_EVENT_SDHI0_OXASIOIRQ                          = (783), // SDHI0 SDIO accessinterrupt
    ELC_EVENT_SDHI1_OXMNIRQ                            = (784), // SDHI1 interrupt
    ELC_EVENT_SDHI1_OXASIOIRQ                          = (785), // SDHI1 SDIO accessinterrupt
    ELC_EVENT_PCIE0_INTA_RC                            = (786), // PCIE0 INTA interruptfor Root complex
    ELC_EVENT_PCIE0_INTB_RC                            = (787), // PCIE0 INTB interruptfor Root complex
    ELC_EVENT_PCIE0_INTC_RC                            = (788), // PCIE0 INTC interruptfor Root complex
    ELC_EVENT_PCIE0_INTD_RC                            = (789), // PCIE0 INTD interruptfor Root complex
    ELC_EVENT_PCIE0_INTMSI_RC                          = (790), // PCIE0 MSI interruptfor Root complex
    ELC_EVENT_PCIE0_INT_LINK_BANDWIDTH                 = (791), // PCIE0 Link widthchange interrupt forRoot complex
    ELC_EVENT_PCIE0_INT_EQUALIZATION_REQUEST           = (792), // PCIE0 LinkEqualization Requestinterrupt for Rootcomplex
    ELC_EVENT_PCIE0_INT_PM_PME                         = (793), // PCIE0 PM_PMEMessage receiveinterrupt for Rootcomplex
    ELC_EVENT_PCIE0_INT_DMA                            = (794), // PCIE0 Event interruptof DMA
    ELC_EVENT_PCIE0_INT_PCIE_EVT                       = (795), // PCIE0 Event interruptof PCIE
    ELC_EVENT_PCIE0_INT_MSG                            = (796), // PCIE0 Messagereceive interrupt
    ELC_EVENT_PCIE0_INT_ALL                            = (797), // PCIE0 ORedinterrupt of allinterrupt
    ELC_EVENT_PCIE0_TURN_OFF_EVENT                     = (798), // PCIE0PME_Turn_Off Msg.receive flag output forEndpoint
    ELC_EVENT_PCIE0_PMU_POWEROFF                       = (799), // PCIE0 POWEROFFindication on L2
    ELC_EVENT_PCIE0_D3_EVENT_F0                        = (800), // PCIE0 Non-D0 Statetransition requestreceive outputFunction #0 forEndpoint
    ELC_EVENT_PCIE0_D3_EVENT_F1                        = (801), // PCIE0 Non-D0 Statetransition requestreceive outputFunction #1 forEndpoint
    ELC_EVENT_PCIE0_CFG_PMCSR_PME_STATUS_WRITECLEAR_F0 = (802), // PCIE0PME_STATUS clearoutput Function #0for Endpoint
    ELC_EVENT_PCIE0_CFG_PMCSR_PME_STATUS_WRITECLEAR_F1 = (803), // PCIE0PME_STATUS clearoutput Function #1for Endpoint
    ELC_EVENT_PCIE0_FLR_REQ_F0                         = (804), // PCIE0 FLR requestFunction #0 forEndpoint
    ELC_EVENT_PCIE0_FLR_REQ_F1                         = (805), // PCIE0 FLR requestFunction #1 forEndpoint
    ELC_EVENT_PCIE1_INTA_RC                            = (806), // PCIE1 INTA interruptfor Root complex
    ELC_EVENT_PCIE1_INTB_RC                            = (807), // PCIE1 INTB interruptfor Root complex
    ELC_EVENT_PCIE1_INTC_RC                            = (808), // PCIE1 INTC interruptfor Root complex
    ELC_EVENT_PCIE1_INTD_RC                            = (809), // PCIE1 INTD interruptfor Root complex
    ELC_EVENT_PCIE1_INTMSI_RC                          = (810), // PCIE1 MSI interruptfor Root complex
    ELC_EVENT_PCIE1_INT_LINK_BANDWIDTH                 = (811), // PCIE1 Link widthchange interrupt forRoot complex
    ELC_EVENT_PCIE1_INT_EQUALIZATION_REQUEST           = (812), // PCIE1 LinkEqualization Requestinterrupt for Rootcomplex
    ELC_EVENT_PCIE1_INT_PM_PME                         = (813), // PCIE1 PM_PMEMessage receiveinterrupt for Rootcomplex
    ELC_EVENT_PCIE1_INT_DMA                            = (814), // PCIE1 Event interruptof DMA
    ELC_EVENT_PCIE1_INT_PCIE_EVT                       = (815), // PCIE1 Event interruptof PCIE
    ELC_EVENT_PCIE1_INT_MSG                            = (816), // PCIE1 Messagereceive interrupt
    ELC_EVENT_PCIE1_INT_ALL                            = (817), // PCIE1 ORedinterrupt of allinterrupt
    ELC_EVENT_PCIE1_TURN_OFF_EVENT                     = (818), // PCIE1PME_Turn_Off Msg.receive flag output forEndpoint
    ELC_EVENT_PCIE1_PMU_POWEROFF                       = (819), // PCIE1 POWEROFFindication on L2
    ELC_EVENT_PCIE1_D3_EVENT_F0                        = (820), // PCIE1 Non-D0 Statetransition requestreceive outputFunction #0 forEndpoint
    ELC_EVENT_PCIE1_D3_EVENT_F1                        = (821), // PCIE1 Non-D0 Statetransition requestreceive outputFunction #1 forEndpoint
    ELC_EVENT_PCIE1_CFG_PMCSR_PME_STATUS_WRITECLEAR_F0 = (822), // PCIE1PME_STATUS clearoutput Function #0for Endpoint
    ELC_EVENT_PCIE1_CFG_PMCSR_PME_STATUS_WRITECLEAR_F1 = (823), // PCIE1PME_STATUS clearoutput Function #1for Endpoint
    ELC_EVENT_PCIE1_FLR_REQ_F0                         = (824), // PCIE1 FLR requestFunction #0 forEndpoint
    ELC_EVENT_PCIE1_FLR_REQ_F1                         = (825), // PCIE1 FLR requestFunction #1 forEndpoint
    ELC_EVENT_DDRC_INT                                 = (826), // Interrupt signal fromthe DDR controller
    ELC_EVENT_DDRPHY_INT                               = (827), // Interrupt signal fromthe DDR PHY
    ELC_EVENT_DREQ                                     = (840), // External DMArequest
    ELC_EVENT_CAN0_CF_DMAREQ                           = (841), // CAFND0 Firstcommon FIFO DMArequest
    ELC_EVENT_CAN1_CF_DMAREQ                           = (842), // CAFND1 Firstcommon FIFO DMArequest
    ELC_EVENT_CAN_RF_DMAREQ0                           = (843), // CAFND RX FIFO 0DMA request
    ELC_EVENT_CAN_RF_DMAREQ1                           = (844), // CAFND RX FIFO 1DMA request
    ELC_EVENT_CAN_RF_DMAREQ2                           = (845), // CAFND RX FIFO 2DMA request
    ELC_EVENT_CAN_RF_DMAREQ3                           = (846), // CAFND RX FIFO 3DMA request
    ELC_EVENT_CAN_RF_DMAREQ4                           = (847), // CAFND RX FIFO 4DMA request
    ELC_EVENT_CAN_RF_DMAREQ5                           = (848), // CAFND RX FIFO 5DMA request
    ELC_EVENT_CAN_RF_DMAREQ6                           = (849), // CAFND RX FIFO 6DMA request
    ELC_EVENT_CAN_RF_DMAREQ7                           = (850), // CAFND RX FIFO 7DMA request
    ELC_EVENT_ADC120_WCMPM                             = (851), // ADC120 comparematch
    ELC_EVENT_ADC120_WCMPUM                            = (852), // ADC120 comparemismatch.
    ELC_EVENT_ADC121_WCMPM                             = (853), // ADC121 comparematch
    ELC_EVENT_ADC121_WCMPUM                            = (854), // ADC121 comparemismatch.
    ELC_EVENT_ADC122_WCMPM                             = (855), // ADC122 comparematch
    ELC_EVENT_ADC122_WCMPUM                            = (856), // ADC122 comparemismatch.
    ELC_EVENT_IOPORT_GROUP1                            = (857), // Input edge detectionof input port group 1
    ELC_EVENT_IOPORT_GROUP2                            = (858), // Input edge detectionof input port group 2
    ELC_EVENT_IOPORT_SINGLE0                           = (859), // Input edge detectionof single input port 0
    ELC_EVENT_IOPORT_SINGLE1                           = (860), // Input edge detectionof single input port 1
    ELC_EVENT_IOPORT_SINGLE2                           = (861), // Input edge detectionof single input port 2
    ELC_EVENT_IOPORT_SINGLE3                           = (862), // Input edge detectionof single input port 3
    ELC_EVENT_TCIV4_OF                                 = (863), // MTU4.TCNT overflow
    ELC_EVENT_TCIV4_UF                                 = (864), // MTU4.TCNTunderflow
    ELC_EVENT_TCIV7_OF                                 = (865), // MTU7.TCNT overflow
    ELC_EVENT_TCIV7_UF                                 = (866), // MTU7.TCNTunderflow
    ELC_EVENT_GPT00_0_ADTRGA                           = (867), // GPT00_0 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT00_0_ADTRGB                           = (868), // GPT00_0 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT00_1_ADTRGA                           = (869), // GPT00_1 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT00_1_ADTRGB                           = (870), // GPT00_1 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT00_2_ADTRGA                           = (871), // GPT00_2 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT00_2_ADTRGB                           = (872), // GPT00_2 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT00_3_ADTRGA                           = (873), // GPT00_3 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT00_3_ADTRGB                           = (874), // GPT00_3 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT00_4_ADTRGA                           = (875), // GPT00_4 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT00_4_ADTRGB                           = (876), // GPT00_4 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT01_0_ADTRGA                           = (877), // GPT01_0 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT01_0_ADTRGB                           = (878), // GPT01_0 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT01_1_ADTRGA                           = (879), // GPT01_1 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT01_1_ADTRGB                           = (880), // GPT01_1 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT01_2_ADTRGA                           = (881), // GPT01_2 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT01_2_ADTRGB                           = (882), // GPT01_2 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT01_3_ADTRGA                           = (883), // GPT01_3 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT01_3_ADTRGB                           = (884), // GPT01_3 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT01_4_ADTRGA                           = (885), // GPT01_4 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT01_4_ADTRGB                           = (886), // GPT01_4 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT02_0_ADTRGA                           = (887), // GPT02_0 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT02_0_ADTRGB                           = (888), // GPT02_0 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT02_1_ADTRGA                           = (889), // GPT02_1 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT02_1_ADTRGB                           = (890), // GPT02_1 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT02_2_ADTRGA                           = (891), // GPT02_2 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT02_2_ADTRGB                           = (892), // GPT02_2 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT02_3_ADTRGA                           = (893), // GPT02_3 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT02_3_ADTRGB                           = (894), // GPT02_3 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT02_4_ADTRGA                           = (895), // GPT02_4 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT02_4_ADTRGB                           = (896), // GPT02_4 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT03_0_ADTRGA                           = (897), // GPT03_0 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT03_0_ADTRGB                           = (898), // GPT03_0 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT03_1_ADTRGA                           = (899), // GPT03_1 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT03_1_ADTRGB                           = (900), // GPT03_1 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT03_2_ADTRGA                           = (901), // GPT03_2 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT03_2_ADTRGB                           = (902), // GPT03_2 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT03_3_ADTRGA                           = (903), // GPT03_3 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT03_3_ADTRGB                           = (904), // GPT03_3 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT03_4_ADTRGA                           = (905), // GPT03_4 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT03_4_ADTRGB                           = (906), // GPT03_4 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT04_0_ADTRGA                           = (907), // GPT04_0 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT04_0_ADTRGB                           = (908), // GPT04_0 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT04_1_ADTRGA                           = (909), // GPT04_1 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT04_1_ADTRGB                           = (910), // GPT04_1 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT04_2_ADTRGA                           = (911), // GPT04_2 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT04_2_ADTRGB                           = (912), // GPT04_2 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT04_3_ADTRGA                           = (913), // GPT04_3 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT04_3_ADTRGB                           = (914), // GPT04_3 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT04_4_ADTRGA                           = (915), // GPT04_4 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT04_4_ADTRGB                           = (916), // GPT04_4 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT05_0_ADTRGA                           = (917), // GPT05_0 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT05_0_ADTRGB                           = (918), // GPT05_0 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT05_1_ADTRGA                           = (919), // GPT05_1 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT05_1_ADTRGB                           = (920), // GPT05_1 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT05_2_ADTRGA                           = (921), // GPT05_2 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT05_2_ADTRGB                           = (922), // GPT05_2 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT05_3_ADTRGA                           = (923), // GPT05_3 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT05_3_ADTRGB                           = (924), // GPT05_3 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT05_4_ADTRGA                           = (925), // GPT05_4 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT05_4_ADTRGB                           = (926), // GPT05_4 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT06_0_ADTRGA                           = (927), // GPT06_0 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT06_0_ADTRGB                           = (928), // GPT06_0 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT06_1_ADTRGA                           = (929), // GPT06_1 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT06_1_ADTRGB                           = (930), // GPT06_1 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT06_2_ADTRGA                           = (931), // GPT06_2 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT06_2_ADTRGB                           = (932), // GPT06_2 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT06_3_ADTRGA                           = (933), // GPT06_3 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT06_3_ADTRGB                           = (934), // GPT06_3 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT06_4_ADTRGA                           = (935), // GPT06_4 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT06_4_ADTRGB                           = (936), // GPT06_4 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT07_0_ADTRGA                           = (937), // GPT07_0 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT07_0_ADTRGB                           = (938), // GPT07_0 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT07_1_ADTRGA                           = (939), // GPT07_1 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT07_1_ADTRGB                           = (940), // GPT07_1 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT07_2_ADTRGA                           = (941), // GPT07_2 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT07_2_ADTRGB                           = (942), // GPT07_2 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT07_3_ADTRGA                           = (943), // GPT07_3 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT07_3_ADTRGB                           = (944), // GPT07_3 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT07_4_ADTRGA                           = (945), // GPT07_4 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT07_4_ADTRGB                           = (946), // GPT07_4 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT08_0_ADTRGA                           = (947), // GPT08_0 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT08_0_ADTRGB                           = (948), // GPT08_0 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT08_1_ADTRGA                           = (949), // GPT08_1 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT08_1_ADTRGB                           = (950), // GPT08_1 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT08_2_ADTRGA                           = (951), // GPT08_2 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT08_2_ADTRGB                           = (952), // GPT08_2 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT08_3_ADTRGA                           = (953), // GPT08_3 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT08_3_ADTRGB                           = (954), // GPT08_3 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT08_4_ADTRGA                           = (955), // GPT08_4 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT08_4_ADTRGB                           = (956), // GPT08_4 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT09_0_ADTRGA                           = (957), // GPT09_0 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT09_0_ADTRGB                           = (958), // GPT09_0 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT09_1_ADTRGA                           = (959), // GPT09_1 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT09_1_ADTRGB                           = (960), // GPT09_1 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT09_2_ADTRGA                           = (961), // GPT09_2 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT09_2_ADTRGB                           = (962), // GPT09_2 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT09_3_ADTRGA                           = (963), // GPT09_3 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT09_3_ADTRGB                           = (964), // GPT09_3 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT09_4_ADTRGA                           = (965), // GPT09_4 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT09_4_ADTRGB                           = (966), // GPT09_4 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT09_5_ADTRGA                           = (967), // GPT09_5 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT09_5_ADTRGB                           = (968), // GPT09_5 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_GPT09_6_ADTRGA                           = (969), // GPT09_6 GTADTRAcompare match (A/DConverter StartRequest A)
    ELC_EVENT_GPT09_6_ADTRGB                           = (970), // GPT09_6 GTADTRBcompare match (A/DConverter StartRequest B)
    ELC_EVENT_NONE
} elc_event_t;

/** @} (end addtogroup BSP_MCU_RZT2H) */

/***********************************************************************************************************************
 * Exported global variables
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Exported global functions (to be accessed by other files)
 **********************************************************************************************************************/

/** Common macro for FSP header files. There is also a corresponding FSP_HEADER macro at the top of this file. */
FSP_FOOTER

#endif
